### ISSUE TITLE
Minor Formatting Issue: Format Check Numbers so They're Sortable

### ISSUE THREAD

**Issue by jonatversprite** [prowler-cloud/prowler#101]
Current Number format: 3.1, 3.2, 3.3, ... 3.10
Desired Number format: 3.01, 3.02, 3.03... 3.10

This will make it easier to sort the results in other tools.

**Comment by toniblyx** [comment]
Thanks @jonatversprite that makes sense to me. I think it should be backwards compatible just in case someone is using the existing output and parsing it anyhow. What if I add a ```-n``` option to make it sorted numeral (I don't know how to call it)?

**Comment by jonatversprite** [comment]
That sounds good to me. Thanks!

**Comment by toniblyx** [comment]
hey @jonatversprite can you test the latest version with -n option? It should work as you wanted. Thanks!

**Comment by jonatversprite** [comment]
Thank you for that fix.  It works as expected.  

I did notice a new unrelated issue, #103
