### ISSUE TITLE
Bug: 1.04 -> Failed conversion of access_key_1_last_rotated using format

### ISSUE THREAD

**Issue by jonatversprite** [prowler-cloud/prowler#103]
Let me know what other logs would help.  Here's a copy of the console output.

$ date
Mon Sep 11 10:59:05 EDT 2017
$ git clone https://github.com/Alfresco/prowler.git
Cloning into 'prowler'...
remote: Counting objects: 534, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 534 (delta 2), reused 3 (delta 1), pack-reused 527
Receiving objects: 100% (534/534), 217.04 KiB | 0 bytes/s, done.
Resolving deltas: 100% (275/275), done.
$ ./prowler -n -p $PROFILE -M csv > ~/Desktop/prowler/$PROFILE_prowler.csv

Generating "," delimited report on stdout for profile CardL_IDS, account $ACCOUNT_#
0.0 Show report generation info
...
1.04 Ensure access keys are rotated every 90 days or less (Scored)
Failed conversion of ``access_key_1_last_rotated'' using format ``%Y-%m-%d''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
./prowler: line 193: (1505141313 -  )/60/60/24: syntax error: operand expected (error token is ")/60/60/24")
./prowler: line 519: [: -gt: unary operator expected
1.05 Ensure IAM password policy requires at least one uppercase letter (Scored)
...11

**Comment by toniblyx** [comment]
Are you running it on linux or mac?
It seems to be using a wrong flag on the date command. The numbers enhancement is working fine, isn't it?

**Comment by jonatversprite** [comment]
$ uname -a
Darwin Jonathans-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by jonatversprite** [comment]
I tested on an Amazon Linux box:

1.04 Ensure access keys are rotated every 90 days or less (Scored)
date: invalid date ‘access_key_1_last_rotated’
./prowler: line 170: (1505088000 -  )/60/60/24: syntax error: operand expected (error token is ")/60/60/24")
./prowler: line 519: [: -gt: unary operator expected

**Comment by toniblyx** [comment]
ok, thanks. Working on it now

**Comment by toniblyx** [comment]
I can't reproduce it using either commands:
```
./prowler -p $PROFILE -n -c check104 -M csv
```
or 
```
./prowler -p $PROFILE -n -c check104
```

Can you try changing line 519 from this:
```
if [ $HOWOLDER -gt "90" ];then
```
to this one:
```
if [[ $HOWOLDER -gt "90" ]];then
```
Thanks.

**Comment by jonatversprite** [comment]
change made, here's the output

date: invalid date ‘access_key_1_last_rotated’
./prowler: line 170: (1505088000 -  )/60/60/24: syntax error: operand expected (error token is ")/60/60/24")

**Comment by toniblyx** [comment]
There was a conflict with certain user names ;) and now it is fixed.
