### ISSUE TITLE
Possible to not rely on the ~/.aws config?

### ISSUE THREAD

**Issue by ghost** [prowler-cloud/prowler#107]
I predominantly use API keys as environment variables by way of [apicreds](https://github.com/auraltension/apicreds) and thus haven't really ever needed to set up AWS local profiles (and would prefer not to given the local persistent plaintext creds).

I'm wondering if there's an easy way I can use prowler in this scenario? The tool seems pretty hardcoded to expect the aws config file to exist, but would love to give it a spin.

**Comment by toniblyx** [comment]
Hi @d-j-c, makes sense what you asking. I should make first prowler look if env vars credentials are set, not sure if it should be a default behavior or a new option like "prowler -e" to load creds from environment variables, what do you think?

**Comment by TaiSHiNet** [comment]
`awscli` should do this on it's own if variable names correlate with their specification, so I'm guessing the `-e` would be used to bypass this block 
```if [[ ! -f ~/.aws/credentials ]]; then
  echo -e "\n$RED ERROR!$NORMAL AWS credentials file not found (~/.aws/credentials). Run 'aws configure' first. \n"
  return 1
fi```

**Comment by toniblyx** [comment]
Actually, what AWS recommends in official docs is to follow this order:

1. Command line options
2. Environment variables
3. The AWS credentials file
4. The CLI configuration file
5. Container credentials
6. Instance profile credentials

What I'm testing now is to look first at 2, then 3, then 6. 
In my opinion, 1 is not good idea, 4 is covered with 3 and 5 is irrelevant so far.  Doing it in that order by default is the way to be consistent with AWS.

More info here http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#config-settings-and-precedence

**Comment by TaiSHiNet** [comment]
Yeah but all those are already handled by awscli, so if you were to bypass the `~/.aws/credentials` check, it should automatically pick up env variables from apicreds

**Comment by ghost** [comment]
yeah I had commented out the check @TaiSHiNet 

```
-if [[ ! -f ~/.aws/credentials ]]; then
-  echo -e "\n$RED ERROR!$NORMAL AWS credentials file not found (~/.aws/credentials). Run 'aws configure' first. \n"
-  return 1
-fi
```

However the expectation of a profile name is baked throughout the script and the region is hardcoded so I still get failures.

```
$ aws sts get-caller-identity --output json --profile default --region ap-southeast-2 --query "Account" | tr -d '"'

The config profile (default) could not be found
```

And removing --profile I have some success.

```
$ aws sts get-caller-identity --output json --region ap-southeast-2 --query "Account" | tr -d '"'
062921715532
```

There seems to be agreement that working from env variables is desirable so if I'm not beaten to it I'll do more work on it and submit a PR.

**Comment by toniblyx** [comment]
ok, I got it. I'm working on it now, few changes have to be done to make it work though.

**Comment by toniblyx** [comment]
Ok, there you go guys @d-j-c @TaiSHiNet let me know if it works fine now. I have tested 3 use cases and worked for me: 
1- having creds on environment variables OK
2- having only a default profile in ~/.aws/credentials OK
3- having additional profiles with tokens OK

Haven't tested with IAM instance profile yet but should work (or at least functionality added). Any feedback is welcome. Thanks!
