### ISSUE TITLE
Cross-Account Role STS Credentials Ignored

### ISSUE THREAD

**Issue by virtualjj** [prowler-cloud/prowler#11]
I have multiple AWS accounts in which I only keep users in one account and then use cross-account roles to access the other accounts with STS like this:

`aws sts assume-role --role-arn "arn:aws:iam::1XXXXXXXXXXX:role/UAT-ENGINEERS" --role-session-name "CIS-Benchmark-Scan" --token-code <MFA Code>  --serial-number arn:aws:iam::6XXXXXXXXXXX:mfa/bob.hope`

After running this command I receive STS credentials and export them using these commands*

`export AWS_ACCESS_KEY_ID=<Enter AccessKeyId>`
`export AWS_SECRET_ACCESS_KEY=<Enter SecretAccessKey>`
`export AWS_SESSION_TOKEN=<Enter SessionToken>`

However, when I run ./prowler it isn't using the STS credentials.

**Comment by toniblyx** [comment]
Other great catch @virtualjj! We also use STS but I wrote an internal tool that writes that credentials including the token to ~/.aws/credentials like:

```
[customprofile]
aws_access_key_id=YYYY
aws_secret_access_key=XXXX
aws_session_token=ZZZZ
```

Then you can run prowler using ./prowler -p customprofile -r us-east-1. I might add the capability to read environment variables as well in case ~/.aws/credentials is not properly configured. WDYT?

**Comment by toniblyx** [comment]
I have tested using env variables with token and it works without using --profile option so it won't work in prowler as it is now. So any custom profile has to be declared in ~/.aws/credentials

**Comment by virtualjj** [comment]
Got it thanks! As a workaround I just simply created a temporary user in the target account to perform the audit.

**Comment by toniblyx** [comment]
Cool!
