### ISSUE TITLE
Does the script support LDAP Authentication to AWS?

### ISSUE THREAD

**Issue by guerilla7** [prowler-cloud/prowler#125]
Or any plans supporting it in the future?

https://aws.amazon.com/blogs/security/how-to-connect-your-on-premises-active-directory-to-aws-using-ad-connector/

**Comment by toniblyx** [comment]
I don´t see why not, you only need to be able run awscli commands against your account.

**Comment by toniblyx** [comment]
Hi @guerilla7, in case I wasn't clear in my previous comment. Prowler uses aws-cli authentication methods as stated here http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html if you can run aws-cli commands with LDAP auth, you can run Prowler.
