### ISSUE TITLE
Exit code should indicate status of results

### ISSUE THREAD

**Issue by dan-petty** [prowler-cloud/prowler#126]
It would be nice if exit code for reviews that indicate warnings or failures to exit with a non-zero code so that it integrates nicely with build tooling.

**Comment by toniblyx** [comment]
Hi @mixmatch, thanks for your comment. Can you please give me an example to better understand your use case?

**Comment by dan-petty** [comment]
I want to run this daily, or following automated aws configuration, in Jenkins and have the build fail if there are warnings in the results. Currently the script always exists with 0 status.

**Comment by dan-petty** [comment]
Examples:
https://support.smartbear.com/testcomplete/docs/working-with/automating/command-line-and-exit-codes/exit-codes.html
https://llvm.org/docs/CommandGuide/lit.html
https://github.com/FriendsOfPHP/PHP-CS-Fixer#exit-codes

**Comment by dan-petty** [comment]
Here is how I did it to suit my own needs. Might want a cleaner implementation if you decide to do this:
https://github.com/Alfresco/prowler/compare/master...mixmatch:master

**Comment by toniblyx** [comment]
ok, thanks @mixmatch I'll take a look and see what I can do :)

**Comment by toniblyx** [comment]
Hi @mixmatch you can check now that enhancement. For max items, instead of removing the option you can just use option `-m 1000` for example. I'll close this case, don't hesitate to open it again if it doesn't work properly for you.
