### ISSUE TITLE
check124 grep for version Id

### ISSUE THREAD

**Issue by shivankar-madaan** [prowler-cloud/prowler#132]
I have two policies with almost the same names for example
arn:aws:iam::123:policy/admin-policy
arn:aws:iam::123:policy/admin-policy-full
So when this command runs on 
https://github.com/Alfresco/prowler/blob/master/prowler#L859
The output throws 2 version Id's
`aws iam list-policies --region us-east-1 --query 'Policies[*].[Arn,DefaultVersionId]' --output text| grep -w "arn:aws:iam::123:policy/admin-policy" | awk '{ print $2}'

arn:aws:iam::123:policy/admin-policy        v1      

arn:aws:iam::123:policy/admin-policy-full       v1`

The `-w` option didn't work as it does only a exact word match as per this
https://stackoverflow.com/questions/44315564/grep-fixed-string-is-not-grepping-exact-string-string-end-with-extra-character

Is it possible to have fix around this as well.
Thanks

**Comment by wassies** [comment]
Hi @shivankar-madaan @toniblyx 

Was this issue resolved in commit d8879d9 ?

Cheers.

**Comment by shivankar-madaan** [comment]
Yes looks good now
Sorry I did not take a fresh pull
It is working now.
