### ISSUE TITLE
Incorrect text output for check36

### ISSUE THREAD

**Issue by dan-petty** [prowler-cloud/prowler#133]
Currently:
`textOK "CloudWatch group $group found with metric filters and alarms for usage of root account"`

Should be:
`textOK "CloudWatch group $group found with metric filters and alarms for AWS Management Console authentication failures"`

https://github.com/Alfresco/prowler/blob/master/prowler#L1182

**Comment by toniblyx** [comment]
Thanks @mixmatch, would you mind to send a PR with the change? That would make it quicker to fix it. Otherwise I'll try to do it later. Thanks!

**Comment by wassies** [comment]
Hi @mixmatch @toniblyx 

Can we mark this one off as resolved?

**Comment by toniblyx** [comment]
Cool, doing it now. Thanks!
