### ISSUE TITLE
Add option to only display warnings/failures

### ISSUE THREAD

**Issue by sidewinder12s** [prowler-cloud/prowler#140]
It'd be nice if you could have the tool only output failures. Some of these reports can be massive/difficult to parse for people who are not familiar with it, such as when your trying to audit for a large number of accounts at the same time or forwarding results to end users.

That seem reasonable?

**Comment by toniblyx** [comment]
Hi @sidewinder12s, that does make a lot of sense, let me see how hard is to implement it. Thanks!

**Comment by sidewinder12s** [comment]
This is also fairly easy to do with grep/bash for anyone with a similar use case. Might still be nice to have it built in.
```
    ./prowler -M "${PROWLER_FORMAT}" -r "${AWS_REGION}" > "${report_file}" 2>/dev/null || true
    if [ -f "${report_file}" ]; then
      warnings_count=$(grep WARNING "${report_file}" | wc -l)
      echo "${TEAM} WARNINGS (${TEAM_EMAIL}): ${warnings_count}"
      echo "Lines with 'INFO' are stripped"
      echo "Lines with 'OK' result are stripped"

      # Skip the INFO & OK! messages, but emit everything else
      grep -v "INFO\|OK" "${report_file}"
```

**Comment by toniblyx** [comment]
Implemented here https://github.com/toniblyx/prowler/pull/441
