### ISSUE TITLE
Add option to recode error codes for textOK, textNotice, textWarn

### ISSUE THREAD

**Issue by chickenriggies** [prowler-cloud/prowler#145]
It would be convenient to have the ability to remap the return codes for these functions. Our CI/CD system reports a "build failure" whenever a textWarn is called -- which is expected in some cases, but we are currently just interested in knowing whether the prowler run was successful or not.

**Comment by toniblyx** [comment]
Can you give me an example to figure out what is the best way to implement it here? Thanks

**Comment by chickenriggies** [comment]
./prowler --textWarnExitStatus 0 --textOKExitStatus=0 --textWarnExitStatus=0

A very minor request and environmentally specific to us. It was easy enough for us to override the variables.

**Comment by toniblyx** [comment]
Hi @hb3b, I didn't forget this, just trying to add more checks. If you can send a PR with just a couple of examples to know exactly how to do it, would be appreciated, I don't really know how to make it.

**Comment by toniblyx** [comment]
hey @hb3b, do you still need this feature with the current status of Prowler? Thanks!

**Comment by toniblyx** [comment]
if you need it please feel free to open it again and provide some more information. Thanks again.
