### ISSUE TITLE
Add check for internet facing ELBs

### ISSUE THREAD

**Issue by sidewinder12s** [prowler-cloud/prowler#147]
Another extra check for internet facing ELBs. Probably environment specific for people but if you generally use internal resources this could be a red flag.

**Comment by toniblyx** [comment]
Thanks @sidewinder12s, this may be something more informational than a warning because it depends on the deployment and use case.

**Comment by toniblyx** [comment]
I get it with a query like this one:
`aws elb describe-load-balancers --query "LoadBalancerDescriptions[?Scheme == 'internet-facing'].LoadBalancerName" --output text`

Informational then? Still not sure if to add it as extra.

**Comment by sidewinder12s** [comment]
Generally we have been starting to use Prowler to just try and get information on the public footprint of accounts, in addition to general security issues like IAM/CloudTrail configuration. I guess adding it to Prowler itself would depend on if you guys see the same use case for Prowler, though if #153 gets done it might just be moot.

**Comment by toniblyx** [comment]
I'm fine adding this check as an extra, obviously it will INFO or WARN or just OK depending on the use case, like for a deliberately open S3 bucket, but is good info to have.

**Comment by sidewinder12s** [comment]
Maybe add another called NOTICE? Info is kinda used for prowler information and warn is used for things you really should fix whereas this is more informational. I do see that some of the INFO stuff is NOTICE in the code so maybe that would require a bigger change.

I should have a PR that adds this in a bit.

**Comment by toniblyx** [comment]
Sounds good @sidewinder12s if you can PR that is even better. Thanks!
