### ISSUE TITLE
Add extra check for RDS CloudWatch logging

### ISSUE THREAD

**Issue by chickenriggies** [prowler-cloud/prowler#149]
Feature request to check that all RDS instances are reporting audit, {error log, general log, slow query log} logs to CloudWatch.

**Comment by toniblyx** [comment]
Hi @hb3b, is that option the `DBInstanceStatus` property running this command?
`aws rds describe-db-instances`
I'm not sure if that's more a performance check than a security check.

**Comment by toniblyx** [comment]
added in https://github.com/toniblyx/prowler/commit/62991cfb48bb3485ae2a8ee5e6032395db693540
