### ISSUE TITLE
An error occurred (TrailNotFoundException) when calling the GetTrailStatus operation:

### ISSUE THREAD

**Issue by virtualjj** [prowler-cloud/prowler#15]
I'm getting a strange error at https://github.com/Alfresco/aws-cis-security-benchmark/blob/master/prowler#L499

![image](https://cloud.githubusercontent.com/assets/10323889/18916970/4fe4fec4-85d1-11e6-8b29-af061002509a.png)

However, when I run the command manually it works:

`aws cloudtrail get-trail-status --name $trail --query 'LatestCloudWatchLogsDeliveryTime' --output text|grep -v None`

![image](https://cloud.githubusercontent.com/assets/10323889/18917084/9ff0bc32-85d1-11e6-8e84-1a24f0c44fe3.png)

**Comment by toniblyx** [comment]
Are you using the same profile and region in both prowler and your command? I see that your command is using default.

**Comment by virtualjj** [comment]
Interesting - okay here is the output of what I ran:

![image](https://cloud.githubusercontent.com/assets/10323889/18917671/6d3be382-85d3-11e6-8672-e28a71321d13.png)

For some reason I was thinking that the region would automatically pass through. Running with the following switches resolves the issue:

`./prowler -p default -r eu-west-1 -c check24`

![image](https://cloud.githubusercontent.com/assets/10323889/18917751/9ef36922-85d3-11e6-8473-290a413bf42d.png)

**Comment by toniblyx** [comment]
Oh yes, I forgot to mention that if no region is specified, default region is us-east-1, look at here: https://github.com/Alfresco/aws-cis-security-benchmark/blob/master/prowler#L51 and https://github.com/Alfresco/aws-cis-security-benchmark/blob/master/prowler#L167

Despite that, remember that some checks look for issues in all regions as specified in the CIS paper.

**Comment by toniblyx** [comment]
I'm going to close it since it is already mentioned on the README I have just updated.
