### ISSUE TITLE
Add check to discover ElasticSeach service domains opened to the internet

### ISSUE THREAD

**Issue by toniblyx** [prowler-cloud/prowler#151]
List ES domains:

`aws es list-domain-names --region us-east-1 --query 'DomainNames[*].DomainName' --output text`

Then, for a given domain look at the AccessPolicies and parse it to check if Principal:* is set:

`aws es describe-elasticsearch-domains  --region us-east-1 --domain-names NAME --query 'DomainStatusList[*].AccessPolicies'| awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}'| awk '/Principal/ && !skip { print } { skip = /Deny/} '|grep \"Principal|grep \*`

**Comment by sidewinder12s** [comment]
Might want to also make sure this doesn't catch/flag ES domains that are exposed to a VPC only?

**Comment by toniblyx** [comment]
Thanks @sidewinder12s, I didn't think about that case.
Added a new check extra716 on PR #170
