### ISSUE TITLE
Dynamically load new checks

### ISSUE THREAD

**Issue by endzyme** [prowler-cloud/prowler#153]
Would be a nice feature to implement an inferred check based on a file in path. Potentially could be a command line param too (or both).

There would be some obvious kinks to work out with your naming contract (check... or extra... + optional leading zero on ID). There would also need to be some TITLE and ID magic happening in the background but that could also be a convention requirement of the function instead of defined like it is now.

Anywho - food for thought -- then people could augment their own checks without having to clone and edit main prowler checks.

Example of implementation:
In Prowler we're assuming `this...` is the prefix of all the custom checks.
```bash
#!/bin/bash

# Source the checks
if [ -f prowler.checks ]; then
  source prowler.checks

  # create array of checks
  MYARR=()

  # Find the functions defined in some namespace
  for func in $(declare -F|sed 's/^declare -f //') ; do
    if [[ ${func} =~ ^this[0-9]{2,3} ]]; then
      MYARR+=(${func})
    fi
  done

  # List out what you find
  for i in ${MYARR[@]}; do
    echo i found function: $i
  done

  # Run the checks potentially
  echo "I would have run the following 'this' checks"
  echo ${MYARR[@]} | tr " " ";"

fi
```

Example prowler.checks
```bash
#!/bin/bash

function this7() { echo this; }

function this71() { echo thing2; }

function this732() { echo that; }

function that() { echo nope; }

function this_declare() { echo wat; }

function this731() { echo something; }
```

Example output from the above code
```bash
i found function: this71
i found function: this731
i found function: this732
I would have run the following this checks
this71;this731;this732
```

**Comment by toniblyx** [comment]
Hi @endzyme, I like the idea and have a lot of sense to make Prowler easier to extend. I was also thinking about re-factorize the code to allow easier adding of checks. I plan to add a bunch of new checks over the next weeks and was wondering a better way to do so. Thanks for heads up.

**Comment by endzyme** [comment]
No problemo - I can also dedicate some time to this in the coming months since we have some stuff at work that aligns.

**Comment by toniblyx** [comment]
If you can help on that would be great, we can probably break down every check in its own 3 parts (functions?): tittle, check code and eventual fix recommendation. Thanks!

**Comment by sidewinder12s** [comment]
This would be sweet, it'd make it very easy for users to add their own 'check files' with any checks that either are not in Prowler or that you guys don't want to add to the tool.

**Comment by toniblyx** [comment]
Requirements that I see also for this is to make sure any new check is applied to all existing regions (except GovCloud, China and Secret). And to define a foundation for every check command (awscli minimum values)

**Comment by endzyme** [comment]
So these checks are starting to feel like classes to me in terms of an inherited set of functions (title, suggested fix, score#, etc) and allowing custom  config on each type of test. I know it would be a major refactor but a real language might be able to title better maintainability later on. Something like python feels right to me. 

This could also be a refactor that supports running checks as any type of script and not only bash functions. I'm thinking python would be good here. 

This is probably outside the scope of this particular issue and might not fully align with your vision. @toniblyx - definitely interested in helping where I can.

**Comment by toniblyx** [comment]
Amazon already made a python implementation of CIS benchmark a little bit after Prowler (https://github.com/awslabs/aws-security-benchmark). I like python too but can't write checks as quick as with bash. 

Support third party checks with any language sounds like be good idea anyway. 

I'll take a look to the way that Lynis is doing that for linux hardeing, it is way more comprehensive than Prowler and it is also bash and widely used. Actually, I think it is not very important what is underneath (language), what is important is to make any collaboration easier that currently.

Thanks for your feedback @endzyme, good ideas!

**Comment by endzyme** [comment]
Sounds good! Thanks!

**Comment by toniblyx** [comment]
This is now supported with v2.0 beta, in devel branch so far, @endzyme can you check it out? Your feedback is welcomed. I'll close this issue, feel free to open it later if needed.

**Comment by endzyme** [comment]
Thanks @toniblyx - We'll be revisiting this project this month - definitely will check it out soon. Thanks again for your hard work on this!!

**Comment by endzyme** [comment]
At first glance this looks awesome - A+. Thanks for the implementation and extensibility.
