### ISSUE TITLE
Support for resources whitelist (leave resources out of checks)

### ISSUE THREAD

**Issue by endzyme** [prowler-cloud/prowler#154]
Would be nice to have environment definable suppressions and ignores:

An example would be to ignore `check73` if `bucket` = `my-known-problem-bucket`.

I am envisioning a file based approach, either one file for all suppressions with a config loader, or potentially a file per check so you can rely on conventions for loading your ignore list.

Example:
```text
# File Name: check73.suppressions
suppress=()
suppress+=('my-known-problem-bucket')
suppress+=('another-problem-bucket')
```

Easier examples would be line separated values or comma perhaps. Lots of options but would be nice.

**Comment by toniblyx** [comment]
Thanks @endzyme, I think it may be useful for some cases. What is your use case exactly, don't you want to find wrongly configured (deliberately or not) assets? Are you using any kind of automation or CD/CI with Prowler? You can always `grep -v my-known-problem-bucket` to remove the error, I know it seems probably a bit dirty, but enough. Even with a eventual scoring system, you will always know how your account/accounts are in terms of security configuration best practices. What do you think?

**Comment by endzyme** [comment]
Thanks for being so quick to respond. 

Use Case: Some assets aren't misconfigured but are intentionally configured in a certain way that may be against recommendations. An example would be S3 buckets that are public, that could be a business decision that should be ignored.

In terms of `grep`ing our way out of the problem, that seems like a fine MVP. Longer term I think it would be prudent to be able to configure suppressions but I can see how difficult that could be based on all the different ways checks are performed (may require secondary function implementations for filtering, which means probably not bash). 

I am fine closing this for now and using `grep` solution.

**Comment by toniblyx** [comment]
S3 use case is very common, we have the same case. I think this can be also addressed if I implement somehow an option to only show `WARN` instead of `OK + WARN`. I'll keep it in mind. Thanks @endzyme

**Comment by toniblyx** [comment]
I've been thinking about this: whitelist! I guess the easier way to implement it is creating a file with all whitelisted devices by its resource id, somethign like `-w whitelist.txt`:
```
check710 i-01234567890123456788
check710 i-01234567890123456789
check75 sg-0123456788
check75 sg-0123456789
```

**Comment by endzyme** [comment]
This would be awesome

**Comment by sidewinder12s** [comment]
The whitelist is probably better than grep as it gives us the option to start building an approved list of resources to ignore.

**Comment by sidewinder12s** [comment]
I had started doing this in an Excel sheet with lookups, which sorta worked. Only feedback on that would be making it so you can easily add a comment to each lined exception.

**Comment by toniblyx** [comment]
I've been thinking in a small function that `grep -v` whatever is needed per each check... Can be loaded from a text file per line or something like this:
```
check26:bucket111,bucket222,bucket333
```
 I'm busy with other things until next week, I'll play with it soon. WDYT?

**Comment by QuantumBJump** [comment]
I like this idea!

Just to provide another possible use case for this: `extra718` checks for server access logging on s3 buckets. However, afaik it is not recommended to activate server access logging on the buckets which are themselves used to store other buckets' server access logs. It would be useful to be able to exclude these buckets from the check without turning the whole thing off.

Example:
```
PASS! Bucket some-bucket has server access logging enabled
PASS! Bucket some-other-bucket has server access logging enabled
FAIL! Bucket server-access-logs has server access logging disabled! <- this is undesirable
```
