### ISSUE TITLE
Display IPs/DNS endpoints for resources

### ISSUE THREAD

**Issue by sidewinder12s** [prowler-cloud/prowler#158]
For checks like 7.8-10, do you guys have any opposition to outputting the DNS/IP addresses of the resources it finds into the reports?

I wasn't sure if you'd just want to stick to AWS resource names but we're looking at trying to dump lists of IPs from Prowler to then point scanning tools at.

**Comment by toniblyx** [comment]
I think is good to have them. At the end of the day we run Prowler to find and identify security flaws to fix them asap or notify them. Having IP/Name of the resources definitely help on that, go for it.
