### ISSUE TITLE
Bug: Missing --profile option in extra75

### ISSUE THREAD

**Issue by jonatversprite** [prowler-cloud/prowler#159]
LIne 1711
SG_NOT_USED=$($AWSCLI ec2 describe-network-interfaces $PROFILE_OPT --region $regx --filters "Name=group-id,Values=$SG_ID" --query "length(NetworkInterfaces)" --output text)

The aws command is missing the --profile flag

**Comment by toniblyx** [comment]
Hi @jonatversprite, actually $PROFILE_OPT variable adds it if needed.

**Comment by jonatversprite** [comment]
My mistake
