### ISSUE TITLE
Add checks from "Three-tier Web" benchmark

### ISSUE THREAD

**Issue by mbode** [prowler-cloud/prowler#179]
It would be nice if prowler could also execute checks from the [CIS AWS Three-tier Web Benchmark](https://d1.awsstatic.com/whitepapers/compliance/CIS_Amazon_Web_Services_Three-tier_Web_Architecture_Benchmark.pdf) additionally to the AWS Foundations Benchmark.

**Comment by toniblyx** [comment]
Thant's a good idea @mbode, I already added some checks with that CIS benchmark in mind to the extras section. Not all of them work fine without a bunch of arguments so I have to think the best way to add them. I also would like to refactorise the code to make it easier to add checks and make it a bit faster. That can be for v2... and more to come :)

**Comment by toniblyx** [comment]
I'm going to close this one since extras group has most of the required checks and more coming!
