### ISSUE TITLE
check110 Returns False Even When Number of passwords to remember Greater Than 23

### ISSUE THREAD

**Issue by virtualjj** [prowler-cloud/prowler#18]
Check 110 is returning FALSE even though **Number of passwords to remember** is set to 24.

Manually running the command confirms that my **Number of passwords to remember** is set to 24

![image](https://cloud.githubusercontent.com/assets/10323889/19148982/7e333794-8bfa-11e6-84ae-7f3fa21f88c6.png)

I resolved issue by changing https://github.com/Alfresco/aws-cis-security-benchmark/blob/master/prowler#L371

FROM

`COMMAND110=$($AWSCLI iam get-account-password-policy --profile $PROFILE --region $REGION --query 'PasswordPolicy.PasswordReusePrevention' | grep PasswordReusePrevention | awk -F: '{ print $2 }'|sed 's/\ //g'|sed 's/,/ /g')`

TO

`COMMAND110=$($AWSCLI iam get-account-password-policy --profile $PROFILE --region $REGI    ON --query 'PasswordPolicy.PasswordReusePrevention')`

![image](https://cloud.githubusercontent.com/assets/10323889/19149140/51495a82-8bfb-11e6-84f7-b5170767bfef.png)

**Comment by toniblyx** [comment]
Thanks @virtualjj I have just fixed it adding a --output text and better explanation. PR #22
