### ISSUE TITLE
awk ignorecase causes false positives on OSX

### ISSUE THREAD

**Issue by crashGoBoom** [prowler-cloud/prowler#184]
Hi!

Noticed some false positives on a few reports. Looked into it further and they were ran using OSX. Since the implementation of awk on OSX is not gawk the [IGNORECASE=1](https://github.com/Alfresco/prowler/blob/master/prowler#L1257) option that is used in several checks will not work as expected. Using tolower should provide better OSX support without requiring a specific version of awk.

Let me know and I can open a PR with a fix for this. Thanks!

**Comment by toniblyx** [comment]
Hi @crashGoBoom, thanks for your feedback.
Actually I write Prowler in OSX and test it in Linux, so I try to make sure all commands work for darwin/bsd and gnu binaries but some may fail or don't work as expected. Can you please provide what checks number are you referring and some sample output in your use case to test myself and reproduce the issue? For example, tell me resource names that are failing for you, or are you talking about the command itself?

**Comment by crashGoBoom** [comment]
@toniblyx Hi! Yeah I am referring to the awk command itself which uses the option `IGNORECASE` in several checks such as [3.3](https://github.com/Alfresco/prowler/blob/master/prowler#L1257). Note the reason [here](https://www.gnu.org/software/gawk/manual/gawk.html#Case_002dsensitivity) is that `IGNORECASE` is specific to the gnu version of awk.

> Another method, specific to gawk, is to set the variable IGNORECASE to a nonzero value

Whereas the use of `tolower` would work with any POSIX-compliant awk such as the default OSX version.

The tricky part is that it doesnt throw an error or anything it just can't find whatever you are searching for since the ignorecase option doesnt actually get used. Hope this helps!

**Comment by toniblyx** [comment]
Got it, thanks for clarifying. Probably is better to convert lowercase before filtering with awk. Thoughts?

**Comment by crashGoBoom** [comment]
Yep sounds good to me!

**Comment by toniblyx** [comment]
Can you please try changing line https://github.com/Alfresco/prowler/blob/master/prowler#L1257
to this one and test?
```
HAS_ALARM_ASSOCIATED=$($AWSCLI cloudwatch describe-alarms $PROFILE_OPT --region $CLOUDWATCH_LOGGROUP_REGION --query 'MetricAlarms[].MetricName' --output text | tr '[:upper:]' '[:lower:]'| grep -Ei '\/userIdentity\/|\/Root\/|\/AwsServiceEvent\/')
```
If it works for you in linux and osx I fix the code.

**Comment by crashGoBoom** [comment]
Hi! I just tested in linux and osx and the grep command does not appear to work. 
`grep (GNU grep) 3.1` on osx and...
`grep (GNU grep) 2.27` on linux.
Works as expected if I modify the grep command to `grep -Ei 'userIdentity|Root|AwsServiceEvent'`.

**Comment by toniblyx** [comment]
ok, thanks for testing it. To make sure, sorry if it sounds redundant, this command works then?

`HAS_ALARM_ASSOCIATED=$($AWSCLI cloudwatch describe-alarms $PROFILE_OPT --region CLOUDWATCH_LOGGROUP_REGION --query 'MetricAlarms[].MetricName' --output text | tr '[:upper:]' '[:lower:]'| grep -Ei 'userIdentity|Root|AwsServiceEvent')`

**Comment by crashGoBoom** [comment]
@toniblyx Yep that works for me on both it seems. Thanks for taking a look at this!

**Comment by toniblyx** [comment]
Great! I'll do a PR with that change as soon as I can, I'm adding and fixing few more things as well :) 
Thanks!
