### ISSUE TITLE
Native multi-account support instead of bash trick

### ISSUE THREAD

**Issue by toniblyx** [prowler-cloud/prowler#185]
Currently, we can run Prowler to multiple accounts using a bash trick like this:
```
grep -E '^\[([0-9A-Aa-z_-]+)\]'  ~/.aws/credentials | tr -d '][' | shuf |  \
xargs -n 1 -L 1 -I @ -r -P 4 ./prowler -p @ -M csv  2> /dev/null  >> all-accounts.csv
```
A desired feature is to be able to check multiples AWS accounts without that trick and just using a command option. Prowler should look at `~/.aws/credentials` file if `-a` is set as parameter. 

Output would be mandatory in CSV and creating a report therefore `-M csv` would be assumed.

**Comment by n8zwn** [comment]
If I don't specify the credentials in that file, how do I get prowler to use the assume role functionality? I have one account it should hit by default, but the rest are using an assume role.

**Comment by toniblyx** [comment]
Also explain how to use prowler with the assume role functionality

**Comment by sidewinder12s** [comment]
Would be useful if the assume role functionality let you run against multiple accounts at the same time.

**Comment by toniblyx** [comment]
Agreed 100%, I need to find time to write down how to do that, I think it is more about documentation than a feature.

**Comment by cbchhaya** [comment]
I am happy to document how to use `assume-role` since I am wrapping the main prowler script here in an `sts assume-role` call already. The "run" account does not have any privileges besides being able to assume a named role in every account it scans. Is that OK? Please let me know where to document. We'll need corresponding `role` and `accounts` flags as input.

Another option is to point prowler to the organization and use credentials that have permission to enumerate accounts in org followed by assuming role in each.

**Comment by toniblyx** [comment]
Hi @cbchhaya yes please, it would be great if we can have that properly documented, you can add that information here and I'll add it in to the repository and linked inside README.md, probably is time for a proper documentation site, but in the meantime we can add it as a md file. Thanks!

**Comment by cbchhaya** [comment]
Here you go. The requirements are:

1. An identically named role in every account - let's call this `SecurityScanningRole`
2. An IAM user for running prowler in your InfoSec/monitoring account - let's call this `u_scanner`
3. This role must have the `SecurityAudit` AWS-Managed Policy attached to it
4. This role, in every account, must have a trust relationship with the `u_scanner` user in your InfoSec/monitoring account
5. You need credentials for `u_scanner` in `.aws/credentials` already
6. You need `jq` installed

Assuming this setup, let's say we want to scan for cislevel1 and group2 in us-east-1. Pass in the list of accounts as an argument to the script below:

```
for account in $@
do
  {
    for scan_group in "cislevel1" "group2"
    do
      {
        unset AWS_SESSION_TOKEN
        assumed_role=$(aws sts assume-role --role-arn arn:aws:iam::${account}:role/SecurityScanningRole --role-session-name Prowler)
        export AWS_ACCESS_KEY_ID=$(echo $assumed_role | jq .Credentials.AccessKeyId | xargs)
        export AWS_SECRET_ACCESS_KEY=$(echo $assumed_role | jq .Credentials.SecretAccessKey | xargs)
        export AWS_SESSION_TOKEN=$(echo $assumed_role | jq .Credentials.SessionToken | xargs)
        outputfile=${account}-${scan_group}-results.txt
        prowler -f us-east-1 -r us-east-1 -g $(scan_group) -M json -b > ${outputfile}
      }
    done
  }
done
```

I will write up a more detailed post with pics and link to it here.

Let me know if this helps.

Cheers!

**Comment by toniblyx** [comment]
having this feature #445  implemented we can close this one as well since it is probably the best way to do multi-account checks without tricks, just using a while or for to do it across all needed accounts.
