### ISSUE TITLE
Add scheduled scans and reporting via e-mail

### ISSUE THREAD

**Issue by nealpeters86** [prowler-cloud/prowler#186]
Hello,

Is it possible to schedule scans (once a day) and then report via e-mail or a published webpage. 
If there are changes (new risks) is it possible to send an e-mail ?

**Comment by toniblyx** [comment]
Hi @nealpeters86, thanks for your comment. I understand your requirement, I know about people already doing that with the existing version of Prowler. You just need to run prowler in a cronjob and export it as CSV (`-M csv`), then compare them and send differences as alerts when needed, I have heard different ways to make it happen, not challenging at all, you can even import results in a DB. Doing that natively in Prowler is not planned. My main goal is to improve it around use cases, add new check groups, make it more efficient and add more checks to make the tool more comprehensive.
