### ISSUE TITLE
check28 - Warning! for AWS Default KMS Keys

### ISSUE THREAD

**Issue by virtualjj** [prowler-cloud/prowler#19]
So this is an interesting one - for check28 I get two keys are not set to rotate:

![image](https://cloud.githubusercontent.com/assets/10323889/19157040/f42188f6-8c1e-11e6-8259-545155f73470.png)

When I run the CLI commands manually I get 8 keys - the screenshot above shows 10 keys - not sure why that is the case.

![image](https://cloud.githubusercontent.com/assets/10323889/19161042/474e1f36-8c2d-11e6-9b3d-c7290b8e3b68.png)

Also, the keys that are showing _**not set to rotate!**_ are AWS default master keys that are created when you encrypt a resource without specifying your own CMK. One of those keys does not display from the manual query - the one from _**us-east-1**_

Unfortunately, there doesn't appear to be a way to distinguish a CMK and a default KMS master key. I tried searching using 'Keys[*].KeyArn' but do not see anyway to differentiate between CMK and AWS default keys. 

I also opened a case with AWS and was told that once a default AWS key has been created, there is no way to delete it. :( AWS supposedly rotates default master keys every year but when you do a query for a key the response is False:

![image](https://cloud.githubusercontent.com/assets/10323889/19160929/c7db6b50-8c2c-11e6-9f1d-8e8a4e070a41.png)

**Comment by toniblyx** [comment]
Yep, I have seen there is no way to set rotation for default keys...

**Comment by toniblyx** [comment]
Answering your other question, prowler queries all keys in all regions, this is why you get 10 keys. If you use a single command you will get only keys on your current working region.

**Comment by virtualjj** [comment]
Ah! Okay, got it apologies for that.

As a suggestion, since no way to determine whether default KMS key or not, perhaps update the message to something like:

**WARNING! Key XXXXXXXXX in Region XXXXX is not set to rotate OR Default KMS Key In Use!**

**Comment by toniblyx** [comment]
Ok, added your suggestion in PR #18
