### ISSUE TITLE
Improved JSON output format

### ISSUE THREAD

**Issue by chickenriggies** [prowler-cloud/prowler#190]
I'd like to suggest there be a JSON-only output mode for Prowler reports. In order to forward Prowler warnings to Splunk, we add this to the textWarn() function.

`+    jq -c --arg PROFILE "$PROFILE" --arg ACCOUNT_NUM "$ACCOUNT_NUM" --arg TITLE_TEXT "$TITLE_TEXT" --arg WARNING "$1" --arg TIMESTAMP $(date -u +"%Y-%m-%dT%H:%M:%SZ") -n '{"Profile": $PROFILE, "Account Number": $ACCOUNT_NUM, "Control": $TITLE_TEXT, "Warning": $WARNING, "Timestamp": $TIMESTAMP}' >> "/opt/audit/logs/$PROFILE-prowler.log"`

As you can see, we inject the profile name and a timestamp into each document. Thank you @toniblyx for your excellent work! Let me know what you think.

**Comment by toniblyx** [comment]
Hi @hb3b, that's pretty good idea. I wonder if we can get the same output using `awk` instead of `jq`, to avoid having that as dependency. We can also add a conditional if `-M json` is invoked and `jq` is not installed, show an error and install suggestion. Can you please share the entire `textWarn()` function? Thanks!

**Comment by MrSecure** [comment]
Would it make sense to have separate `json` and `splunk` output formats?   Thought being that `json` would be 1 JSON document with an array of check results, but `splunk` would be one JSON document for each failed check.  The use cases are different enough, it seems.

**Comment by chickenriggies** [comment]
I submitted a separate PR for JSON support: https://github.com/toniblyx/prowler/pull/215/

This PR uses "jq" to ensure JSON is valid. Using printf can be risky if special characters aren't escaped.

**Comment by rheak** [comment]
When Importing the json output into splunk, it would be really handy for each scan have an associated scan id to be able to drill down into specific time ranges and do trending, . As a test, I am using the scan start time variable as the scan id and appending it to the end of the json object in each section of the include/outputs file.

**Something like this:**

_Cut out from outputs file_
```
    --arg TIMESTAMP $(date -u +"%Y-%m-%dT%H:%M:%SZ") \
    --arg SCAN_ID "$SCRIPT_START_TIME" \
    -n '{
      "Profile": $PROFILE,
      "Account Number": $ACCOUNT_NUM,
      "Control": $TITLE_TEXT,
      "Message": $MESSAGE,
      "Status": "Pass",
      "Scored": $SCORED,
      "Level": $ITEM_LEVEL,
      "Control ID": $TITLE_ID,
      "Region": $REPREGION,
      "Timestamp": $TIMESTAMP,
      "ScanID": $SCAN_ID,
```

**Result**
```
….. ,"Timestamp":"2018-08-16T19:13:09Z","ScanID":"2018-08-16T19:12:57+0000"}
``` 

 

 

1. Is there better way to do this?
2. If not, would there be any potential issues with doing it this way? For example will it cause issues for folks that are expecting a json object with a predefined number of elements.
3. If there are known issues,  would be best to have another output, maybe ‘json-splunk’?

**Comment by toniblyx** [comment]
Thanks @rheak, if @hb3b and @MrSecure can't look at it in detail, I would create a new output option for Splunk just in case, to avoid breaking the existing implementation. `json-splunk` sounds good.

**Comment by tomkerswill** [comment]
The ability to output json is great!  At the moment, although the json for each check seems valid, the total json it produces isn't, because each check is output as its own line, with self-contained json, and they are not separated by commas. So it would be hard to just pipe this into a tool (for example, we're hoping to pipe the output into a templating tool).

To fix this, it would be great if the json is presented as an array of check result, with each separated by a comma - something like this:
```
{[
{"Profile":"default","Account Number":"123","Control":"[check11] Avoid the ...","Message":"Root ac","Status":"Info","Scored":"Scored","Level":"Level 1","Control ID":"1.01","Region":"eu-west-1","Timestamp":"2018-10-02T04:50:47Z"},
{"Profile":"default","Account Number":"123","Control":"[check12] Blah ...","Message":"Different check","Status":"Info","Scored":"Scored","Level":"Level 1","Control ID":"1.02","Region":"eu-west-1","Timestamp":"2018-10-02T04:50:47Z"}
]}
```

**Comment by nvisium-john-poulin** [comment]
This is something I've been hoping for, too. Right now I run a script to return valid JSON from the tool.

To be clear, @tomkerswill - what you provided technically isn't valid JSON either. You don't need / can't have the outer brackets (`{}`) in what you provided above. What it should output is below:

```
[
  {"Profile":"default","Account Number":"123","Control":"[check11] Avoid the ...","Message":"Root ac","Status":"Info","Scored":"Scored","Level":"Level 1","Control ID":"1.01","Region":"eu-west-1","Timestamp":"2018-10-02T04:50:47Z"},
  {"Profile":"default","Account Number":"123","Control":"[check12] Blah ...","Message":"Different check","Status":"Info","Scored":"Scored","Level":"Level 1","Control ID":"1.02","Region":"eu-west-1","Timestamp":"2018-10-02T04:50:47Z"}
]
```

**Comment by toniblyx** [comment]
Thanks for the feedback @nvisium-john-poulin and @tomkerswill, I'd be happy to work on this for the final v2.0 planned for BlackHat Europe (or before!). @nvisium-john-poulin can you share that script? I'd like to see if it may help to make the current output a valid single json instead of multiple ones. Thanks

**Comment by nvisium-john-poulin** [comment]
Sure thing. It can probably be improved by someone with more Bash experience, but it's a simple one liner. The gist is, replace newlines with commas and wrap the entire thing in `[]`

`echo '['; tr -s '\r\n' ',' < report.json | rev | cut -c 2- | rev; echo ']';`

**Comment by toniblyx** [comment]
Prowler Json output has been updated and improved over the time and it will be impoved also over the next versions. That includes the Json ASFF one. I'm closing this issue at this point. So far, users are aware of the lack of comma after each finding line and parse that json file accordingly before process it.
