### ISSUE TITLE
Store results in S3 bucket

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [prowler-cloud/prowler#191]
Hi,

Would be good if you could store the results (whatever output format) into an S3 bucket.

**Comment by toniblyx** [comment]
Hi @Phil-ThePower-Pearce, thanks for your suggestion. I think that's pretty easy to achieve using awscli like this:
```
./prowler -M mono  | aws  s3 cp - s3://bucket/prowler-report.txt
```
it wouldn't be bad idea to add a output flag like `-o <s3-location>` when s3-location is something like `s3://bucket/prowler-report-$DATE.txt`

**Comment by toniblyx** [comment]
I have added that command in README.md https://github.com/toniblyx/prowler/commit/eaf0a6bf095025e51264053d18340ae230c2ed3d
