### ISSUE TITLE
Prowler used by commercial entity with license removed

### ISSUE THREAD

**Issue by benvaljean** [prowler-cloud/prowler#195]
FYI a 3rd-party security auditor is using this software without adhering to the license, see the diff here:

https://gist.github.com/benvaljean/16611b5cba76256b9e48517a0bc02638

I have removed references to the company, if you are interested in taking it further I can give more information. I hate it when commercial entities rip-off open source work, especially when this company is very well known in the industry.

**Comment by toniblyx** [comment]
Hi @benvaljean, thanks for letting me know. That's a violation of open source license that comes with Prowler.

Please, if you don't mind, send me more details, contact here https://blyx.com/contacto/

Thanks.
