### ISSUE TITLE
GDPR - Group Number inconsistent

### ISSUE THREAD

**Issue by MrSecure** [prowler-cloud/prowler#206]
The group file for GDPR checks identifies its GROUP_NUMBER as '8.0' rather than '9.0'
https://github.com/toniblyx/prowler/blob/3212b0db551d72f9673d5d6c69ec613a74dd0119/groups/group9_gdpr#L15

**Comment by toniblyx** [comment]
my bad, I'm going to fix it now. I have to add more checks to complete the group, I'll find some time later this week.
Thanks!
