### ISSUE TITLE
Shouldn't check28 skip keys which are in state: PendingDeletion

### ISSUE THREAD

**Issue by nexeck** [prowler-cloud/prowler#209]
Is there any reason why check28 checks all KMS Keys, even those which are in State: PendingDeletion?

**Comment by toniblyx** [comment]
Hi @nexeck, I guess you mean the KeyState attribute right? Allowed values are Enabled, Disabled, PendingImport, or PendingDeletion. I agree with you the query should filter by Enabled only. 

I'm fixing it, I'll submit a PR in a moment. Thanks for reporting it!

**Comment by toniblyx** [comment]
Now it works as expected and doesn't check when a custom KeyState is in a different state than "Enabled"
