### ISSUE TITLE
[Bug]: Issue with scanning multiple AWS Accounts

### ISSUE THREAD

**Issue by Ty-Cloudscaler** [prowler-cloud/prowler#2099]
### Steps to Reproduce

This is in AWS, running Organizations and trying to scan multiple accounts in Parallel.

Following the instructions https://github.com/prowler-cloud/prowler/blob/master/docs/tutorials/aws/multiaccount.md, 

ROLE_TO_ASSUME=<role_name>
PARALLEL_ACCOUNTS="3"
for accountId in $ACCOUNTS_LIST; do
    test "$(jobs | wc -l)" -ge $PARALLEL_ACCOUNTS && wait || true
    {
        prowler aws --role arn:aws:iam::$accountId:role/$ROLE_TO_ASSUME
    } &
done

I am running this on a Mac, not sure if that should make a difference. 

2023-03-16 14:41:55,694 [File: audit_info.py:212] 	[Module: audit_info]	 CRITICAL: RoleArnParsingFailedMissingFields -- The assumed role arn contains a number of fields different than six separated by :, please input a valid arn

### Expected behavior

Prowler running checks on multiple accounts in Parallel, it seems like a good powerful tool but if we cannot scan multiple accounts in parallel it isn't scalable.

### Actual Result with Screenshots or Logs

2023-03-16 14:41:55,694 [File: audit_info.py:212] 	[Module: audit_info]	 CRITICAL: RoleArnParsingFailedMissingFields -- The assumed role arn contains a number of fields different than six separated by :, please input a valid arn

### How did you install Prowler?

From brew (brew install prowler)

### Environment Resource

Local machine

### OS used

MacOS

### Prowler version

Prowler 3.2.4

### Pip version

pip 23.0.1 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)

**Comment by toniblyx** [comment]
Hi @Ty-Cloudscaler,
It looks like the command `prowler aws --role arn:aws:iam::$accountId:role/$ROLE_TO_ASSUME`is not getting the variables properly and thus the ARN is not valid as we can see in the error.
Remember you need to declare `$ACCOUNTS_LIST` with the list of accounts separated by space like in `ACCOUNTS_LIST="111111111 2222222 333333"` I don't see that variable in your code. 
Let us know if that helps.

**Comment by Ty-Cloudscaler** [comment]
Hi @toniblyx, thanks for the quick reply. We have now figured it out, I was in zsh on the MacOS. When I switched to Bash it worked :-)
