### ISSUE TITLE
Extra 7.4 / 7.04 Requires Clarification

### ISSUE THREAD

**Issue by netflash** [prowler-cloud/prowler#210]
Looks like extra 7.04 is confusing. I assumed it would check the SGs which have no ingress filter enabled. 
<img width="397" alt="screenshot 2018-05-01 11 30 50" src="https://user-images.githubusercontent.com/2478391/39487194-3874cb18-4d33-11e8-8277-e1bc2117d446.png">

However this check brings up security groups, which have Ingress set to
```
Allow port 80 from 0.0.0.0/0
Allow port 443 from 0.0.0.0/0
```
This is a pretty simple example of a SG for a public-facing Load Balancer.

I reckon it would be nice to clarify the exact algorithm with examples of legit and non-legit groups for this check.

**Comment by toniblyx** [comment]
Hi @netflash, thanks for your comment.
As per its description `7.4 [extra74] Ensure there are no Security Groups without ingress filtering being used (Not Scored) (Not part of CIS benchmark)`

What that check does is to find SGs with `Name=ip-permission.cidr,Values=0.0.0.0/0`, what means that has any port open to the internet, and then it checks if that SG is being used (attached to a NIC) `--filters Name=group-id,Values=found-sg --query 'length(NetworkInterfaces)'`. You can run `bash -x ./prowler -c extra74` to see the exact commands it executes.

Do you think should be the check title somehow different?

**Comment by toniblyx** [comment]
@netflash feel free to reopen this issue if you have further questions.

**Comment by chizou** [comment]
Can this be updated to include what rules failed? Although the CIS concept is valid, so is having something like port 80 or port 443 open to 0.0.0.0. As it stands, the output of the report requires me to go to each security group and evaluate the rules. It would be much more helpful to tell if the result is a false positive if the actual rules showed up in the report.

**Comment by toniblyx** [comment]
I don't get it @chizou can you please open a new issue with an example? I can create another check for that particular requirement
