### ISSUE TITLE
Check27 not working correctly when using trail name, works when using TrailARN

### ISSUE THREAD

**Issue by adamprice2** [prowler-cloud/prowler#225]
Hi,
I found that check27 was failing for me even though it should have passed.
I changed the code to use the trailARN instead of the trail name and it all works.

Bug could be something weird with my AWS setup, but since I have a 'fix' I thought I would share it.
I don't have a clue how to make github work to submit a change, and I'm not going to try since the change is so trivial.

```
adam@Pam:~/prowler/checks$ diff check27 check27.new
19c19
<   CLOUDTRAILNAME=$($AWSCLI cloudtrail describe-trails --query 'trailList[*].Name' --output text $PROFILE_OPT --region $REGION)
---
>   CLOUDTRAILNAME=$($AWSCLI cloudtrail describe-trails --query 'trailList[*].TrailARN' --output text $PROFILE_OPT --region $REGION)
```

**Comment by toniblyx** [comment]
ok, we I run this command manually:
`/usr/local/bin/aws cloudtrail describe-trails --query 'trailList[*].TrailARN' --output text --profile default --region us-east-1`
I get something like:
`arn:aws:cloudtrail:us-east-1:0123456789:trail/Default`
Then prowler runs:
`/usr/local/bin/aws cloudtrail describe-trails --profile default --region us-east-1 --trail arn:aws:cloudtrail:us-east-1:0123456789:trail/Default --query 'trailList[*].KmsKeyId' --output text`
and I don't get anything because I don't have keys configured in that trail.

using `--query 'trailList[*].Name'` I get the same result, probably TrailARN is less error prone in case of multiple trails, is that your case? can you share an example of your trail names? I would be happy to improve it is that is the case. Thanks in advance!

**Comment by adamprice2** [comment]
Hi Tony,
OK for test purposes I am working in a simple account with a single trail named "CloudTrail1".
I'm working in the eu-west-1 region and I am using a profile other than 'default'.

This was the 'test script' that I used (I tried to keep as many variable names from the 'check' code as possible).
```
#!/bin/bash
export AWS_PROFILE=ProserviaCISAdmin
export AWSCLI=/home/adam/.local/bin/aws
export REGION=eu-west-1
export PROFILE_OPT="--profile ${AWS_PROFILE}"


echo checking with .Name....


export trail=$($AWSCLI cloudtrail describe-trails --query 'trailList[*].Name'      --output text $PROFILE_OPT --region $REGION)

echo \$trail = $trail
echo output = $($AWSCLI cloudtrail describe-trails $PROFILE_OPT --region $REGION --trail $trail --query 'trailList[*].KmsKeyId' --output text  )

echo ==========================================


echo checking with .TrailARN

export trail=$($AWSCLI cloudtrail describe-trails --query 'trailList[*].TrailARN'  --output text $PROFILE_OPT --region $REGION)
echo \$trail = $trail
echo output = $($AWSCLI cloudtrail describe-trails $PROFILE_OPT --region $REGION --trail $trail --query 'trailList[*].KmsKeyId' --output text)

```
The output was as follows

```
checking with .Name....
$trail = CloudTrail1
output =
==========================================
checking with .TrailARN
$trail = arn:aws:cloudtrail:eu-central-1:0123456789:trail/CloudTrail1
output = arn:aws:kms:eu-central-1:0123456789:key/1acd7e5a-1ef4-4b9d-8abb-e26b0a52389f
```

**Comment by toniblyx** [comment]
is it a copy-paste issue or is there a problem with your region? I see `export REGION=eu-west-1` but `eu-central-1` on the results. I'm trying and I can't reproduce, using .Name works fine for me with multiple trails, using your names with and without keys, all my tests are in us-east-1...

**Comment by toniblyx** [comment]
Can you please run the default prowler check this way? `bash -x ./prowler -c check27 -r eu-central-1` and paste the output here (obfuscate data if needed). Thanks!

**Comment by adamprice2** [comment]
For completeness, here is the output if I run without a region specified on the command line
```
 bash -x  ./prowler -c check27  -p ProserviaCISAdmin
```
[FAIL_output.txt](https://github.com/toniblyx/prowler/files/2192555/FAIL_output.txt)

**Comment by toniblyx** [comment]
Ok, I think I know what is going on. Your trail "CloudTrail1" is a global trail right? Being a global trail it is found by `describe-trails --query 'trailList[*].Name'` regardless the region you use to run Prowler. But KMS is not global, it is tight to a region then when you query for the `'trailList[*].KmsKeyId'` in the wrong region it doesn't find the key, that's why it fails for you in eu-west-1 and not in eu-central-1, because your KMS is in eu-central-1. So to fix it the `--query 'trailList[*].KmsKeyId'` command has to be with the region taken from the trail ARN. Am I correct?

**Comment by adamprice2** [comment]
Your summary of my setup is correct, the trail is a global trail.  I'm not sure about your fix but I think so.

This is the full output from describe-trails
```
aws cloudtrail describe-trails  --profile ProserviaCISAdmin
```
```
{
    "trailList": [
        {
            "TrailARN": "arn:aws:cloudtrail:eu-central-1:5XXXXXXXXX9:trail/CloudTrail1",
            "IncludeGlobalServiceEvents": true,
            "S3BucketName": "cis-aws-foundations-prerequisitesf-ctrails3bucket-bn17zlrtehbr",
            "Name": "CloudTrail1",
            "IsMultiRegionTrail": true,
            "HomeRegion": "eu-central-1",
            "HasCustomEventSelectors": true,
            "KmsKeyId": "arn:aws:kms:eu-central-1:5XXXXXXXXX9:key/1XXXXXXX-1ef4-4b9d-8aeb-eXXXXXXXX89f",
            "LogFileValidationEnabled": true
        }
    ]
}
```

**Comment by toniblyx** [comment]
ok, I'll write a fix here later and you can try. Thanks!

**Comment by toniblyx** [comment]
Can you try this piece of code for check27? I think now is more accurate:
```
check27(){
  # "Ensure CloudTrail logs are encrypted at rest using KMS CMKs (Scored)"
  CLOUDTRAILARN=$($AWSCLI cloudtrail describe-trails --query 'trailList[*].TrailARN' --output text $PROFILE_OPT --region $REGION)
    if [[ $CLOUDTRAILARN ]];then
      for trail in $CLOUDTRAILARN;do
        TRAIL_REGION=$(echo $trail|awk -F":" '{ print $4 }')
        TRAIL_NAME=$(echo $trail|awk -F"/" '{ print $2 }')
        CLOUDTRAILENC_ENABLED=$($AWSCLI cloudtrail describe-trails $PROFILE_OPT --region $TRAIL_REGION --trail $TRAIL_NAME --query 'trailList[*].KmsKeyId' --output text)
        if [[ $CLOUDTRAILENC_ENABLED ]];then
          textPass "KMS key found for $TRAIL_NAME"
        else
          textFail "Encryption is not enabled in your CloudTrail trail $TRAIL_NAME (KMS key not found)!"
        fi
      done
    else
      textFail "CloudTrail bucket doesn't exist!"
    fi
}
```

**Comment by adamprice2** [comment]
Hmm I wonder if we can simplify this check, if we just run 
```
 $AWSCLI cloudtrail describe-trails --query 'trailList[].[Name,KmsKeyI]' --output text 
```
and then look for any lines where KmsKey = "None" then we would have the right answer I think.
I've done some quick testing and it seems to work at least with my setup.

**Comment by toniblyx** [comment]
I agree, that's a nicer solution. I'll play around that.

**Comment by adamprice2** [comment]
OK I so this loop could replace check27 I think. 
Should be a bit more efficient because it only calls awscli once.

```

    $AWSCLI cloudtrail describe-trails --query 'trailList[].[Name,KmsKeyId]' --output text | while read trail key ; do
        if [[ "$trail" ]] ; then
            if [[ "$key" != "None" ]] ; then
                textPass "KMS key found for $trail"
            else

                textFail "encryption is not enabled in your CloudTrail trail $trail (KMS key not found)!"
            fi
        else
            textFail "CloudTrail bucket doesn't exist!"
        fi
    done
}
```

**Comment by toniblyx** [comment]
Thanks @adamprice2, I finally managed to fixed it and improved it with your suggestion here https://github.com/toniblyx/prowler/commit/e12f1f6957fa745f8470664f8f9298dd2eb72044
