### ISSUE TITLE
Exception in Check124

### ISSUE THREAD

**Issue by arkadiyt** [prowler-cloud/prowler#226]
Hi,

Thanks for the great project - I was testing it out one some accounts I have and ran into the following exception:
```
1.24 [check124] Ensure IAM policies that allow full "*:*" administrative privileges are not created (Scored)

In function contains(), invalid type for value: None, expected one of: ['array', 'string'], received: "null"

In function contains(), invalid type for value: None, expected one of: ['array', 'string'], received: "null"
```

**Comment by toniblyx** [comment]
Thanks @arkadiyt, I can't reproduce that issue, can you please run that check like this `bash -x ./prowler -c check124` and share here its output? (obfuscate account id, etc.)

**Comment by arkadiyt** [comment]
```
+ for policy in '$LIST_CUSTOM_POLICIES'
++ /usr/local/bin/aws iam list-policies --profile zzzzzzzzzzz --region us-west-2 --query 'Policies[*].[Arn,DefaultVersionId]' --output text
++ awk '$1 == "arn:aws:iam::zzzzzzzzzzzz:policy/zzzzzzzzzzzzzz" { print $2 }'
+ POLICY_VERSION=v5
++ /usr/local/bin/aws iam get-policy-version --output text --policy-arn arn:aws:iam::zzzzzzzzzzzz:policy/zzzzzzzzzzzzzz --version-id v5 --query 'PolicyVersion.Document.Statement[?Effect == '\''Allow'\'' && contains(Resource, '\''*'\'') && contains (Action, '\''*'\'')]' --profile zzzzzzzzzzz --region us-west-2

In function contains(), invalid type for value: None, expected one of: ['array', 'string'], received: "null"
```

**Comment by toniblyx** [comment]
Hi @arkadiyt, I'm trying to reproduce your issue but I can't. It seems to be something related to your policy, can you share it?

Just to make sure, the error is right after `/usr/local/bin/aws iam get-policy-version --output text --policy-arn arn:aws:iam::zzzzzzzzzzzz:policy/zzzzzzzzzzzzzz --version-id v5 --query 'PolicyVersion.Document.Statement[?Effect == '\''Allow'\'' && contains(Resource, '\''*'\'') && contains (Action, '\''*'\'')]' --profile zzzzzzzzzzz --region us-west-2` command right?

**Comment by arkadiyt** [comment]
Yup that's the line that errors out. Here's the policy:
```
$ /usr/local/bin/aws iam get-policy-version --output text --policy-arn arn:aws:iam::zzzzzzzzzzzz:policy/zzzzzzzzzzzzz --version-id v5  --profile zzzzzzzzzz --region us-west-2
POLICYVERSION	2018-06-14T20:51:20Z	True	v5
DOCUMENT	2012-10-17
STATEMENT	ssm:GetParametersByPath	Allow		arn:aws:ssm:us-west-2:zzzzzzzzzzzz:parameter/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz/*
STATEMENT	kms:Decrypt	Allow		arn:aws:kms:us-west-2:zzzzzzzzzzzz:key/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
STATEMENT		Allow	*	*	Noop
STATEMENT	ssm:GetParametersByPath	Allow		arn:aws:ssm:us-west-2:zzzzzzzzzzzz:parameter/zzzzzzzzzzzzzzzzzzzzzzzz/*
STATEMENT	kms:Decrypt	Allow		arn:aws:kms:us-west-2:zzzzzzzzzzzz:key/zzzzzzzzzzzzzzzzzzzzzzzz
STATEMENT	ssm:GetParametersByPath	Allow		arn:aws:ssm:us-west-2:zzzzzzzzzzzz:parameter/zzzzzzzzzzzzzzzzzzzzzzzz/*
STATEMENT	kms:Decrypt	Allow		arn:aws:kms:us-west-2:zzzzzzzzzzzz:key/zzzzzzzzzzzzzzzzzzzzzzzz
STATEMENT	ssm:DescribeParameters	Allow		*
STATEMENT	ssm:GetParameters	Allow		arn:aws:ssm:*:*:parameter/zzzzzzzzzzzzzzzzzzzzzzzz*
STATEMENT	ssm:GetParametersByPath	Allow		arn:aws:ssm:us-west-2:zzzzzzzzzzzz:parameter/zzzzzzzzzzzzzzzzzzzzzzzz/*
STATEMENT	kms:Decrypt	Allow		arn:aws:kms:us-west-2:zzzzzzzzzzzz:key/zzzzzzzzzzzzzzzzzzzzzzzz
```

**Comment by toniblyx** [comment]
Sorry, I still can't reproduce it :( for some reason your policy fails with this query `--query 'PolicyVersion.Document.Statement[?Effect == '\''Allow'\'' && contains(Resource, '\''*'\'') && contains (Action, '\''*'\'')]'` can you try with different queries or changing the line https://github.com/toniblyx/prowler/blob/master/checks/check124#L24 ? And see if you get a different behavior?

**Comment by toniblyx** [comment]
Hi @arkadiyt sorry for the delay, I'm testing it now much better and I see that the exception is caused by the function contains at `contains(Action, '\''*'\'')`, expects a string and gets a `null` since there is not `Action` but `NotAction`.

The way to fix it is using this query `--query "PolicyVersion.Document.Statement[?Action!=`null`]|[?Effect == 'Allow' && contains(Resource, '*') && contains (Action, '*')]"` 

Now I'm figuring out how to add it to the check124 with the right syntax

**Comment by toniblyx** [comment]
the right syntax is with `\`` around null

**Comment by toniblyx** [comment]
Done :)

**Comment by arkadiyt** [comment]
Thanks!
