### ISSUE TITLE
Add HIPAA compliance checks

### ISSUE THREAD

**Issue by hhh0505** [prowler-cloud/prowler#227]
any plan to add this?

**Comment by toniblyx** [comment]
Hi @hhh0505, do you have a sample set of checks that might be suitable for HIPPA compliance in AWS? Some might be part of the existing checks and probably some new check points.

**Comment by crashGoBoom** [comment]
Adding HIPAA checks is no small task and I don't believe checks for _full_ compliance will be possible as it depends much upon how each user/application handles PHI. But a good start would be checking for encryption at rest and in transit for the major services.

That being said, here is a quick place holder of needed/desired HIPAA checks. I will try to update this periodically. @toniblyx This is just a start but...feel free to shoot all this down if it starts adding too many checks 😄 

## Account Security
- [x] MFA Enabled - `check12, check113`
- [x] Account Root User Credentials Protection `check112, check113`

## VPC Security 
- [x] VPC Flow Logging Used - `check29`
- [ ] VPC Flow Logs are Encrypted - Needs check
- [x] Enable ELB Logging - Needs check `extra739`

## EC2 Security
- [x] Encrypted EBS Volumes - `extra729`
- [x] Encrypted EBS Snapshots - `extra740`
- [x] _Ensure EC2 Instances are launched in a VPC_ - (No longer need, only for pretty old accounts)

## S3 Security
- [x] Bucket Policy, Enforce Encryption and Filter by source-ip. - `extra734`
- [x] IAM Roles, Enforce permissions  - `check38`, `extra73`
- [x] Monitoring, Access Logs - `check23 , check26 , check27, extra718, extra725`

## RDS Security
- [x] Encrypted RDS - `extra735`

**Comment by toniblyx** [comment]
I'll update this list with new checks soon. Most of the checks I'm writing for GDPR are valid for HIPPA.

**Comment by toniblyx** [comment]
This is already finished in `devel` branch. I'll merge it to master soon.
