### ISSUE TITLE
Change 3.15 and 1.15 from outputting Scored Value of 'Scored'

### ISSUE THREAD

**Issue by rheak** [prowler-cloud/prowler#230]
When I run prowler and export to json, I get a Scored value of 'Scored' instead of 'Not Scored' for 1.15 and 3.15. In their Title/Description it correctly says (Not Scored), but the outputted value needs to be updated. Thanks!

**Comment by toniblyx** [comment]
Yes, this makes sense, my bad when I created the check files. Thanks you!
