### ISSUE TITLE
Check31 unclosed delimiter - metric name causing an issue?

### ISSUE THREAD

**Issue by Pl4nky** [prowler-cloud/prowler#236]
Getting the following from check31

3.1  [check31] Ensure a log metric filter and alarm exist for unauthorized API calls (Scored)``
Bad value for --query MetricAlarms[?MetricName==`ABC123: Bad jmespath expression: Unclosed delimiter:

MetricAlarms[?MetricName==`ABC123

^ points at the backtick 

The metric names used in our accounts look like "ABC123 - CIS Monitoring - 3.01 Unauthorized API Calls".   Is the spaces causing an issue with this check? or something else?

**Comment by toniblyx** [comment]
Thanks @Pl4nky, alarm names can be really random and it is hard to figure out how they are going to be and write a proper regexp for it. You can try to write a custom check or modify the existing to accept your own naming policy: `'MetricAlarms[?MetricName==`'$metric_name'`]' `.

In any case, I can try to reproduce your error and find a way to make it work, would you mind to run this command and share the output here? (fake or obfuscate account ID or any other detail if needed)
`bash -x ./prowler -c check31`
Thanks

**Comment by Pl4nky** [comment]
Not a problem @toniblyx. I've been using virtualjj's cloudformation template to deploy the metric monitoring/alarms and just went with the defaults (https://github.com/virtualjj/cis-aws-benchmark-section-3-monitoring-remediate).   Its no drama to re-deploy with different names. 

[output.txt](https://github.com/toniblyx/prowler/files/2304801/output.txt)

**Comment by Pl4nky** [comment]
Strange, as there is no quotes visible in the console, nor when I run `aws cloudwatch describe-alarms` manually

The CF template doesn't have quotes in default value at all

`  32MgmtConsoleNoMFA:`
`    Description: 3.02 Ensure a log metric filter and alarm exist for Management Console sign-in without MFA (Scored)`
`    Type: String`
`    Default: CIS Benchmark v.1.1 - 3.02 Management Console Sign-in Without MFA`
`    MinLength: '1'`
`    MaxLength: '255'`
`    AllowedPattern: "[\\w\\s-_/.]+"`
`    ConstraintDescription: "Metric names can contain up to 255 alphanumeric characters, with the following also allowed: -_./"`

Yea, pretty happy with his templates, makes deployment of those benchmarks so much simpler. 

I'll redeploy the template with different names and see how I go.

**Comment by Pl4nky** [comment]
I took the spaces out of the names and now running check31 comes back successfully.
