### ISSUE TITLE
check13 - date: invalid date ‘+%s’

### ISSUE THREAD

**Issue by Pl4nky** [prowler-cloud/prowler#237]
When running check13, I get the following error:

 `1.3  [check13] Ensure credentials unused for 90 days or greater are disabled (Scored)`
`date: invalid date ‘+%s’`
`./include/os_detector: line 25: (1534773600 -  )/60/60/24: syntax error: operand expected (error token is ")/60/60/24")`
`./checks/check13: line 25: [: -gt: unary operator expected`

I modifed os_detector, line 24 from 

 `DATE_FROM_IN_DAYS=$(date -d $DATE_TO_COMPARE +%s)`

to

 `DATE_FROM_IN_DAYS=$(date -d "$DATE_TO_COMPARE" +%s)`

Which seemed to eliminate the error. Not sure of the impact, so FYI!

**Comment by toniblyx** [comment]
What OS are you using to run Prowler?

**Comment by Pl4nky** [comment]
AWS Linux, but moved to an ubuntu instance and no modifications needed.
