### ISSUE TITLE
Check32 - no alarms associated

### ISSUE THREAD

**Issue by Pl4nky** [prowler-cloud/prowler#238]
I'm trying to work out why my alarms are not being found by prowler.   

Using Check32 as an example, it has the following code

` HAS_ALARM_ASSOCIATED=$($AWSCLI cloudwatch describe-alarms $PROFILE_OPT --region $CLOUDWATCH_LOGGROUP_REGION --query 'MetricAlarms[].MetricName' --output text | awk 'BEGIN {IGNORECASE=1}; /ConsoleLogin/ || /MFAUsed/;')`

As far as I can tell (Im not familiar with bash scripts), this will always fail as it just lists all alarms metric names, using AWK to look for ConsoleLogin and MFAUsed which wont be found. 

I see in check31, the code for ascertaining the alarm is rather different (and works when I run it).

I've attached the output of bash -x ./prowler -c check32. Let me know if there is anything else I can do. 

[debug.txt](https://github.com/toniblyx/prowler/files/2308646/debug.txt)

**Comment by Pl4nky** [comment]
I copied the code from check31 (updating the values being looked for - consolelogin and mfaused) and it now works successfully. 

Looking at the other check3* scripts they have the same issue detailed above.

**Comment by toniblyx** [comment]
All those checks are pretty specific and in most cases have to be customized to detect a right alarm. You did well making your own by changing the existing ones. I hope they re-think that part in the CIS benchmark.
