### ISSUE TITLE
Improve Prowler speed

### ISSUE THREAD

**Issue by andresriancho** [prowler-cloud/prowler#246]
prowler was running for 4h yesterday to complete the whole process. This is for a huge AWS organization with 2k EC2, 2k users, 1k roles, etc. but still 4h is too much!

Scout2 took 45min to assess the security of the same organization.

Maybe consider using threads?

**Comment by toniblyx** [comment]
Yes, it may take long time for some checks in large accounts. I played a bit with threads here https://github.com/toniblyx/prowler/blob/master/checks/check_extra73#L60 but it is something to be implemented across checks.

**Comment by toniblyx** [comment]
This is being also discussed in #299 and #267 so I'll close this ticket as redundant. Thanks @andresriancho !
