### ISSUE TITLE
List checks is not listing the checks

### ISSUE THREAD

**Issue by UranusBytes** [prowler-cloud/prowler#255]
It doesn't listing the checks, but starting the checks.   Need to move the if statement for `PRINTCHECKSONLY` up in the main execution.

With that fixed, it was only displaying the first check due to syntax bug in the `show_all_titles` function.

**Comment by toniblyx** [comment]
looking at your PR, I think it must be a matter of permissions, can you please let me know what are the polices attached you this role? `arn:aws:sts::123412341234:assumed-role/myRoleNamexxxx/i-0000aaaabbbbccccd` I mean, the role you are running Prowler (instance profile, actually). Thanks!

**Comment by toniblyx** [comment]
I see an error in your report `An error occurred (UnauthorizedOperation) when calling the DescribeRegions operation: You are not authorized to perform this operation` and it doesn't run any report, it just try to generate the credentials report without success. So it seems to be related to permissions. Make sure you have this policy attached to the instance from where you are running Prowler: https://github.com/toniblyx/prowler#custom-iam-policy

**Comment by UranusBytes** [comment]
Hi Toni,

You are correct in that the output from the logs in the pull request are showing access errors for DescribeRegions and GenerateCredentialReport, but I'm not clearly communicating why I think these errors shouldn't occur, even if permissions are insufficient.  Why should AWS permissions be needed to list all regions and generate credential reports if the only action being done is to list all the checks and then exit the script???  It's unnecessary actions.

Ignoring the permissions, the other issue that the pull request addressed is that it will only list the first check of each category.

In the `execute_groups()` the for-loop is correctly using the CHECKS as an array.

https://github.com/toniblyx/prowler/blob/fe6eae7d309fdbdca95942add3b2f3ec5a2a9325/prowler#L218-L221

But in the `show_all_titles()` the for-loop is not using the CHECKS as an array

https://github.com/toniblyx/prowler/blob/fe6eae7d309fdbdca95942add3b2f3ec5a2a9325/prowler#L251-L254

Jeremy

**Comment by toniblyx** [comment]
Ah ok ok, I'm now understanding your point @UranusBytes, sorry about that. It makes a lot of sense. If you just want to see the list, it doesn't make any sense to look at regions, etc. 
I'll work on it to fix it.

**Comment by toniblyx** [comment]
I have applied your PR #256 , thanks @UranusBytes !
