### ISSUE TITLE
extra720 "Lambda function NOT enabled in trail" / Support for "arn:aws:lambda" selector

### ISSUE THREAD

**Issue by acceptableEngineering** [prowler-cloud/prowler#258]
### Symptom
Prowler will report a Lambda function as not being monitored by a CloudTrail trail if you are using the CloudTrail event selector `arn:aws:lambda` which tells the trail to monitor all Lambdas. I believe this to be a bug and proposed that Prowler look for this selector and treat it as a passing criteria:
```FAIL! us-east-1: Lambda function test_lambda NOT enabled in trail test_trail```

However, this selector is valid according to: https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_DataResource.html
> To log data events for all functions in your AWS account, specify the prefix as arn:aws:lambda.

----

### Under the hood
You can examine the payload returned by the AWS CLI SDK, then read further to see why Prowler is reaching this conclusion:

#### AWS CLI SDK
```
$ aws cloudtrail get-event-selectors --trail-name test_trail --profile test
```
```
{
    "EventSelectors": [
        {
            "IncludeManagementEvents": true,
            "DataResources": [
                {
                    "Values": [
                        "arn:aws:lambda"
                    ],
                    "Type": "AWS::Lambda::Function"
                }
            ],
            "ReadWriteType": "All"
        }
    ],
    "TrailARN": "arn:aws:cloudtrail:us-east-1:AWS_ACCOUNT_NUMB:trail/test_trail"
}
```

### Prowler
[This logic](https://github.com/toniblyx/prowler/blob/master/checks/check_extra720#L28) inside the loop is seeking a value matching the Lambda function's ARN:
```
FUNCTION_ENABLED_IN_TRAIL=$($AWSCLI cloudtrail get-event-selectors $PROFILE_OPT --trail-name $trail --region $regx --query "EventSelectors[*].DataResources[?Type == \`AWS::Lambda::Function\`].Values" --output text |xargs -n1| grep -E "^arn:aws:lambda.*function:$lambdafunction$")
if [[ $FUNCTION_ENABLED_IN_TRAIL ]]; then
    textPass "$regx: Lambda function $lambdafunction enabled in trail $trail" "$regx"
else
    textFail "$regx: Lambda function $lambdafunction NOT enabled in trail $trail" "$regx"
fi
```

----

**Comment by toniblyx** [comment]
Hi @acceptableEngineering, I have been doing some tests and I don't see where is the issue or I missed something in your issue.

This is the command and output to list event selectors on a Trail without any enabled:

```
aws cloudtrail get-event-selectors --profile default --trail-name Default --region us-east-1
{
    "EventSelectors": [
        {
            "IncludeManagementEvents": true,
            "DataResources": [],
            "ReadWriteType": "All"
        }
    ],
    "TrailARN": "arn:aws:cloudtrail:us-east-1:XXXXXXX:trail/Default"
```

Now, this is the output with just one lambda function selected:

```
aws cloudtrail get-event-selectors --profile default --trail-name Default --region us-east-1
{
    "EventSelectors": [
        {
            "IncludeManagementEvents": true,
            "DataResources": [
                {
                    "Values": [
                        "arn:aws:lambda:us-east-1:XXXXXXX:trail:function:demo-lambda-1PQYQH2QP2TX1"
                    ],
                    "Type": "AWS::Lambda::Function"
                }
            ],
            "ReadWriteType": "All"
        }
    ],
    "TrailARN": "arn:aws:cloudtrail:us-east-1:XXXXXXX:trail:trail/Default"
}
```
Running `/usr/local/bin/aws cloudtrail get-event-selectors --profile default --trail-name Default --region us-east-1 --query 'EventSelectors[*].DataResources[?Type == `AWS::Lambda::Function`].Values' --output text` we get the lambda function being logged:
`arn:aws:lambda:us-east-1:XXXXXXX:trail:trail:function:demo-lambda-1PQYQH2QP2TX1` 
And that's the way I get which lambda function is enabled in a Trail. It works fine in my tests, can you give me more information about your trails, regions, etc? I can try to reproduce it.

**Comment by acceptableEngineering** [comment]
Hi @toniblyx, thank you so much for your response, and your contributions to the open source community!

It's possible I'm something here, so please feel free to correct me. I understand that the event selector `arn:aws:lambda` acts as a wildcard, catching all Lambda events, and that the comparison operator linked in my original message doesn't expect nor handle that scenario.

**Comment by toniblyx** [comment]
The challenge here is that you have to get all the lambdas logged per Trail (since each trail can log same lambdas, or even global trails can also have all lambdas enabled), it is a bit a mess from the AWS stand point in order to do a proper check. You can run prowler this way and you can see all the commands and the sequence of them to see some logic and understand it: `bash -x ./prowler -c extra720 -p test` 
Let me know if you need anything else.

**Comment by toniblyx** [comment]
Hi @acceptableEngineering please feel free to reopen this issue if you need further information or you find that still a bug on this.
