### ISSUE TITLE
False Negative For check31

### ISSUE THREAD

**Issue by virtualjj** [prowler-cloud/prowler#26]
Even though I have this metric filter configured I get the message stating that no filters or alarms are associated.

![image](https://cloud.githubusercontent.com/assets/10323889/19340783/8e0d7894-9165-11e6-823d-108037bbb05a.png)

The problem is at https://github.com/Alfresco/aws-cis-security-benchmark/blob/master/prowler#L606 since the --query argument must extract data from **metricFilters**.

![image](https://cloud.githubusercontent.com/assets/10323889/19340851/e5027dfc-9165-11e6-92e9-02f7da9c7e5c.png)

Changing to --query 'metricFilters' appears to fix the problem.

![image](https://cloud.githubusercontent.com/assets/10323889/19341047/ce85dcda-9166-11e6-9802-37f9d3a89256.png)

**Comment by toniblyx** [comment]
Thanks @virtualjj working through checks 3.x now, I'll keep you posted

**Comment by virtualjj** [comment]
Cool - I'm slowing going through each control but I'm finding issues with the actual CIS recommendations. For example this filter will actually return a bunch of hits from the following AWS services:

kms.amazonaws.com
elasticloadbalancing.amazonaws.com
s3.amazonaws.com
acm.amazonaws.com
cloudtrail.amazonaws.com
cloudtrail.amazonaws.com
rds.amazonaws.com
logs.amazonaws.com
acm.amazonaws.com
ec2.amazonaws.com
iam.amazonaws.com

Especially **_kms.amazonaws.com_** if control 2.7 (Encrypted CloudTrail Logs) is enabled.

I think this metric filter below is actually better to reduce false positives but I have opened a support case with AWS to confirm:

`{ $.userIdentity.sessionContext.attributes.mfaAuthenticated != "true" && $.eventSource != *.amazonaws.com }`

**UPDATE:** AWS has acknowledged this issue (Case 1909332871) and will contact their teams to review the CIS white paper. This filter pattern has been suggested instead:

`{ ($.additionalEventData.MFAUsed = "No") && ($.eventName = "ConsoleLogin") }`

**Comment by toniblyx** [comment]
Thanks @virtualjj. Are you using something to implement all these changes? I mean, commands or a CFN template? I have found a template here that may create some alarms but it is not fully covering all CIS 3.X checks. https://s3-us-west-2.amazonaws.com/awscloudtrail/cloudwatch-alarms-for-cloudtrail-api-activity/CloudWatch_Alarms_for_CloudTrail_API_Activity.json

**Comment by virtualjj** [comment]
Awesome - thanks for this. I'm actually doing the changes with my own scripts but once I have everything cleaned up, planning on sharing my templates on GitHub.

**Comment by toniblyx** [comment]
That would be great. I'm also thinking to make public content here or write an blog post about how to fix all these WARNINGS with real commands or assets since what it comes in the CIS document is very vague. If you are interested let me know and we can put them toguether. I will keep you posted about my work on that template in the next days.

**Comment by virtualjj** [comment]
Sounds great - just followed you on Twitter. Not sure how quick I can contribute but will throw ideas your way in the meantime! Will close this issue - thanks again!
