### ISSUE TITLE
Prowler work from External Server 

### ISSUE THREAD

**Issue by Cybernewbies** [prowler-cloud/prowler#264]
I would like to know , how we can set an custom profile for doing an external audit on AWS cloud environment using internal DC in which Centos is used as base OS for setup prowler and doing the assessment in it. I also followed the below procedure:

1. Prowler setup
2. AWS configure is installed
3. pre-requisites are installed.

I need to know the use of customized profile in this case. I would like to how to set it up in Centos Machine not from EC2 instance?

How to check the connectivity is established here in correct manner with AWS? Any Suggestions

**Comment by toniblyx** [comment]
Hi @Cybernewbies, Prowler rely on the aws-cli so if you have it installed and working in either an EC2 instance or a remote computer you need the proper permission configured in your AWS profile, you have all steps needed here https://github.com/toniblyx/prowler#requirements-and-installation. If you are able to run aws-cli commands from your centos using its own aws configuration, you just have to make sure that its profile has the enough permissions to run all the checks.

**Comment by Cybernewbies** [comment]
Thanks Toniblyx

I would like to inform that i have installed the tool in Centos and access the AWS via API using putty with profile is a Security Audit role in which all the permission as per procedure , But while doing the Steps 4 in usage and saving in it as .html , but i am not able to see it further in html even though during the AWS configure:

AWS Access Key ID [None]: AKIAIOSFODNN7EXAMPLE
AWS Secret Access Key [None]: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
Default region name [None]: us-west-2
Default output format [html
![aws html issues](https://user-images.githubusercontent.com/36504310/47567422-1f429800-d94c-11e8-876e-f1934182c793.GIF)
]: .html 

I would like to know whether html format are supported further on Output Format in Prowler or not. Can you tell the issue in this case.

**Comment by Cybernewbies** [comment]
Sorry for closing the Issues

**Comment by toniblyx** [comment]
What command are you running to get that error? 

First of all you have to make sure your aws-cli is working properly, for example, make sure this command gives you a proper output: `aws sts get-caller-identity` or `aws sts get-caller-identity --profile yourprofile`. If you get output without errors, keep reading, otherwise fix you aws-cli first.

If you want to save your report as html you have to install first `ansi2html` with this command as mentioned in the README `pip install ansi2html` then you can run Prowler like `./prowler | ansi2html -la > report.html`

**Comment by Cybernewbies** [comment]
Even i have tried to use the same command as ./prowler | ansi2html -la > cyberprod_report.html. Then it seems that we are getting an unknown output.

Unknown output type: html
Unknown output type: html

**Comment by toniblyx** [comment]
I think that's an error from ansi2html, not from Prowler, can you make sure ansi2html works fine? https://github.com/ralphbean/ansi2html

**Comment by toniblyx** [comment]
Please feel free to reopen this issue if you have more questions.
