### ISSUE TITLE
Missing credentials dependency

### ISSUE THREAD

**Issue by museadmin** [prowler-cloud/prowler#272]
I have been running Prowler under Cloud Security Suite and I see this error message repeatedly:

`An error occurred (ReportNotPresent) when calling the GetCredentialReport operation: Unknown`

On investigation, this was because the credentials report it was requesting was expired. To fix this I had to explicitly call

`bradley.atkins $ aws iam generate-credential-report
{
    "State": "STARTED",
    "Description": "No report exists. Starting a new report generation task"
}

bradley.atkins $ aws iam generate-credential-report
{
    "State": "COMPLETE"
}`

Then Prowler ran without error because a report was present to request.

Can you add a call to this endpoint and loop until it returns COMPLETE?

thanks

**Comment by toniblyx** [comment]
What version of Prowler are you using? As far as I know Cloud Security Suite uses an old version and probably doesn't handle that properly. Thanks for asking!

**Comment by museadmin** [comment]
Thanks Tony,

Yes I see on stdout that your latest version does get the credentials.

Cheers

Brad
