### ISSUE TITLE
Feature Request: Better check selection and exclusion granularity

### ISSUE THREAD

**Issue by jcmcken** [prowler-cloud/prowler#273]
Two related features would make working with this tool much simpler and faster:

* The ability to specify multiple ``-c`` at the command line to select specific checks.
* The ability to run all checks except for a few exclusions. This could be implemented as another CLI option, e.g. ``-E``. This option should also work in "append" mode (ability to specify multiple checks to exclude).

Until multi-threading/processing support is added, this would give users a way to manually shard the checks into multiple jobs to speed up the scanning process. For example, known long-running checks can be sharded into their own separate jobs, and fast-running checks can be combined together into a single job.

Since everything is shell, it may be easier to implement the multiple options as a comma-separated list rather than allowing duplicate invocations of an option e.g.:

```console
./prowler -c check113,check112
```

...instead of...

```console
./prowler -c check113 -c check112
```

**Comment by toniblyx** [comment]
Thanks for your suggestions.  I'll have them in mind them for next features. In the meantime, remember that you can create your custom group with any check that you want and run it like `prowler -g my-group`. Thanks!

**Comment by toniblyx** [comment]
the ability to run `./prowler -c check113,check112` has been implemented thanks to a PR from @SDugo and it is already available in the master branch.
