### ISSUE TITLE
Check 2.9 failure even if no VPCs exist in the region

### ISSUE THREAD

**Issue by affanhmalik** [prowler-cloud/prowler#274]
CIS section 2.9 requires VPC flowlogs to be enabled for all VPCs. However, prowler implementation only looks for flowlogs in each region (doesn't account for the possibility that there are no VPCs in the region).

To reproduce:

1. In AWS Console, go to VPC
2. Change region to an unused region, delete the default VPC (and any other existing VPCs)
3. Run check29, the status of this particular region will be FAIL

**Comment by toniblyx** [comment]
Hi @affanhmalik, this check is actually correct, there are no flowlogs because also there are no VPCs in a given region. Do you think it should be INFO instead? Stating something like: `INFO! ap-south-1: No VPCs found`
