### ISSUE TITLE
Check 13 should examine users in more depth

### ISSUE THREAD

**Issue by jcmcken** [prowler-cloud/prowler#275]
To recap, check 13 is:

```
[check13] Ensure credentials unused for 90 days or greater are disabled (Scored)
```

Right now in my account, I have an IAM user with no active IAM credentials and no console access, so the user is effectively disabled and unusable. But Prowler flags this user as failing check 13

Currently, check 13 just checks ``PasswordLastUsed`` on the user to determine if the user is inactive and should be disabled. 

Ideally, it could use the following heuristic:

* Find all users who are deemed inactive (using ``PasswordLastUsed``)
* If an inactive user has console access (username/password) or an active IAM key, fail the check.
* If the user has no console access and no active IAM keys, the user is considered disabled, and the check passes.

**Comment by toniblyx** [comment]
You are right, CIS guide only advises about `PasswordLastUsed` but it can be better checked as you mention. I'll improve it as soon as I can. Thanks!

**Comment by toniblyx** [comment]
Hi @jcmcken I'm reviewing this issue and it is actually fine when it comes to users with console access, this check actually only checks for users with console access, see https://github.com/toniblyx/prowler/blob/master/checks/check13#L19 

I'm going to close the issue. If you consider that it worth it to have another helpful check, please feel free to let me know with your requirements. Thanks!
