### ISSUE TITLE
Check 120 incorrectly can not fail

### ISSUE THREAD

**Issue by tmonk42** [prowler-cloud/prowler#277]
The CIS v1.2 standard control 1.20 says "Check if the 'AWSSupportAccess' is attached to any IAM user, group or role"

Note that when the check command is run and a policy is not attached to anything, it returns empty lists for PolicyGroups, PolicyUsers, and PolicyRoles:

```
aws iam list-entities-for-policy --region us-east-1 --profile FOO --policy-arn "arn:aws:iam::aws:policy/AWSSupportAccess" --output json
{
    "PolicyGroups": [],
    "PolicyUsers": [],
    "PolicyRoles": []
}
```

https://github.com/toniblyx/prowler/blob/master/checks/check120#L23

When the policy is not attached, $POLICYUSERS will contain the hash with the empty arrays, and therefore "pass". It is not possible for this check to fail. Note that if it is not attached, output will be as follows:
```
 1.20  [check120] Ensure a support role has been created to manage incidents with AWS Support (Scored)
       PASS! Support Policy attached to arn:aws:iam::aws:policy/AWSSupportAccess
```
This check should look for values for any one of an IAM user, group, or role, display which it's attached to when found, and fail if none of them are true.

Also, currently L24 says 'textPass "Support Policy attached to $policyarn"' when this is just displaying the ARN of the support policy regardless of its attachment status.

**Comment by toniblyx** [comment]
It looks like Amazon has changed something here, probably is the output  of `aws iam list-entities-for-policy`, now `$POLICYUSERS` gets a value (wrong one). I have to rewrite that check accordingly to parse PolicyRoles.

**Comment by toniblyx** [comment]
can you try with this code? It may make the trick for roles:
```
check120(){
  # "Ensure a support role has been created to manage incidents with AWS Support (Scored)"
  SUPPORTPOLICYARN=$($AWSCLI iam list-policies --query "Policies[?PolicyName == 'AWSSupportAccess'].Arn" $PROFILE_OPT --region $REGION --output text)
  if [[ $SUPPORTPOLICYARN ]];then
    for policyarn in $SUPPORTPOLICYARN;do
      POLICYROLES=$($AWSCLI iam list-entities-for-policy --policy-arn $SUPPORTPOLICYARN $PROFILE_OPT --region $REGION --query PolicyRoles[*] --output text)
      if [[ $POLICYROLES ]];then
        for role in $POLICYROLES; do
          textPass "Support Policy attached to $role role"
        done 
        # for user in $(echo "$POLICYUSERS" | grep UserName | cut -d'"' -f4) ; do
        #   textInfo "User $user has support access via $policyarn"
        # done
      else
        textFail "Support Policy not applied to any Group / User / Role "
      fi
    done
  else
    textFail "No Support Policy found"
  fi
}
```

**Comment by tmonk42** [comment]
Yup! That looks like it works for the case where the support policy is attached to a role. Probably want to update the textFail to remove mention for group/user, or update the check to look at those as well.

**Comment by toniblyx** [comment]
Thanks, it is fixed in the next merge from Devel.
