### ISSUE TITLE
Unable to use -p flag and create HTML report

### ISSUE THREAD

**Issue by tashjnorris** [prowler-cloud/prowler#280]
Unable to use the export results to html and the -p (profile) flag at the same time. Perhaps I'm crafting the command wrong? anyone seen this? 

tried:

`./prowler | ansi2html -la > report.html -p GS`

An error occurred (AuthFailure) when calling the DescribeRegions operation: AWS was not able to validate the provided access credentials

and

`./prowler -p GS | ansi2html -la > report.html`

An error occurred (AccessDenied) when calling the GetBucketAcl operation: Access Denied

**Comment by toniblyx** [comment]
Hi @tashnorrispbx, the right way to run your command is like your second command `./prowler -p GS | ansi2html -la > report.html`. What is going on apparently is permission problem. Prowler doesn't have enough permissions (profile GS) to run `s3:GetBucketAcl` operation.  Make sure you have a custom policy like this one https://github.com/toniblyx/prowler#custom-iam-policy associated to your GS profile.

**Comment by toniblyx** [comment]
If the advise didn't work, please feel free to re-open this issue.

**Comment by mindfulmonk** [comment]
I would want to reopen this as I'm currently writing a workaround to this issue. It is quite common to lock down S3 buckets for example for terraform state files as they are quite sensitive. 

Now I see there are two ways to go about it:

1. Create a policy that would allow to view those buckets. 
2. Write a script that removes the "Access Denied" lines from the output.

It would be great if instead there was a flag --ignore-errors or similar to prevent prowler from generating an invalid html/json file.

**Comment by toniblyx** [comment]
hi @mindfulmonk, sorry but I don't get your error. Is the html not created correctly due to a wrongly handled error from the aws-cli output? In that case, can  you please open a new issue highlighting the check that is failing? Thanks!

**Comment by ob1xxx** [comment]
I've added the policy you suggested and still receive permission errors? Was this truly corrected?

**Comment by toniblyx** [comment]
Hi @ob1xxx, can you please share the error and the check number where you find issues?
