### ISSUE TITLE
ansi2html doesn't work with Prowler

### ISSUE THREAD

**Issue by ms0x08-dev** [prowler-cloud/prowler#285]
Unable to use the export results to html. 
Command: 
./prowler -p Acc -r eu-west-1 | ansi2html -la > report.html
The process just hangs and nothing happens.
System: Linux 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux

**Comment by toniblyx** [comment]
Hi @Kapalov, when you run `./prowler -p Acc -r eu-west-1 ` does it work? can you also try to run `echo test | ansi2html -la > report.html` and see if it creates a proper html test? Thanks

**Comment by ms0x08-dev** [comment]
Hi, sure.  ./prowler -p Acc -r eu-west-1 it works. 
echo test | ansi2html -la > report.html -- it also works.
It just created a report for a very long time, everything works. Thanks. Close up

**Comment by toniblyx** [comment]
cool! Thanks for let me know. Yes, if you have hundreds of resources in your AWS account it may take long time until it finishes.
