### ISSUE TITLE
Checks 3.1 - 3.14 with Multiple Trails

### ISSUE THREAD

**Issue by fenichelar** [prowler-cloud/prowler#286]
For checks 3.1 - 3.14, if multiple trails exists, as long as one of the Trails is compliant it seems like it should not show a fail status for the other Trails. A common example of this is the Macie created Trail. I can make a PR if you agree?

**Comment by fenichelar** [comment]
FYI Security Hub only requires a single Trail to contain the alarm to show compliant status. Also, Security Hub only requires one Trail to be compliant for 2.1 and 2.4 as well.

**Comment by toniblyx** [comment]
Thanks @fenichelar, sure, a PR would be appreciated! But in any case, CIS doesn't specify anything about a single or multiple cloudtrail trails, that's why I preferred to check all of them. Another solution can be to whitelist/blacklist resources, which is a feature I'd like to add eventually.

**Comment by fenichelar** [comment]
@toniblyx I think CIS is looking for alerting when certain changes are detected. This isn't really a per Trail requirement, but a per account requirement. You can see in the Security Hub screenshot, the check is done at the account level for 3.1 - 3.14. However, 2.7 is a per Trail requirement. It seems like this should be the same. Maybe logic like this:

```
pass = 0
for each Trail {
  if trail has filter with alerting {
    pass = 1
  }
}
if pass > 0 {
  return 'PASS'
} else {
  return 'FAIL'
}
```

So there is only a single output, pass or fail. But each Trail has to be checked.

Thoughts?


![image](https://user-images.githubusercontent.com/3437075/51493423-55dd5280-1d83-11e9-8912-15b7a93b2be2.png)

![image](https://user-images.githubusercontent.com/3437075/51493604-d734e500-1d83-11e9-9d92-4f220267806d.png)

**Comment by fenichelar** [comment]
BTW, in Security Hub:
2.1 is per account
2.4 is per Trail

**Comment by toniblyx** [comment]
Ok, I see what you mean. It makes sense to have 2.1 is per account and 2.4 is per Trail as in Security Hub, but in the other side, when I run Prowler I like to see all trails and how they are configured. Still thinking that whitelisting resources could be a good solution for this use case. What do you think?

**Comment by fenichelar** [comment]
I think seeing all of the trails is one of the main benefits of Prowler over Security Hub. Security Hub is harder to identify the reason for the success or failure of a test.

But I think a whitelist is like cheating. It begs for the question, "why did you need to whitelist that, don't you comply?"

BTW, I'm running this report for my boss and others just as much as for myself. They like to see all passes. Explaining why I whitelisted something or why something is failing but isn't a problem is painful.

I'm thinking the output should look like this:

```
2.4  [check24] Ensure CloudTrail trails are integrated with CloudWatch Logs (Scored)
   INFO! AWSMacieTrail-DO-NOT-EDIT trail is not logging in the last 24h or not configured (it is in us-east-1)
   INFO! audit-log trail has been logging during the last 24h (it is in us-east-1)
   PASS! Ensure CloudTrail trails are integrated with CloudWatch Logs
```

or

```
2.4  [check24] Ensure CloudTrail trails are integrated with CloudWatch Logs (Scored)
   INFO! AWSMacieTrail-DO-NOT-EDIT trail is not logging in the last 24h or not configured (it is in us-east-1)
   INFO! audit-log trail is not logging in the last 24h or not configured (it is in us-east-1)
   FAIL! Ensure CloudTrail trails are integrated with CloudWatch Logs
```

With the PASS and FAIL lines colored accordingly of course.

What do you think?

**Comment by toniblyx** [comment]
Hi @fenichelar so far I'm going to leave this check as it is now. I understand your point but I like to see all trails and how they are configured when I run it. There is always the option to create a custom check and change `group2_logging` to reflect what you need.

Prowler does sequential checks to every resource it finds. I could change the logic but I would have to do it also in many other checks to keep consistency in all the results. That's probably for a future changes, like analyzing information from a static database after pulling all info from the API. Does it make sense? At the end of the day it is showing what it finds, you can also compare findings and detect changes.

Please, feel free to reopen it and give me more information and feedback about your experience.
