### ISSUE TITLE
Prowler not able to determine my credentials

### ISSUE THREAD

**Issue by otteydw** [prowler-cloud/prowler#29]
During my initial run of prowler, the top of the output shows as follows (showing an error message for a run of aws cli):

> This report is being generated using credentials below:
> AWS-CLI Profile: [default] AWS Region: [us-east-1]
> usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
> To see help text, you can run:
>   aws help
>   aws <command> help
>   aws <command> <subcommand> help
> aws: error: argument operation: Invalid choice, valid choices are:
> assume-role                              | assume-role-with-saml                   
> assume-role-with-web-identity            | decode-authorization-message            
> get-federation-token                     | get-session-token                       
> help                                    
> Colors Code for results:  INFORMATIVE, OK (RECOMMENDED VALUE),  CRITICAL (FIX REQUIRED)  
> Generating AWS IAM Credential Report....COMPLETE

It seems there is a problem running this command:

> $aws sts get-caller-identity --output table --profile default --region us-east-1 

> usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
> To see help text, you can run:
> 
>   aws help
>   aws <command> help
>   aws <command> <subcommand> help
> aws: error: argument operation: Invalid choice, valid choices are:
> 
> assume-role                              | assume-role-with-saml                   
> assume-role-with-web-identity            | decode-authorization-message            
> get-federation-token                     | get-session-token                       
> help                                    

I am using the latest aws cli

> $aws --version                   
> aws-cli/1.9.7 Python/2.6.6 Linux/2.6.32-573.22.1.el6.x86_64 botocore/1.3.7

**Comment by toniblyx** [comment]
Hi @otteydw, thanks for your feedback.
The latest version of AWS-CLI is 1.11.2 (in my case installed in macOS with brew). You can try to install the latest version with python pip. 

It looks like your aws-cli is not working properly because you can't even run the command:
aws sts get-caller-identity --output table --profile default --region us-east-1

What operating system are you using?

**Comment by otteydw** [comment]
Sorry about that.  I was pretty sure I had just updated to the latest aws cli prior to running prowler.  I just ran prowler again with an updated aws cli and the error is gone.  My apologies!

**Comment by toniblyx** [comment]
Thanks @otteydw remember to update your code to the latest version, I added some changes yesterday for section 3 and group checks.
