### ISSUE TITLE
Run Prowler with temporary MFA credentials

### ISSUE THREAD

**Issue by derweiser** [prowler-cloud/prowler#294]
Recommend addition to Readme to detail using the tool with temporary MFA credentials

**Comment by toniblyx** [comment]
Thanks @derweiser, I'll add information I shared with you via email last week. Thanks.

You just need to get temporary credentials then you can run prowler straight away. 

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html

Some good examples that may help:
https://github.com/asagage/aws-mfa-script
https://github.com/sweharris/aws-cli-mfa

**Comment by toniblyx** [comment]
Resolved in PR #298
