### ISSUE TITLE
awk error during "Ensure no root account access key exists"

### ISSUE THREAD

**Issue by otteydw** [prowler-cloud/prowler#30]
The following awk error was displayed during a run of prowler:

>  1.12 Ensure no root account access key exists (Scored) 
>       Found access key 1 
>       Found access key 2 
> awk: warning: escape sequence `\ ' treated as plain ` '

**Comment by toniblyx** [comment]
What Operating System are you using?

**Comment by otteydw** [comment]
Red Hat Enterprise Linux Server release 6.7 (Santiago).  I have the latest gawk package installed for this distribution.

**Comment by toniblyx** [comment]
This bug will be fixed in my next commit. Thanks.

**Comment by toniblyx** [comment]
Done
