### ISSUE TITLE
Env variables and json output

### ISSUE THREAD

**Issue by mindfulmonk** [prowler-cloud/prowler#301]
Prowler by default will read the ENV variables to figure out against which account to run the scanner. For example it will check `AWS_PROFILE`

Even though it can do that, you still have to specify a `-p ${AWS_PROFILE}` when running it as the json output otherwise doesn't have the profile name in it. This is the output you get otherwise:

`{"Profile":"ENV","Account Number":"000000000000"}`

It says ENV instead of profile name.

**Comment by toniblyx** [comment]
Ok, I have tested it and it does what I expected (but probably it is not a good idea). So when you have your profile as environment variable it reads it but it doesn't show it in the JSON, it just shows `ENV` instead but the profile with the account number are properly taken. I'm going to fix it.
