### ISSUE TITLE
Extra71 give wrong result

### ISSUE THREAD

**Issue by Tnadrev** [prowler-cloud/prowler#303]
Extra71 give wrong result
 7.1 [extra71] Ensure users with AdministratorAccess policy have MFA tokens enabled (Not Scored) (Not part of CIS benchmark)

after scanning process, I checked with aws console but I found user in admin group already enabled MFA.

Please check and fix issue.

**Comment by toniblyx** [comment]
if your user has  AdministratorAccess policy and MFA is not showed by Prowler. Should it be shown as PASS?

**Comment by toniblyx** [comment]
Probably it should do it to keep consistency with other checks in Extras.

**Comment by toniblyx** [comment]
I have reviewed that check and it looks for AdministratorAccess policy in groups, not in users. I'm going to change the title to show what it actually checks, for users with console access and MFA enabled there is already `check12`.
