### ISSUE TITLE
Doesn't Work for Freebsd Platform

### ISSUE THREAD

**Issue by farhancitrix** [prowler-cloud/prowler#310]
Freebsd it doesn't work. The workaround is to open the  include/os_detector and modify the 16th line from
if [ "$OSTYPE" == "linux-gnu" ] || [ "$OSTYPE" == "linux-musl" ]; then

To
if [ "$OSTYPE" == "linux-gnu" ] || [ "$OSTYPE" == "linux-musl" ] || ["$OSTYPE" == "freebsd" ]; then

**Comment by toniblyx** [comment]
Nice, thanks @farhancitrix, I'll add it to `devel` branch so far. But PR are welcome ;)

**Comment by toniblyx** [comment]
@farhancitrix I added it to `devel`, can you check it and let me know please?

**Comment by toniblyx** [comment]
I added it to devel and merged to master and I found and issue on it when running Prowler on OSX:

`./include/os_detector: line 16: [darwin18.2.0: command not found` 

I have reverted that change. If you can tested it better also in OSX, it would be great.
