### ISSUE TITLE
Minor Typos in Two Checks Create Invalid CSV Output

### ISSUE THREAD

**Issue by jonathanbglass** [prowler-cloud/prowler#315]
Stray commas in two extra checks cause the creation of invalid CSV.

<img width="1385" alt="Screen Shot 2019-04-18 at 5 16 42 PM" src="https://user-images.githubusercontent.com/19599038/56391836-da623480-61fd-11e9-8656-36b725fd14c3.png">

**Comment by toniblyx** [comment]
Thanks @jonathanbglass fixed already in master branch.
