### ISSUE TITLE
Break control ID out into separate column for PSV output

### ISSUE THREAD

**Issue by kmcquade** [prowler-cloud/prowler#316]
Currently looks like this:
```csv
,1234567890,us-east-1,1.1,INFO,Scored,Level 1,[check11] Avoid the use of the root account (Scored),Root account last accessed (password key_1 key_2): 2019-02-06T20:22:36+00:00 N/A N/A
```

I'm referring to [check11] always being a part of the control name. Can we break this out into a separate column? Desired state shown below.

```csv
,1234567890,us-east-1,1.1,INFO,Scored,Level 1,[check11],Avoid the use of the root account (Scored),Root account last accessed (password key_1 key_2): 2019-02-06T20:22:36+00:00 N/A N/A
```

**Comment by toniblyx** [comment]
Hi @kmcquade, if I may ask, why do you need that? you could add it easily with `./prowler -M csv -c check11|sed s/\]/\],/g` or changing the outputs here https://github.com/toniblyx/prowler/blob/master/include/outputs#L64 and `$TITLE_TEXT`. That's not a planned planned, not sure if others could benefit from it, but you can make the change to fit your needs.
