### ISSUE TITLE
extra734 check incorrectly reporting non-enforced bucket encryption

### ISSUE THREAD

**Issue by pepastach** [prowler-cloud/prowler#324]
I am getting the following output for our S3 buckets:

```
PASS! Bucket AAA has default encryption enabled with algorithm AES256
FAIL! Bucket AAA does not enforce encryption! 
PASS! Bucket BBB has default encryption enabled with algorithm AES256
FAIL! Bucket BBB does not enforce encryption!
```

The problem is in `checks/check_extra734` file, specifically in the while loop. While loops are executed in a subshell in bash. So any modification to the `ENCRYPTION` variable are lost once  the while loop ends. It is nicely explained here: https://stackoverflow.com/a/16854326

Here is a patch:

```
diff --git a/checks/check_extra734 b/checks/check_extra734
index dae7869..ddfa781 100644
--- a/checks/check_extra734
+++ b/checks/check_extra734
@@ -30,12 +30,12 @@ extra734(){
       CHECK_BUCKET_SSE_POLICY_VALUE=$(cat $TEMP_SSE_POLICY_FILE | sed -e 's/[{}]/''/g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}'| awk '/Condition/ && !skip { print } { skip = /x-amz-server-side-encryption/} '|grep -Eo "AES256|aws:kms")
       ENCRYPTION=false

-      echo "$RESULT" | while read RBUCKET SSEALG; do
+      while read RBUCKET SSEALG; do
         if [[ $SSEALG ]]; then
           textPass "Bucket $RBUCKET has default encryption enabled with algorithm $SSEALG"
           ENCRYPTION=true
         fi
-      done
+      done <<< $(echo "$RESULT")
       if [[ $CHECK_BUCKET_SSE_POLICY_PRESENT && $CHECK_BUCKET_SSE_POLICY_VALUE ]]; then
         textPass "Bucket $bucket has S3 bucket policy to enforce encryption with $CHECK_BUCKET_SSE_POLICY_VALUE"
         ENCRYPTION=true
```

**Comment by toniblyx** [comment]
Thanks @pepastach. This one is a bit tricky because what it does as it is is to check if it has encryption enabled and if it it is forced with a policy, so it gives you PASS if it is well setup at bucket level but fail if it doesn't force it. So your results are correct. Don't you need to know that info?

Another solution is to have 4 levels per check, INFO, PASS, WARN and FAIL, in that case a bucket with encryption enabled but not forced could be just a WARN... what do you think?

**Comment by pepastach** [comment]
Yeah, WARN looks like a good idea in this case. Not sure how a WARN would affect the final score, but there are certainly results somewhere between PASS and FAIL.

I'll work on the policy enforcement on our side for now. We can close the issue then and think about multiple levels. 

Thanks for your input!

**Comment by toniblyx** [comment]
Thanks @pepastach
