### ISSUE TITLE
Remove Prowler Header from JQ Output

### ISSUE THREAD

**Issue by jonrau1** [prowler-cloud/prowler#330]
Similar to Issue #190, however, this is for being able to cleanly unmarshal the JSON with Golang 

The Prowler custom text and date that is added to the top of output into JSON is interfering with setting up a struct to unmarshal the Prowler output via a Go Lambda function

Is there anyway to exclude the motif from showing up? It is easy enough to remove manually, however, for automation that will not work

**Comment by toniblyx** [comment]
Hi @jonrau1, have you tried -b option to remove banner from the output?



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonrau1** [comment]
@toniblyx - yeah that did it, guess I should have RTFM

Thanks!
