### ISSUE TITLE
Clone Prowler

### ISSUE THREAD

**Issue by ShubhamBhurke** [prowler-cloud/prowler#341]
How do I clone a prowler?
Please do forgive my mistakes, I am a Beginner. ;)

**Comment by toniblyx** [comment]
Hi @ShubhamBhurke you need to install git in your Operating System then run `git clone https://GitHub.com/toniblyx/prowler` then use it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ShubhamBhurke** [comment]
> Hi @ShubhamBhurke you need to install git in your Operating System then run `git clone https://GitHub.com/toniblyx/prowler` then use it.
> 
> Sent with [GitHawk](http://githawk.com)

Thanks a lot!
