### ISSUE TITLE
Miltiple report types at once

### ISSUE THREAD

**Issue by lacteolus** [prowler-cloud/prowler#345]
Is it possible to run prowler only one time and get two types of reports simultaneously?
We need to create HTML report and send it via email and at the same time create JSON report to store it in S3 bucket. Now it is possible only by running prowler twice: with ansi2html piping and then with -M json parameter. But actually it means we run the same tests and get exactly the same data consuming double time and spending twice as much money (it runs in AWS). The only difference is the report types witch are based on the same checks and results. 
Also it's not possible to build HTML report with prowler using JSON file generated by itself. I think it could be significant improvement if this feature was implemented.

**Comment by toniblyx** [comment]
Hi @lacteolus that’s not possible at this moment, I agree that would be very helpful and you are not the only one asking for that feature so I’ll think about it and what is the best way to implement it. Thanks! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toniblyx** [comment]
Already added, see here https://github.com/toniblyx/prowler#save-your-reports
HTML is not included in the native format, a better/nicer html output makes more sense to invest time. Probably using json or csv outputs to create something or just use the new Security Hub integration.
