### ISSUE TITLE
-e does it actually work?

### ISSUE THREAD

**Issue by dana-cleveland-pfg** [prowler-cloud/prowler#348]
It doesn't seem like -e actually does any thing.. 
It sets EXTRAS=1 but nothing that i see checks for that? and when i run prowler it still performs all the "extras" checks..

**Comment by toniblyx** [comment]
Hi @dana-cleveland-pfg I haven’t tested that option recently but I’ll give it a look to see what’s going on. Thanks for the heads up! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toniblyx** [comment]
I have just tested it and you are right, it seems other change removed that functionality. I'll try to figure out and revert it back.

**Comment by toniblyx** [comment]
Hi @dana-cleveland-pfg please, test the latest code in master branch, it is fixed already. Thanks!

**Comment by dana-cleveland-pfg** [comment]
perfect!
works now thanks!
