### ISSUE TITLE
check314 capitalization disagreement

### ISSUE THREAD

**Issue by ralphrodkey** [prowler-cloud/prowler#349]
I got an unexpected failure in check314. Upon investigation, I realized that Prowler is looking for the string "VPC", but the CIS docs specify "Vpc". The case mismatch causes the error. I made a local change to the Prowler code to be case insensitive, and that resulted in the test passing as expected.

All I really did was change the end of line https://github.com/toniblyx/prowler/blob/master/checks/check314#L27 to `/VPC/i`

**Comment by toniblyx** [comment]
I made a comment in your PR

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toniblyx** [comment]
this should be fixed already in PR #366. Please, check it out and re open it with details if needed. Thanks
