### ISSUE TITLE
Running a group with -E should exclude that check from the run

### ISSUE THREAD

**Issue by MartiUK** [prowler-cloud/prowler#351]
Right now prowler ignores the `-g` argument and continues to run every check excluding the check specified in the `-E` argument

**Comment by ricoli** [comment]
I still find this to be the case with latest version of docker image.

**Comment by toniblyx** [comment]
can you please confirm that you are using the latest version? https://hub.docker.com/r/toniblyx/prowler/builds

**Comment by ricoli** [comment]
This is strange, but a `docker pull toniblyx/prowler:latest` is bringing an image that was created 3 months ago... Its digest does however match what docker hub says was last updated 12 hours ago though: `f7e27058b6defdfdee61ac0dd010918f158d8dabfa63bf3b2906ee7bf466dae5`. When looking at the files inside the image I can see that recent changes are missing, so this image tag is definitely not up to date. For example this file added 2 days ago is missing: https://github.com/toniblyx/prowler/blob/master/checks/check_extra761
I have tried removing the image and pulling once again, still the same...

**Comment by ricoli** [comment]
```
$ docker pull toniblyx/prowler:latest
latest: Pulling from toniblyx/prowler
e7c96db7181b: Already exists 
a355bbeeb7bb: Pull complete 
Digest: sha256:f7e27058b6defdfdee61ac0dd010918f158d8dabfa63bf3b2906ee7bf466dae5
Status: Downloaded newer image for toniblyx/prowler:latest
docker.io/toniblyx/prowler:latest
```

**Comment by ricoli** [comment]
```
$ docker run --entrypoint=/bin/bash --rm -it toniblyx/prowler:latest
Unable to find image 'toniblyx/prowler:latest' locally
latest: Pulling from toniblyx/prowler
e7c96db7181b: Already exists 
a355bbeeb7bb: Pull complete 
Digest: sha256:f7e27058b6defdfdee61ac0dd010918f158d8dabfa63bf3b2906ee7bf466dae5
Status: Downloaded newer image for toniblyx/prowler:latest
bash-4.4$ ls -la /prowler/checks/check_extra76*
-rw-r--r--    1 prowler  root          1538 Jul  4 08:39 /prowler/checks/check_extra76
-rw-r--r--    1 prowler  root          2720 Jul  4 08:39 /prowler/checks/check_extra760
```

**Comment by ricoli** [comment]
To me it looks like the codebase is not being freshly cloned wherever the docker image is being built

**Comment by ricoli** [comment]
Oh of course - you see on your Dockerfile you are cloning the repo - now that will get cached once and never run again as docker has no way to know that the git clone command will result in a different outcome - https://github.com/toniblyx/prowler/blob/master/util/Dockerfile#L11
I suppose the Dockerfile should be changed to do an `ADD . /prowler` instead of cloning - that way you are guaranteed to get new images when the code changes.

**Comment by ricoli** [comment]
I have opened a PR for it. Now I have found another bug, which is actually related to this issue: while the group argument (-g) is now being respected, only the first check in the comma separated exclusion argument is being respected. For example, `-g cislevel1 -E check120,check25` results in check 120 being ignored, but not check 25.

**Comment by ricoli** [comment]
And a separate PR to actually fix this issue described above.
