### ISSUE TITLE
Missing IAM permission

### ISSUE THREAD

**Issue by zfLQ2qx2** [prowler-cloud/prowler#354]
It looks like the policy needs S3:GetEncryptionConfiguration - or maybe could be S3:Get*

**Comment by toniblyx** [comment]
Hi @zfLQ2qx2, what check is failing due to the lack of that policy?

**Comment by zfLQ2qx2** [comment]
@toniblyx It was extra734 -- "Check if S3 buckets have default encryption (SSE) enabled or use a bucket policy to enforce it"

**Comment by zfLQ2qx2** [comment]
@toniblyx Also check713 needs guardduty:GetDetector

**Comment by toniblyx** [comment]
I have added your recommendation to `iam/prowler-policy-additions.json` thanks!
