### ISSUE TITLE
Add check for idle ELB and ALBs

### ISSUE THREAD

**Issue by kpawloski** [prowler-cloud/prowler#355]
It'd be helpful if there was a check for ELB and ALBs that have either no listeners or no instances in their target pool. The check is similar to an unused security group although their are more financial penalties for having idle ELB and ALBs.

**Comment by toniblyx** [comment]
Thanks for your suggestion @kpawloski, this is more like an inventory/cost check than a security related one. I can add it to the roadmap list, in this case with low priority.

**Comment by kpawloski** [comment]
@toniblyx Yeah, certainly not a high priority check. For those that do network scans of their public facing assets, it can goose the number of assets to scan... but obviously the host they'd hit wouldn't really route anywhere... but it could indicate that something is broken in your build system if idle LBs are being left behind.

**Comment by toniblyx** [comment]
Closing this issue, consolidating new check ideas in a single place.
