### ISSUE TITLE
GetBucketLocation error

### ISSUE THREAD

**Issue by zfLQ2qx2** [prowler-cloud/prowler#356]
For a couple handfulls of our S3 buckets I'm receiving the following error, I haven't worked out what is different about those buckets, there are several multiples more that work without issue. Instance role for Prowler definitely has S3:GetBucketLocation permission.

```
An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --region: expected one argument
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --region: expected one argument
```

**Comment by toniblyx** [comment]
Hi @zfLQ2qx2, it looks like it doesn't get the region properly, where are those buckets, us-east-1? Can you please share the output (without your own information) of `bash -x ./prowler` with whatever options or specific checks you are running?

**Comment by zfLQ2qx2** [comment]
@toniblyx I'm getting the details for you, sorry its taken a couple days, wanted to take a moment to let you know I'm really impressed with prowler, I'm comparing it with a commercial offering and its 1-1 on CIS and catches a number of beyond CIS items which the other one doesn't report.

**Comment by zfLQ2qx2** [comment]
@toniblyx I found the problem, is not prowler, the buckets with the errors have very strict bucket policies and the instance role for prowler is not allowed s3:GetBucketLocation, I'm not even allowed and I'm an admin. I think the immediate fix would be for me to allow that API call on those buckets, I'm not sure if there is a way to indicate I'm auditing and be able to get the same information without allowing it directly in the policy.
