### ISSUE TITLE
Check34 failing to find alarm

### ISSUE THREAD

**Issue by museadmin** [prowler-cloud/prowler#358]
Hi Toni,

I'm having an issue with check34. On line 26 you call describe alarms like so:

`HAS_ALARM_ASSOCIATED=$($AWSCLI cloudwatch describe-alarms $PROFILE_OPT --region $CLOUDWATCH_LOGGROUP_REGION --query 'MetricAlarms[].MetricName' --output text |     awk 'BEGIN {IGNORECASE=1}; /DeletePolicy/ || /DeletePolicies/ || /Policies/ || /Policy/;')`

The aws half of this line returns the names of my alarms as a single space separated string:

`aws cloudwatch describe-alarms --region eu-west-2 --query 'MetricAlarms[].MetricName' --output text`

which includes the name of my alarm for IAM policy changes - iam_policy_change

However the second half of the command uses awk to delete the string because it matches the word policy amongst others...

`awk 'BEGIN {IGNORECASE=1}; /DeletePolicy/ || /DeletePolicies/ || /Policies/ || /Policy/;`

Resulting in the false positive for no alarm being raised:

`++ aws cloudwatch describe-alarms --region eu-west-2 --query 'MetricAlarms[].MetricName' --output text
++ awk 'BEGIN {IGNORECASE=1}; /DeletePolicy/ || /DeletePolicies/ || /Policies/ || /Policy/;'
+ HAS_ALARM_ASSOCIATED=
+ [[ -n '' ]]
+ textFail 'CloudWatch group CloudTrail/DefaultLogGroup found with metric filters but no alarms associated'`

For what it's worth, this jq filter seems to do the trick:

`aws logs describe-metric-filters --log-group-name CloudTrail/DefaultLogGroup --region eu-west-2 --query metricFilters | jq '.[] | select(.filterPattern=="{($.eventName=DeleteGroupPolicy)||($.eventName=DeleteRolePolicy)||($.eventName=DeleteUserPolicy)||($.eventName=PutGroupPolicy)||($.eventName=PutRolePolicy)||($.eventName=PutUserPolicy)||($.eventName=CreatePolicy)||($.eventName=DeletePolicy)||($.eventName=CreatePolicyVersion)||($.eventName=DeletePolicyVersion)||($.eventName=AttachRolePolicy)||($.eventName=DetachRolePolicy)||($.eventName=AttachUserPolicy)||($.eventName=DetachUserPolicy)||($.eventName=AttachGroupPolicy)||($.eventName=DetachGroupPolicy)}").metricTransformations[].metricName'`

Returns - "iam_policy_change"

**Comment by toniblyx** [comment]
Hey @museadmin I'm working with @masterinner on this to solve the issue on the PR #366

**Comment by toniblyx** [comment]
this should be fixed already in PR #366. Please, check it out and re open it with details if needed. Thanks

**Comment by museadmin** [comment]
Hi Toni,

Seems to be fixed thanks:

 3.4  [check34] Ensure a log metric filter and alarm exist for IAM policy changes (Scored)
       PASS! CloudWatch group CloudTrail/DefaultLogGroup found with metric filter iam_policy_change and alarms set
