### ISSUE TITLE
password policy disagreement

### ISSUE THREAD

**Issue by Seegras** [prowler-cloud/prowler#360]
Hi 
The password policies are rather outdated and full of superstition. Please refer to https://github.com/usnistgov/800-63-3/tree/nist-pages/sp800-63b

Namely, the following are NOT encouraged: 
- [check14] Ensure access keys are rotated every 90 days or less
- [check111] Ensure IAM password policy expires passwords within 90 days or less
- [check115] Ensure security questions are registered in the AWS account
And should actually check for the opposite. If you've got security questions set, that's a FAIL. 

Second, the following are deemed inconsequential: 
- [check15] Ensure IAM password policy requires at least one uppercase letter
- [check16] Ensure IAM password policy require at least one lowercase letter
- [check17] Ensure IAM password policy require at least one symbol
- [check18] Ensure IAM password policy require at least one number
These could be turned into "Not Scored"

Kind Regards

**Comment by toniblyx** [comment]
Thanks @Seegras, that recommendation is for NIST and the existing checks are for the AWS CIS Benchmark. If you want to check your account without those checks, you can just create a group with those you want. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Seegras** [comment]
Basically, you mean I should make Amazon change their CIS Benchmark? ;)

**Comment by toniblyx** [comment]
haha well, I mean that it is just CIS, but you can make any list of checks if you consider that those ones are not valid now. Nothing is written in stone, I still think that those are good recommendations but it is better if you don't use local users neither keys and use SAML instead.

**Comment by toniblyx** [comment]
Hey @Seegras, I'm closing this issue since it is related to the specific AWS CIS Benchmark instead of Prowler but please, feel free to report your comment to the authors of that benchmark at https://workbench.cisecurity.org/benchmarks/679 (you have to register first), they are working on the v1.3 of that publication so probably they listen for recommendations. Thanks!
