### ISSUE TITLE
Add Docker image builder

### ISSUE THREAD

**Issue by apolloclark** [prowler-cloud/prowler#361]
I've created a Docker image builder, using Packer, along with a Gradle build runner to parallelize. It creates Docker images for: CentOS 7.6, RHEL 7.6, RHEL 8.0, Ubuntu 18.04, Ubuntu 16.04.

https://github.com/apolloclark/packer-prowler

It runs great, takes only a couple of minutes to build all 5 images.

**Comment by toniblyx** [comment]
that's awesome @apolloclark, thanks! Would you like to send me a PR with that? It could go inside `utils/packer` what do you think? It is pretty helpful to test it in different Linux flavors.

**Comment by apolloclark** [comment]
Awesome, I'll open a PR later today.

**Comment by apolloclark** [comment]
I forgot to mention, this build pipeline uses another Docker image builder:
https://github.com/apolloclark/packer-python3
https://hub.docker.com/r/apolloclark/python3/tags

I created this Python3 Docker image because the "official" Python Docker image only supports: Debian 10 Buster, 9 Stretch, and Alpine.
https://hub.docker.com/_/python

The environments I work in use RHEL, CentOS, and Ubuntu.

**Comment by toniblyx** [comment]
It is all right, have you found any difference on Prowler results with the current one we are using in Prowler? `alpine:3.9`

**Comment by apolloclark** [comment]
No, I haven't seen any differences in the results. Your platform doesn't rely on OS specific base packages, like libxml, so it runs very cleanly. 😀

**Comment by toniblyx** [comment]
Closing this issue since Docker Hub and ECR images are going to be automated and pushed over there after each release.
