### ISSUE TITLE
-e flag not excluding extras from check

### ISSUE THREAD

**Issue by gvasquez95** [prowler-cloud/prowler#364]
Just tried prowler (great product, already implemented several fixes/enhancements) today (v2.1.0 clone from GIT) and the -e flag doesn't seem to work for excluding the extras from the analysis.

**Comment by toniblyx** [comment]
Thanks @gvasquez-waypoint there is a PR that solves that issue but I have to review it. I’ll do it as soon as I can. Thanks! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toniblyx** [comment]
hey @gvasquez-waypoint I have just tested it and you are right, it seems other change removed that functionality. I'll try to figure out and revert it back.

**Comment by toniblyx** [comment]
This issue is duplicated, please refer to #348

**Comment by gvasquez95** [comment]
confirmed, now the -e flag is working

**Comment by toniblyx** [comment]
Nice! thanks @gvasquez-waypoint
