### ISSUE TITLE
Double reporting in extra check 720

### ISSUE THREAD

**Issue by museadmin** [prowler-cloud/prowler#368]
Check 720 is looking to see if Lambda Functions API invocations are being logged in Cloud Trail.

At the moment I am seeing two reports for each Lambda like so:

 ```
7.20 [extra720] Check if Lambda functions invoke API operations are being recorded by CloudTrail (Not Scored) (Not part of CIS benchmark)
       INFO! eu-north-1: No Lambda functions found
       INFO! ap-south-1: No Lambda functions found
       INFO! eu-west-3: No Lambda functions found
       FAIL! eu-west-2: Lambda function load-balancer-check-test NOT enabled in trail CON-PROD-AUDIT-CT
       PASS! eu-west-2: Lambda function load-balancer-check-test enabled in trail lambda-monitoring
       FAIL! eu-west-2: Lambda function MFA_DELETE-ENFORCED-BY-BUCKET-POLICY NOT enabled in trail CON-PROD-AUDIT-CT
       PASS! eu-west-2: Lambda function MFA_DELETE-ENFORCED-BY-BUCKET-POLICY enabled in trail lambda-monitoring
       FAIL! eu-west-2: Lambda function KMS-ENCRYPTION-ENABLED NOT enabled in trail CON-PROD-AUDIT-CT
       PASS! eu-west-2: Lambda function KMS-ENCRYPTION-ENABLED enabled in trail lambda-monitoring
```

This seems to be because we have two trails enabled and the check is reporting a pass and fail for each.

Would it be better to just check that each lambda is using any trail?

**Comment by pchaganti** [comment]
This might not work in an AWS Organization based environment. The master account will usually be the one with a global trail and all member AWS accounts log to it. The Lambda functions will all be in member accounts. This check will look for a trail in the member account which will not exist.

**Comment by toniblyx** [comment]
yep, I totally get it, I have received a PR to enhance some checks that are not working well in that kind of environments and I have some others to enhance as well, including this one. I've got them on my priority list for sure. Thanks!

**Comment by toniblyx** [comment]
This issue was fixed already.
