### ISSUE TITLE
Check extra 741 passing when request has expired

### ISSUE THREAD

**Issue by museadmin** [prowler-cloud/prowler#369]
When running the scanner with a role that times out after one hour, I noticed that the check being run was reporting a PASS as well as reporting the expiry:

```
An error occurred (RequestExpired) when calling the DescribeInstanceAttribute operation: Request has expired.
       PASS! eu-west-2: No secrets found in i-0d653f4b67c200f25 User Data or it is empty
```

Perhaps this error could be trapped?

**Comment by museadmin** [comment]
Hi Toni

I re-ran the scan using a role with a longer timeout and came a cross a few more issues with this check:

All tests bar one fail with shell error "detect-secrets not found" being repeated twice each time:

`ERROR! python library detect-secrets not found. Make sure it is installed correctly and in your $PATH: syntax error: operand expected (error token is " ERROR! python library detect-secrets not found. Make sure it is installed correctly and in your $PATH")`

It might be an idea to add some documentation around getting this installed on your instances if you want to use the check?


There is quite a bit of code duplication in this script that could be moved into a function. 
Also the second FINDINGS section does not delete the secrets on fail, is this intentional?

```
FINDINGS=$(secretsDetector file $EC2_USERDATA_FILE)
if [[ $FINDINGS -eq 0 ]]; then
  textPass "$regx: No secrets found in $instance" "$regx"
  \# delete file if nothing interesting is there
  rm -f $EC2_USERDATA_FILE
else
  textFail "$regx: Potential secret found in $instance" "$regx"
  \# delete file to not leave trace, user must look at the instance User Data
  rm -f $EC2_USERDATA_FILE
fi
```

and

```
FINDINGS=$(secretsDetector file $EC2_USERDATA_FILE)
if [[ $FINDINGS -eq 0 ]]; then
  textPass "$regx: No secrets found in $instance User Data" "$regx"
  rm -f $EC2_USERDATA_FILE
else
  textFail "$regx: Potential secret found in $instance" "$regx"
fi
```

I couldn't find this check mentioned in your documentation. I was looking to see how you handle passing in a baseline for the detector to compare against as mentioned on the Yelp docs.

e.g. 

detect-secrets audit .secrets.baseline

**Comment by JamieOrlando-Engooden** [comment]
@toniblyx Why not just catch the request has expired exception and try to re-assume the role using the instance credentials, since role chaining is limited to 1 hour?

**Comment by toniblyx** [comment]
That is implemented already, see here https://github.com/toniblyx/prowler/blob/583cffaefb067e8fbd81a5300db11a0a841102b2/prowler#L346-L358
