### ISSUE TITLE
7.5 should ignore default security groups

### ISSUE THREAD

**Issue by cloudlena** [prowler-cloud/prowler#371]
`extra75` tells me I have unused security groups. However, these are default security groups of VCS which I cannot delete so there's nothing I can do about that. Should we ignore the default security groups of VPCs for 7.5? We could also only ignore them if they have no ingress/egress rules set (which is the case for me).

**Comment by zfLQ2qx2** [comment]
@mastertinner fixed in https://github.com/toniblyx/prowler/pull/411

**Comment by toniblyx** [comment]
Awesome, thanks!
