### ISSUE TITLE
7.47 checks for inexistent DB property

### ISSUE THREAD

**Issue by cloudlena** [prowler-cloud/prowler#374]
`check747` checks for an inexistent property of RDS DB instances. The property `DBInstances[*].EnabledCloudwatchLogsExports` doesn't exist according to https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBInstances.html. Therefore this check is, in its current state, useless.

Should we rather check for `DBInstances[*].EnhancedMonitoringResourceArn` instead?

**Comment by toniblyx** [comment]
I missed this issue, sorry about that. It looks like that might be change in the API or a bit mistake from my side. I´ll look at it.

**Comment by toniblyx** [comment]
Actually you can enable CloudWatchLog Exports by modifying a RDS instance:

![Screenshot 2019-12-17 11 13 40](https://user-images.githubusercontent.com/3985464/70986556-6d6daa00-20be-11ea-8126-a8169ee52057.png)

It is described here https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DBInstance.html. This check is working as expected.

**Comment by cloudlena** [comment]
Ah, you're right. I guess I was looking at the wrong API description. Sorry about that.
