### ISSUE TITLE
check_extra71 needs the credentials report

### ISSUE THREAD

**Issue by willthames** [prowler-cloud/prowler#378]
check_extra71 relies on the credentials report being generated and saved, but it is not if the group1 checks haven't run

This causes false positives - `USER_MFA_ENABLED` is set to nothing, as the grep doesn't match at all, and so doesn't equal `"true"`.

**Comment by switchdk** [comment]
I can confirm this issue as reported by @willthames 

By running the check on its own as `./prowler -c extra71` it will provide false positives. To prove @willthames 's point, you can compare the result with running `./prowler -c check12,extra71
`, which provides the correct result.

**Comment by zfLQ2qx2** [comment]
@toniblyx I'm not able to reproduce this with "prowler -c extra71" -- $TEMP_REPORT_FILE seems to always be set and point to a valid credential report. Did you have a test case for this issue?

**Comment by toniblyx** [comment]
I was able to reproduce this issue and now is fixed. Thanks!
