### ISSUE TITLE
prowler doesn't execute

### ISSUE THREAD

**Issue by sknadella87** [prowler-cloud/prowler#379]
Here's the error message I get when I run prowler.

`root@USNWIMR9DC:/mnt/c/Users/snla001/Downloads/prowler# ./prowler
./include/colors: line 2: $'\r': command not found
./include/colors: line 13: $'\r': command not found
./include/colors: line 67: syntax error near unexpected token `$'{\r''
'/include/colors: line 67: `printColorsCode(){
./include/os_detector: line 2: $'\r': command not found
./include/os_detector: line 13: $'\r': command not found
./include/os_detector: line 14: $'\r': command not found
./include/os_detector: line 20: syntax error near unexpected token `$'\r''
'/include/os_detector: line 20: `  how_older_from_today()
./include/aws_profile_loader: line 2: $'\r': command not found
./include/aws_profile_loader: line 13: $'\r': command not found
./include/aws_profile_loader: line 14: $'\r': command not found
./include/aws_profile_loader: line 18: $'\r': command not found
./include/aws_profile_loader: line 26: syntax error near unexpected token `elif'
'/include/aws_profile_loader: line 26: `elif [[ $AWS_ACCESS_KEY_ID && $AWS_SECRET_ACCESS_KEY || $AWS_SESSION_TOKEN || $AWS_PROFILE ]];then
./include/awscli_detector: line 2: $'\r': command not found
./include/awscli_detector: line 13: $'\r': command not found
./include/awscli_detector: line 21: syntax error: unexpected end of file
./include/outputs: line 2: $'\r': command not found
./include/outputs: line 13: $'\r': command not found
./include/outputs: line 15: syntax error near unexpected token `$'{\r''
'/include/outputs: line 15: `textPass(){
./include/csv_header: line 2: $'\r': command not found
./include/csv_header: line 13: $'\r': command not found
./include/csv_header: line 14: $'\r': command not found
./include/csv_header: line 15: syntax error near unexpected token `$'{\r''
'/include/csv_header: line 15: `printCsvHeader() {
./include/banner: line 2: $'\r': command not found
./include/banner: line 13: $'\r': command not found
./include/banner: line 14: syntax error near unexpected token `$'{\r''
'/include/banner: line 14: `prowlerBanner() {
./include/whoami: line 2: $'\r': command not found
./include/whoami: line 13: $'\r': command not found
./include/whoami: line 14: $'\r': command not found
./include/whoami: line 16: syntax error near unexpected token `$'{\r''
'/include/whoami: line 16: `getWhoami(){
./include/credentials_report: line 2: $'\r': command not found
./include/credentials_report: line 13: $'\r': command not found
./include/credentials_report: line 15: syntax error near unexpected token `$'{\r''
'/include/credentials_report: line 15: `genCredReport() {
./include/scoring: line 2: $'\r': command not found
./include/scoring: line 13: $'\r': command not found
./include/scoring: line 15: syntax error near unexpected token `$'{\r''
'/include/scoring: line 15: `scoring(){
./include/python_detector: line 2: $'\r': command not found
./include/python_detector: line 13: $'\r': command not found
./include/python_detector: line 15: syntax error near unexpected token `$'{\r''
'/include/python_detector: line 15: `pythonDetector(){
./include/secrets_detector: line 2: $'\r': command not found
./include/secrets_detector: line 13: $'\r': command not found
./include/secrets_detector: line 15: syntax error near unexpected token `$'{\r''
'/include/secrets_detector: line 15: `secretsDetector(){
./include/check3x: line 2: $'\r': command not found
./include/check3x: line 10: $'\r': command not found
./include/check3x: line 11: syntax error near unexpected token `$'{\r''
'/include/check3x: line 11: `check3x(){
: No such file or directoryin/aws
./groups/group10_hipaa: line 2: $'\r': command not found
./groups/group10_hipaa: line 13: $'\r': command not found
./groups/group10_hipaa: line 19: $'\r': command not found
./groups/group11_secrets: line 2: $'\r': command not found
./groups/group11_secrets: line 13: $'\r': command not found
./groups/group11_secrets: line 19: $'\r': command not found
./groups/group11_secrets: line 22: $'\r': command not found
./groups/group12_apigateway: line 2: $'\r': command not found
./groups/group12_apigateway: line 13: $'\r': command not found
./groups/group12_apigateway: line 19: $'\r': command not found
./groups/group13_rds: line 2: $'\r': command not found
./groups/group13_rds: line 13: $'\r': command not found
./groups/group1_iam: line 2: $'\r': command not found
./groups/group1_iam: line 10: $'\r': command not found
./groups/group2_logging: line 2: $'\r': command not found
./groups/group2_logging: line 10: $'\r': command not found
./groups/group3_monitoring: line 2: $'\r': command not found
./groups/group3_monitoring: line 10: $'\r': command not found
./groups/group4_networking: line 2: $'\r': command not found
./groups/group4_networking: line 10: $'\r': command not found
./groups/group5_cislevel1: line 2: $'\r': command not found
./groups/group5_cislevel1: line 10: $'\r': command not found
./groups/group6_cislevel2: line 2: $'\r': command not found
./groups/group6_cislevel2: line 10: $'\r': command not found
./groups/group7_extras: line 2: $'\r': command not found
./groups/group7_extras: line 13: $'\r': command not found
./groups/group7_extras: line 19: $'\r': command not found
./groups/group8_forensics: line 2: $'\r': command not found
./groups/group8_forensics: line 13: $'\r': command not found
./groups/group9_gdpr: line 2: $'\r': command not found
./groups/group9_gdpr: line 13: $'\r': command not found
./groups/group9_gdpr: line 19: $'\r': command not found
./checks/check11: line 2: $'\r': command not found
./checks/check11: line 10: $'\r': command not found
./checks/check11: line 16: $'\r': command not found
./checks/check11: line 17: syntax error near unexpected token `$'{\r''
'/checks/check11: line 17: `check11(){
./checks/check110: line 2: $'\r': command not found
./checks/check110: line 10: $'\r': command not found
./checks/check110: line 16: $'\r': command not found
./checks/check110: line 17: syntax error near unexpected token `$'{\r''
'/checks/check110: line 17: `check110(){
./checks/check111: line 2: $'\r': command not found
./checks/check111: line 10: $'\r': command not found
./checks/check111: line 16: $'\r': command not found
./checks/check111: line 17: syntax error near unexpected token `$'{\r''
'/checks/check111: line 17: `check111(){
./checks/check112: line 2: $'\r': command not found
./checks/check112: line 10: $'\r': command not found
./checks/check112: line 16: $'\r': command not found
./checks/check112: line 17: syntax error near unexpected token `$'{\r''
'/checks/check112: line 17: `check112(){
./checks/check113: line 2: $'\r': command not found
./checks/check113: line 10: $'\r': command not found
./checks/check113: line 16: $'\r': command not found
./checks/check113: line 17: syntax error near unexpected token `$'{\r''
'/checks/check113: line 17: `check113(){
./checks/check114: line 2: $'\r': command not found
./checks/check114: line 10: $'\r': command not found
./checks/check114: line 16: $'\r': command not found
./checks/check114: line 17: syntax error near unexpected token `$'{\r''
'/checks/check114: line 17: `check114(){
./checks/check115: line 2: $'\r': command not found
./checks/check115: line 10: $'\r': command not found
./checks/check115: line 16: $'\r': command not found
./checks/check115: line 17: syntax error near unexpected token `$'{\r''
'/checks/check115: line 17: `check115(){
./checks/check116: line 2: $'\r': command not found
./checks/check116: line 10: $'\r': command not found
./checks/check116: line 16: $'\r': command not found
./checks/check116: line 17: syntax error near unexpected token `$'{\r''
'/checks/check116: line 17: `check116(){
./checks/check117: line 2: $'\r': command not found
./checks/check117: line 10: $'\r': command not found
./checks/check117: line 16: $'\r': command not found
./checks/check117: line 17: syntax error near unexpected token `$'{\r''
'/checks/check117: line 17: `check117(){
./checks/check118: line 2: $'\r': command not found
./checks/check118: line 10: $'\r': command not found
./checks/check118: line 16: $'\r': command not found
./checks/check118: line 17: syntax error near unexpected token `$'{\r''
'/checks/check118: line 17: `check118(){
./checks/check119: line 2: $'\r': command not found
./checks/check119: line 10: $'\r': command not found
./checks/check119: line 16: $'\r': command not found
./checks/check119: line 17: syntax error near unexpected token `$'{\r''
'/checks/check119: line 17: `check119(){
./checks/check12: line 2: $'\r': command not found
./checks/check12: line 10: $'\r': command not found
./checks/check12: line 16: $'\r': command not found
./checks/check12: line 17: syntax error near unexpected token `$'{\r''
'/checks/check12: line 17: `check12(){
./checks/check120: line 2: $'\r': command not found
./checks/check120: line 10: $'\r': command not found
./checks/check120: line 16: $'\r': command not found
./checks/check120: line 17: syntax error near unexpected token `$'{\r''
'/checks/check120: line 17: `check120(){
./checks/check121: line 2: $'\r': command not found
./checks/check121: line 10: $'\r': command not found
./checks/check121: line 16: $'\r': command not found
./checks/check121: line 17: syntax error near unexpected token `$'{\r''
'/checks/check121: line 17: `check121(){
./checks/check122: line 2: $'\r': command not found
./checks/check122: line 10: $'\r': command not found
./checks/check122: line 16: $'\r': command not found
./checks/check122: line 17: syntax error near unexpected token `$'{\r''
'/checks/check122: line 17: `check122(){
./checks/check13: line 2: $'\r': command not found
./checks/check13: line 10: $'\r': command not found
./checks/check13: line 16: $'\r': command not found
./checks/check13: line 17: syntax error near unexpected token `$'{\r''
'/checks/check13: line 17: `check13(){
./checks/check14: line 2: $'\r': command not found
./checks/check14: line 10: $'\r': command not found
./checks/check14: line 16: $'\r': command not found
./checks/check14: line 17: syntax error near unexpected token `$'{\r''
'/checks/check14: line 17: `check14(){
./checks/check15: line 2: $'\r': command not found
./checks/check15: line 10: $'\r': command not found
./checks/check15: line 16: $'\r': command not found
./checks/check15: line 17: syntax error near unexpected token `$'{\r''
'/checks/check15: line 17: `check15(){
./checks/check16: line 2: $'\r': command not found
./checks/check16: line 10: $'\r': command not found
./checks/check16: line 16: $'\r': command not found
./checks/check16: line 17: syntax error near unexpected token `$'{\r''
'/checks/check16: line 17: `check16(){
./checks/check17: line 2: $'\r': command not found
./checks/check17: line 10: $'\r': command not found
./checks/check17: line 16: $'\r': command not found
./checks/check17: line 17: syntax error near unexpected token `$'{\r''
'/checks/check17: line 17: `check17(){
./checks/check18: line 2: $'\r': command not found
./checks/check18: line 10: $'\r': command not found
./checks/check18: line 16: $'\r': command not found
./checks/check18: line 17: syntax error near unexpected token `$'{\r''
'/checks/check18: line 17: `check18(){
./checks/check19: line 2: $'\r': command not found
./checks/check19: line 10: $'\r': command not found
./checks/check19: line 16: $'\r': command not found
./checks/check19: line 17: syntax error near unexpected token `$'{\r''
'/checks/check19: line 17: `check19(){
./checks/check21: line 2: $'\r': command not found
./checks/check21: line 10: $'\r': command not found
./checks/check21: line 16: $'\r': command not found
./checks/check21: line 17: syntax error near unexpected token `$'{\r''
'/checks/check21: line 17: `check21(){
./checks/check22: line 2: $'\r': command not found
./checks/check22: line 10: $'\r': command not found
./checks/check22: line 16: $'\r': command not found
./checks/check22: line 17: syntax error near unexpected token `$'{\r''
'/checks/check22: line 17: `check22(){
./checks/check23: line 2: $'\r': command not found
./checks/check23: line 10: $'\r': command not found
./checks/check23: line 16: $'\r': command not found
./checks/check23: line 17: syntax error near unexpected token `$'{\r''
'/checks/check23: line 17: `check23(){
./checks/check24: line 2: $'\r': command not found
./checks/check24: line 10: $'\r': command not found
./checks/check24: line 16: $'\r': command not found
./checks/check24: line 17: syntax error near unexpected token `$'{\r''
'/checks/check24: line 17: `check24(){
./checks/check25: line 2: $'\r': command not found
./checks/check25: line 10: $'\r': command not found
./checks/check25: line 16: $'\r': command not found
./checks/check25: line 17: syntax error near unexpected token `$'{\r''`

**Comment by toniblyx** [comment]
hello, how did you download it? Please use `git clone https://github.com/toniblyx/prowler/` then `cd prowler` they `./prowler` and make sure you have use bash on linux or mac, or windows with cygwin.

**Comment by sknadella87** [comment]
Hello, I have tried setting up Ubuntu on Windows machine and have tried executing prowler after aws configure. But I'm seeing the error messages posted above when I execute prowler. 
I'm now installing cygwin and will run prowler using cygwin to see if that works. Will keep you posted.

**Comment by sknadella87** [comment]
Similar issue when I try to run prowler on cygwin

`001@USNWIMR9DC /cygdrive/c/Users/Downloads/prowler
$ ./prowler
./include/colors: line 2: $'\r': command not found
./include/colors: line 13: $'\r': command not found
./include/colors: line 67: syntax error near unexpected token `$'{\r''
'/include/colors: line 67: `printColorsCode(){
./include/os_detector: line 2: $'\r': command not found
./include/os_detector: line 13: $'\r': command not found
./include/os_detector: line 14: $'\r': command not found
./include/os_detector: line 20: syntax error near unexpected token `$'\r''
'/include/os_detector: line 20: `  how_older_from_today()
./include/aws_profile_loader: line 2: $'\r': command not found
./include/aws_profile_loader: line 13: $'\r': command not found
./include/aws_profile_loader: line 14: $'\r': command not found
./include/aws_profile_loader: line 18: $'\r': command not found
./include/aws_profile_loader: line 19: curl: command not found
./include/aws_profile_loader: line 26: syntax error near unexpected token `elif'
./include/aws_profile_loader: line 26: `elif [[ $AWS_ACCESS_KEY_ID && $AWS_SECRE'_ACCESS_KEY || $AWS_SESSION_TOKEN || $AWS_PROFILE ]];then
./include/awscli_detector: line 2: $'\r': command not found
./include/awscli_detector: line 13: $'\r': command not found
./include/awscli_detector: line 21: syntax error: unexpected end of file
./include/outputs: line 2: $'\r': command not found
./include/outputs: line 13: $'\r': command not found
./include/outputs: line 15: syntax error near unexpected token `$'{\r''
'/include/outputs: line 15: `textPass(){
./include/csv_header: line 2: $'\r': command not found
./include/csv_header: line 13: $'\r': command not found
./include/csv_header: line 14: $'\r': command not found
./include/csv_header: line 15: syntax error near unexpected token `$'{\r''
'/include/csv_header: line 15: `printCsvHeader() {
./include/banner: line 2: $'\r': command not found
./include/banner: line 13: $'\r': command not found
./include/banner: line 14: syntax error near unexpected token `$'{\r''
'/include/banner: line 14: `prowlerBanner() {
./include/whoami: line 2: $'\r': command not found
./include/whoami: line 13: $'\r': command not found
./include/whoami: line 14: $'\r': command not found
./include/whoami: line 16: syntax error near unexpected token `$'{\r''
'/include/whoami: line 16: `getWhoami(){
./include/credentials_report: line 2: $'\r': command not found
./include/credentials_report: line 13: $'\r': command not found
./include/credentials_report: line 15: syntax error near unexpected token `$'{\r''
'/include/credentials_report: line 15: `genCredReport() {
./include/scoring: line 2: $'\r': command not found
./include/scoring: line 13: $'\r': command not found
./include/scoring: line 15: syntax error near unexpected token `$'{\r''
'/include/scoring: line 15: `scoring(){
./include/python_detector: line 2: $'\r': command not found
./include/python_detector: line 13: $'\r': command not found
./include/python_detector: line 15: syntax error near unexpected token `$'{\r''
'/include/python_detector: line 15: `pythonDetector(){
./include/secrets_detector: line 2: $'\r': command not found
./include/secrets_detector: line 13: $'\r': command not found
./include/secrets_detector: line 15: syntax error near unexpected token `$'{\r''
'/include/secrets_detector: line 15: `secretsDetector(){
./include/check3x: line 2: $'\r': command not found
./include/check3x: line 10: $'\r': command not found
./include/check3x: line 11: syntax error near unexpected token `$'{\r''
'/include/check3x: line 11: `check3x(){
./prowler: line 175: /cygdrive/c/Program: No such file or directory
./groups/group1_iam: line 2: $'\r': command not found
./groups/group1_iam: line 10: $'\r': command not found
./groups/group10_hipaa: line 2: $'\r': command not found
./groups/group10_hipaa: line 13: $'\r': command not found
./groups/group10_hipaa: line 19: $'\r': command not found
./groups/group11_secrets: line 2: $'\r': command not found
./groups/group11_secrets: line 13: $'\r': command not found
./groups/group11_secrets: line 19: $'\r': command not found
./groups/group11_secrets: line 22: $'\r': command not found
./groups/group12_apigateway: line 2: $'\r': command not found
./groups/group12_apigateway: line 13: $'\r': command not foun`

**Comment by toniblyx** [comment]
can you please reproduce here step by step what you are doing? It seems weird result, like not properly downloading or it is not executable.

**Comment by sknadella87** [comment]
I have cloned prowler repo using github desktop. 

Using Ubuntu or Cygwin on Windows, I have performed the following steps:

1. installed awscli
2. aws configure
2. cd prowler
3. ./prowler 

and I get the error message listed above. 

Initially, I thought that the prowler file had special character and in one of the post I see that the file had to be converted to Unix. I did that through both Sublime and Notepad++ but when I try to execute prowler. I still get the exact same error message. 

Would you be able to email me the prowler file that you think is working just to make sure.

**Comment by toniblyx** [comment]
I don´t use cygwin and I can´t try to reproduce it but if you did the same in ubuntu and doesn´t work make sure prowler file is executable with `chmod +x prowler` (to the file, not the directory)

**Comment by davidholsgrove** [comment]
I found this to be line endings on WSL Ubuntu.
A dos2unix shows;

```
$ dos2unix prowler
dos2unix: Binary symbol 0x1B found at line 31
dos2unix: Skipping binary file prowler
```

But just forcing the conversion was enough (`dos2unix -f prowler`). 
Then recursively doing the same to the files in includes, groups, checks etc
