### ISSUE TITLE
Load Balancer Security Group fails extra74

### ISSUE THREAD

**Issue by amsully** [prowler-cloud/prowler#386]
If a load balancer has ingress for say HTTPS via 0.0.0.0/0 443 the security group ingress check will fail.

The recommended sg configuration by AWS thus fails this prowler check: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-update-security-groups.html

**Comment by toniblyx** [comment]
Thanks, this check is only to find SG without ingress filtering which _in some cases_ can be good to know for security reasons, you can disable that check or remove it from the extras group if you like.
