### ISSUE TITLE
Error evaluating Extra725

### ISSUE THREAD

**Issue by theOriginalClauBotas** [prowler-cloud/prowler#387]
Guys have you seen that 
BUCKETS_OBJECT_LOGGING_ENABLED=$($AWSCLI cloudtrail get-event-selectors --trail-name "${TRAIL_NAME}" $PROFILE_OPT --region $TRAIL_REGION --query "EventSelectors[*].DataResources[?Type == \`AWS::S3::Object\`].Values" --output text |xargs -n1 |cut -d: -f 6|sed 's/\///g')

Has to be replaced with
BUCKETS_OBJECT_LOGGING_ENABLED=$($AWSCLI cloudtrail get-event-selectors --trail-name "${TRAIL_NAME}" $PROFILE_OPT --region $TRAIL_REGION --query "EventSelectors[*].DataResources[?Type == \`AWS::S3::Object\`].Values" --output text |xargs -n1 |cut -d: -f 6|sed 's/\///g'|sed 's/\*//g')

Because currently it is removing the / but no the * when listing the buckets

I have the next output when I run extra725
 
 7.25 [extra725] Check if S3 buckets have Object-level logging enabled in CloudTrail (Not Scored) (Not part of CIS benchmark) 
       INFO! Looking for S3 Buckets Object-level logging information in all trails...   
       PASS! us-west-2: S3 bucket BUCKET* has Object-level logging enabled in trail 
       FAIL! us-west-2: S3 bucket BUCKET has Object-level logging disabled

**Comment by toniblyx** [comment]
Thanks, for the heads up. Can you explain it better please? What is your buckets name?

**Comment by theOriginalClauBotas** [comment]
This is the complete output7.25 [extra725] Check if S3 buckets have Object-level logging enabled in CloudTrail (Not Scored) (Not part of CIS benchmark) 
       INFO! Looking for S3 Buckets Object-level logging information in all trails...   
       PASS! us-west-2: S3 bucket cf-templates-10286eovwqo38-us-east-1* has Object-level logging enabled in trail 
       PASS! us-west-2: S3 bucket config-bucket-200575803985* has Object-level logging enabled in trail 
       PASS! us-west-2: S3 bucket gnptrail-gnpctrails3bucket-mcv557m1ickd* has Object-level logging enabled in trail 
       PASS! us-west-2: S3 bucket gnptrail-rarchivelogsbucket-1wv9ba6thy19v* has Object-level logging enabled in trail 
       PASS! us-west-2: S3 bucket mx-gs-indicadores-ch-prod-cloudtrail* has Object-level logging enabled in trail 
       FAIL! us-west-2: S3 bucket cf-templates-10286eovwqo38-us-east-1 has Object-level logging disabled 
       FAIL! us-west-2: S3 bucket config-bucket-200575803985 has Object-level logging disabled 
       FAIL! us-west-2: S3 bucket gnptrail-gnpctrails3bucket-mcv557m1ickd has Object-level logging disabled 
       FAIL! us-west-2: S3 bucket gnptrail-rarchivelogsbucket-1wv9ba6thy19v has Object-level logging disabled 
       FAIL! us-west-2: S3 bucket mx-gs-indicadores-ch-prod-cloudtrail has Object-level logging disabled 
Is taking all the buckets as if they didn't have Object-level logging and at the same time it says that the buckets have Object-level, but that happends because when evaluate the selectors of the trail ( cloudtrail get-event-selectors ) it gets the name of the bucket but the name is incorrect because with sed 's////g' removes the "/" but the name of the buckets after that command remains with the "*", so like the output says, the command is taking the name as BUCKET* after removing all the unwanted substrings of the arn of each bucket.

i.e. 
Check says
 FAIL! us-west-2: S3 bucket config-bucket-200575803985 has Object-level logging disabled
but
 
![Extra725](https://user-images.githubusercontent.com/36703035/65646197-e37edb00-dfbf-11e9-8a13-007f86acd41c.png)

**Comment by theOriginalClauBotas** [comment]
Try with any bucket Object-logging enabled you have. The checks says PASS and FAIL for every Object-logging enabled bucket

**Comment by toniblyx** [comment]
Yes, that was for a reason, I wanted to hit to birds with one stone but I think the easier the better, I'll see how is the best way to make this check more helpful. Thanks!

**Comment by toniblyx** [comment]
This was fixed already.
