### ISSUE TITLE
extra719 Fails for private hosted zones

### ISSUE THREAD

**Issue by amsully** [prowler-cloud/prowler#389]
Extra719 fails in private hosted zones even though Query Logging is disabled for privates hosted zones in AWS:

```
prowler$ aws route53 create-query-logging-config 
     --hosted-zone-id /hostedzone/EXAMPLE 
     --cloud-watch-logs-log-group-arn arn:EXAMPLE

An error occurred (InvalidInput) when calling the CreateQueryLoggingConfig operation: 
You can't create a query logging config for a private hosted zone.
```

But prowler still fails:

```
 7.19 [extra719] Check if Route53 hosted zones are logging queries to CloudWatch Logs (Not Scored) (Not part of CIS benchmark) 
       FAIL! Route53 hosted zone Id /hostedzone/EXAMPLE has query logging disabled! 
```

**Comment by toniblyx** [comment]
Thanks for letting me know @amsully, I can´t test that check right now but if you know any way to filter by private/public hosted zones I can tell you how to fix it and test it.

**Comment by amsully** [comment]
I will look into it and get back to you.

**Comment by theOriginalClauBotas** [comment]
Then I assume this is already a Bug. Right?

**Comment by toniblyx** [comment]
@theOriginalClauBotas I tagged it as bug
