### ISSUE TITLE
ansi2html doesn't work with Prowler in python 3  is installed

### ISSUE THREAD

**Issue by Cybernewbies** [prowler-cloud/prowler#393]
Hi Toni,

I have deployed this application in a Centos Linux OS in which python 3.0 dependencies includes PIP have been installed , but i have prompted with stack error ..

test@ash-prowler prowler]$ ./prowler | ansi2html -la > /home/testeruser/cloudsecu                                                     rity/PROD-REPORT.html -p uat

Unknown output type: html

Unknown output type: html

Unknown output type: html

Unknown output type: html

Unknown output type: html
^CTraceback (most recent call last):
  File "/usr/bin/ansi2html", line 9, in <module>
    load_entry_point('ansi2html==1.5.2', 'console_scripts', 'ansi2html')()
  File "/usr/lib/python2.7/site-packages/ansi2html/converter.py", line 608, in m                                                     ain
    map(_read, sys.stdin.readlines())

Do we have any way to export the report based on various profile such as Dev, Prod. UAT instance in AWS.? How could we overcome this issue.?

**Comment by Cybernewbies** [comment]
Please let me know , if you need any information on logs via Prowler tool ..

**Comment by Cybernewbies** [comment]
![image](https://user-images.githubusercontent.com/36504310/66733799-558b6700-ee7e-11e9-8039-eeed5b12ff20.png)

**Comment by Cybernewbies** [comment]
[root@ash-prowler util]# cd ..
[root@ash-prowler prowler]# pip install awscli ansihtml boto3 detect-secrets
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: awscli in /usr/lib/python2.7/site-packages (1.15.83)
Collecting ansihtml
  ERROR: Could not find a version that satisfies the requirement ansihtml (from versions: none)
ERROR: No matching distribution found for ansihtml

**Comment by toniblyx** [comment]
Hello,

I think you are running it in the wrong order. If I understand correctly what you are trying is probably this: 

`./prowler -p uat | ansi2html -la > /home/testeruser/cloudsecurity/PROD-REPORT.html`

`-p` option is a `prowler` flag, not an `ansi2html` one. I also recommend you to test `ansi2html` without prowler to make sure it is working correctly, with something like `echo test | ansi2html -la > test.html`

I also see that your command `pip install awscli ansihtml boto3 detect-secrets` is wrong naming `ansi2html` package.

**Comment by Cybernewbies** [comment]
I have created an Custom profile with Dev, Prod,UAT. But we need to pull the report in the html format . So i have used some for later part of analysis using color format with the help of ansi2html.

./prowler | ansi2html -la > report.html(used by you)
./prowler | ansi2html -la > /home/testeruser/cloudsecurity/PROD-REPORT.html -p prod

Still i'm not able to populate the report in the right manner. Please help me how to get the html based report using an customized profile like above. I'm running the command with normal user so i have  /home/testeruser/cloudsecurity/ here.

**Comment by toniblyx** [comment]
As I mentioned before, you are executing it wrong, `-p prod` is the profile, that is an option for prowler and you are using it as an option for ansi2html. Please run it as below:

`./prowler -p prod | ansi2html -la > /home/testeruser/cloudsecurity/PROD-REPORT.html`

**Comment by toniblyx** [comment]
Can you please confirm if that was the case?
