### ISSUE TITLE
What is the thought behind check extra79?

### ISSUE THREAD

**Issue by zfLQ2qx2** [prowler-cloud/prowler#398]
What is the thought behind check extra79? If ELBs are not internet facing then how do you expect to ingress traffic into your VPC? Wouldn't anything in front of the ELB be just another layer?

**Comment by toniblyx** [comment]
Hi @zfLQ2qx2 that check is just to know what is exposed to the intenet, a FAIL there is not necessarily a bad thing, just information in case of an issue or a heads up for resources to look at in more detail. Does it make sense?

**Comment by zfLQ2qx2** [comment]
@toniblyx I'm not sure that it makes any more sense then a rule that alerted on ELBs that were not public. In either case your essentially asking people to check if the ELB is what its intended, so it reduces down to an "elb exists" check. It might make more sense top alert on a public facing ELB in a non-routable subnet, or an internal-facing ELB on a public subnet, as these are cases where there appears to be contradiction.

**Comment by toniblyx** [comment]
I understand that not always may fit for purpose. For example, if I'm doing an assessment for an account, I want to see ASAP what is exposed to the internet to figure out the existing attack surface and potential attack vectors. As a continuous security check it is not probably the best one to have. It is a matter of use case I guess. 

You can delete the check or just disable it from the extras group if you don't need it.

**Comment by zfLQ2qx2** [comment]
@toniblyx Yeah! I didn't notice you had merged the PR to disable individual checks until just now. That'll work, thanks!
