### ISSUE TITLE
Bug with IAM password policy queries

### ISSUE THREAD

**Issue by alexpriscott** [prowler-cloud/prowler#4]
Hi,

Great tool! When testing i have noticed a bug with the IAM password policy queries.

The code (line 307) should be lowercase true:

from `if [ $COMMAND15 == "True" ];then`
to `if [ $COMMAND15 == "true" ];then`

and the same for lines 318, 329, 340.

**Comment by toniblyx** [comment]
Thanks Alex, I have just fixed them and updated the code for checks 15, 16, 17 and 18.
