### ISSUE TITLE
extra725 catch-all rule for all logging events

### ISSUE THREAD

**Issue by deppy** [prowler-cloud/prowler#402]
check_extra725 is checking that every individual bucket has a rule in place; however, cloudtrail also allows you to specify a value of `arn:aws:s3:::` which would do object-level logging for every bucket created, so you don't have to specify every single bucket.

It seems like this check should first look for that and if it exists, pass, otherwise go through and check every single bucket individually.

**Comment by toniblyx** [comment]
Thanks @deppy, if I understand correctly, do you mean it would make more sense to have this peace of code below:

```
# create a file with a list of all buckets
  TEMP_BUCKET_LIST_FILE=$(mktemp -t prowler.bucket-list-XXXXXX)
  $AWSCLI s3api list-buckets --query 'Buckets[*].{Name:Name}' $PROFILE_OPT --region $REGION --output text > $TEMP_BUCKET_LIST_FILE
  if [ ! -s $TEMP_BUCKET_LIST_FILE ]; then
    textInfo "$regx: No S3 buckets found" "$regx"
    exit
  fi
```

right before the section `  # diff to get the ones that are not in any trail then they are not logging
` ?

**Comment by deppy** [comment]
Nope. You can actually configure object-level logging globally (instead of specifying each bucket individually)

<img width="1251" alt="Screen Shot 2019-10-28 at 21 13 03" src="https://user-images.githubusercontent.com/1371279/67714312-f114ef80-f9c7-11e9-8395-60a4048a30d1.png">

You can see it enabled via:
```
aws cloudtrail get-event-selectors --trail-name Trails --query "EventSelectors[*].DataResources[?Type == \`AWS::S3::Object\`].Values" --output text
arn:aws:s3:::
```

I've submitted https://github.com/toniblyx/prowler/pull/405 which is at least working for my issue

**Comment by toniblyx** [comment]
Ok, I'll look at it in detail to make sure I understand it. Thanks

**Comment by deppy** [comment]
Closing this issue as https://github.com/toniblyx/prowler/pull/554 fixed the issue
