### ISSUE TITLE
Filebeat and Prowler

### ISSUE THREAD

**Issue by mark260486** [prowler-cloud/prowler#408]
It seems that after filebeat updated appear a trouble. Can you help with this?
Looks like parse error, but i'm haven't any idea what to do with it. Filebeat 7.4.2

https://pastebin.com/yjPKi7wy

**Comment by toniblyx** [comment]
hey @mark260486, I understand you don't need help here, right?

**Comment by mark260486** [comment]
Yes, @toniblyx , i'm found source of a problem. Thank you for answering :)
