### ISSUE TITLE
Catch error and fail check726 when Support level is insufficient

### ISSUE THREAD

**Issue by ramimac** [prowler-cloud/prowler#414]
Currently, in an account that is both not using trusted advisor, and also lacks an AWS Premium Support Subscription, check726 results in the following error:

> An error occurred (SubscriptionRequiredException) when calling the DescribeTrustedAdvisorChecks operation: AWS Premium Support Subscription is required to use this service.

prowler should catch this error and properly report that Trusted Advisor has not been enabled.

**Comment by toniblyx** [comment]
Thanks @ramimac, you are right, that error should be handle nicer.
