### ISSUE TITLE
New check to find secrets in Auto-scaling Launch configurations user data

### ISSUE THREAD

**Issue by toniblyx** [prowler-cloud/prowler#422]
Same as for ec2 instances but for Launch Configurations.
AUTO SCALING -> Launch Configurations -> user data

**Comment by fredski-github** [comment]
I'll pick this one up @toniblyx

**Comment by toniblyx** [comment]
Cool, look at extra741 as a reference if you want. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toniblyx** [comment]
This one was alredy implemented in extra775 `7.75 [extra775] Find secrets in EC2 Auto Scaling Launch Configuration  - autoscaling [Critical]` and added to `secrets` group.
