### ISSUE TITLE
check3x uses unavailable base64 `--decode` option on busybox

### ISSUE THREAD

**Issue by dbellizzi** [prowler-cloud/prowler#426]
The docker image version of `base64` does not have a `--decode` flag available (instead it uses `-d`).  This means that when using the docker image, all of the check3x checks output:

```[0;34m 3.1 [0;39m [check31] Ensure a log metric filter and alarm exist for unauthorized API calls (Scored)
base64: unrecognized option: decode
BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

Usage: base64 [-d] [FILE]

Base64 encode or decode FILE to standard output
	-d	Decode data
base64: unrecognized option: decode
```

A quick change would be to change `--decode` to `-d`, since GNU coreutils supports both.  But I don't know what other platforms you are supporting (For example, it looks like the built-in supports `--decode` or `-D` (capital D) but not `-d` (lowercase d)

**Comment by toniblyx** [comment]
Thanks for the heads up @dbellizzi. That is supposed to be handled by include/os_detector but for some reason `#!/usr/bin/env bash` is not working fine or doesn't goes though the `if` in `$OSTYPE" == "linux-musl` because `echo $OSTYPE` is empty using `sh` when it should be using `bash`. I'm testing with some changes in `Dockerfile` to see what is the better way to fix it.

**Comment by toniblyx** [comment]
Ok, now I get it. I wasn't looking at the right file here https://github.com/toniblyx/prowler/blob/426/include/check3x#L23 I'll update it to use the right function as in `include/os_detector`.

**Comment by toniblyx** [comment]
Ok, in the last commit it is fixed and the latest image in Docker Hub works fine now. I tested it running Prowler as here: `docker run -ti --rm --name prowler --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN toniblyx/prowler:latest '-c check314'`
