### ISSUE TITLE
Check21 doesn't fail if no trails exist

### ISSUE THREAD

**Issue by nimrodkor** [prowler-cloud/prowler#431]
Check 2.1 requires a CloudTrail trail to be enabled in all regions. The implementation scans existing trails' multi-region configuration - but if no trails are found, it doesn't fail. I think it should fail...

**Comment by toniblyx** [comment]
Thanks @nimrodkor I have added a comment to your PR.

**Comment by toniblyx** [comment]
Merged, thanks @nimrodkor!
