### ISSUE TITLE
Check Extra 726 . Counting not_available trusted advisor outputs as fails

### ISSUE THREAD

**Issue by theOriginalClauBotas** [prowler-cloud/prowler#438]
Trusted advisor output depends on the level support for the account, some checks are not available for some levels of support, when a check is not available the status is not_available, currently the check_extra726 is evaluating ok as PASS, warning as INFO and everything else as FAIL.
not_available is not nessesarily a FAILED result.

**Comment by toniblyx** [comment]
Thanks @theOriginalClauBotas, can you give me more context and examples please? Even better, if you can run `bash -x ./prowler -c extra726` and share the output here would be great. Please clean it up before pasting it here.

**Comment by theOriginalClauBotas** [comment]
Caller Identity:
----------------------------------------------------------------------------------------------------------
|                                            GetCallerIdentity                                           |
+--------------+---------------------------------------------------------------+-------------------------+
|    Account   |                              Arn                              |         UserId          |
+--------------+---------------------------------------------------------------+-------------------------+
DELETED
+--------------+---------------------------------------------------------------+-------------------------+


 7.26 [extra726] Check Trusted Advisor for errors and warnings (Not Scored) (Not part of CIS benchmark) 
       PASS! Trusted Advisor check Low Utilization Amazon EC2 Instances is in state ok
       PASS! Trusted Advisor check Idle Load Balancers is in state ok
       PASS! Trusted Advisor check Underutilized Amazon EBS Volumes is in state ok
       PASS! Trusted Advisor check Unassociated Elastic IP Addresses is in state ok
       PASS! Trusted Advisor check Security Groups - Specific Ports Unrestricted is in state ok
       PASS! Trusted Advisor check Security Groups - Unrestricted Access is in state ok
       PASS! Trusted Advisor check IAM Use is in state ok
       PASS! Trusted Advisor check Amazon S3 Bucket Permissions is in state ok
       PASS! Trusted Advisor check MFA on Root Account is in state ok
       PASS! Trusted Advisor check IAM Password Policy is in state ok
       PASS! Trusted Advisor check Amazon RDS Security Group Access Risk is in state ok
       PASS! Trusted Advisor check Amazon EBS Snapshots is in state ok
       PASS! Trusted Advisor check Amazon EC2 Availability Zone Balance is in state ok
       PASS! Trusted Advisor check Load Balancer Optimization is in state ok
       PASS! Trusted Advisor check VPN Tunnel Redundancy is in state ok
       PASS! Trusted Advisor check High Utilization Amazon EC2 Instances is in state ok
       PASS! Trusted Advisor check Auto Scaling Group Resources is in state ok
       PASS! Trusted Advisor check Amazon RDS Backups is in state ok
       PASS! Trusted Advisor check Amazon RDS Multi-AZ is in state ok
       PASS! Trusted Advisor check Auto Scaling Group Health Check is in state ok
       PASS! Trusted Advisor check Amazon S3 Bucket Logging is in state ok
       PASS! Trusted Advisor check Amazon EBS Provisioned IOPS (SSD) Volume Attachment Configuration is in state ok
       PASS! Trusted Advisor check Large Number of Rules in an EC2 Security Group is in state ok
       PASS! Trusted Advisor check Large Number of EC2 Security Group Rules Applied to an Instance is in state ok
       PASS! Trusted Advisor check Amazon RDS Idle DB Instances is in state ok
       PASS! Trusted Advisor check Amazon Route 53 Alias Resource Record Sets is in state ok
       PASS! Trusted Advisor check Amazon Route 53 Name Server Delegations is in state ok
       PASS! Trusted Advisor check Amazon Route 53 High TTL Resource Record Sets is in state ok
       PASS! Trusted Advisor check Overutilized Amazon EBS Magnetic Volumes is in state ok
       PASS! Trusted Advisor check CloudFront Content Delivery Optimization is in state ok
       PASS! Trusted Advisor check Amazon Route 53 Latency Resource Record Sets is in state ok
       PASS! Trusted Advisor check Amazon Route 53 MX Resource Record Sets and Sender Policy Framework is in state ok
       PASS! Trusted Advisor check Amazon Route 53 Failover Resource Record Sets is in state ok
       PASS! Trusted Advisor check Amazon Route 53 Deleted Health Checks is in state ok
       PASS! Trusted Advisor check AWS CloudTrail Logging is in state ok
       PASS! Trusted Advisor check ELB Listener Security is in state ok
       PASS! Trusted Advisor check ELB Security Groups is in state ok
       PASS! Trusted Advisor check ELB Cross-Zone Load Balancing is in state ok
       PASS! Trusted Advisor check ELB Connection Draining is in state ok
       PASS! Trusted Advisor check CloudFront Header Forwarding and Cache Hit Ratio is in state ok
       PASS! Trusted Advisor check CloudFront Custom SSL Certificates in the IAM Certificate Store is in state ok
       PASS! Trusted Advisor check CloudFront SSL Certificate on the Origin Server is in state ok
       PASS! Trusted Advisor check Amazon EC2 to EBS Throughput Optimization is in state ok
       PASS! Trusted Advisor check CloudFront Alternate Domain Names is in state ok
       PASS! Trusted Advisor check IAM Access Key Rotation is in state ok
       PASS! Trusted Advisor check Exposed Access Keys is in state ok
       PASS! Trusted Advisor check Underutilized Amazon Redshift Clusters is in state ok
       PASS! Trusted Advisor check Amazon EC2 Reserved Instance Lease Expiration is in state ok
       INFO! Trusted Advisor check Amazon S3 Bucket Versioning is in state warning 
       FAIL! Trusted Advisor check AWS Direct Connect Connection Redundancy is in state not_available 
       FAIL! Trusted Advisor check AWS Direct Connect Location Redundancy is in state not_available 
       FAIL! Trusted Advisor check AWS Direct Connect Virtual Interface Redundancy is in state not_available 
       PASS! Trusted Advisor check Amazon Aurora DB Instance Accessibility is in state ok
       FAIL! Trusted Advisor check PV Driver Version for EC2 Windows Instances is in state not_available 
       FAIL! Trusted Advisor check EC2Config Service for EC2 Windows Instances is in state not_available 
       PASS! Trusted Advisor check Amazon EBS Public Snapshots is in state ok
       PASS! Trusted Advisor check Amazon RDS Public Snapshots is in state ok
       PASS! Trusted Advisor check EC2 On-Demand Instances is in state ok
       PASS! Trusted Advisor check SES Daily Sending Quota is in state ok
       PASS! Trusted Advisor check EBS Provisioned IOPS (SSD) Volume Aggregate IOPS is in state ok
       PASS! Trusted Advisor check EBS Provisioned IOPS SSD (io1) Volume Storage is in state ok
       PASS! Trusted Advisor check EBS Active Volumes is in state ok
       PASS! Trusted Advisor check EBS Active Snapshots is in state ok
       PASS! Trusted Advisor check EBS General Purpose SSD (gp2) Volume Storage is in state ok
       PASS! Trusted Advisor check EBS Magnetic (standard) Volume Storage is in state ok
       PASS! Trusted Advisor check EC2 Elastic IP Addresses is in state ok
       PASS! Trusted Advisor check EC2 Reserved Instance Leases is in state ok
       PASS! Trusted Advisor check Kinesis Shards per Region is in state ok
       PASS! Trusted Advisor check CloudFormation Stacks is in state ok
       PASS! Trusted Advisor check Auto Scaling Launch Configurations is in state ok
       PASS! Trusted Advisor check Auto Scaling Groups is in state ok
       PASS! Trusted Advisor check VPC is in state ok
       PASS! Trusted Advisor check VPC Internet Gateways is in state ok
       PASS! Trusted Advisor check VPC Elastic IP Address is in state ok
       PASS! Trusted Advisor check IAM Instance Profiles is in state ok
       PASS! Trusted Advisor check IAM Roles is in state ok
       PASS! Trusted Advisor check IAM Policies is in state ok
       PASS! Trusted Advisor check IAM Users is in state ok
       PASS! Trusted Advisor check IAM Server Certificates is in state ok
       PASS! Trusted Advisor check IAM Group is in state ok
       PASS! Trusted Advisor check ELB Active Classic Load Balancers is in state ok
       PASS! Trusted Advisor check RDS Cluster Roles is in state ok
       PASS! Trusted Advisor check RDS Cluster Parameter Groups is in state ok
       PASS! Trusted Advisor check RDS Clusters is in state ok
       PASS! Trusted Advisor check RDS Reserved Instances is in state ok
       PASS! Trusted Advisor check RDS Subnets per Subnet Group is in state ok
       PASS! Trusted Advisor check RDS Subnet Groups is in state ok
       PASS! Trusted Advisor check RDS Option Groups is in state ok
       PASS! Trusted Advisor check RDS Event Subscriptions is in state ok
       PASS! Trusted Advisor check RDS DB Manual Snapshots is in state ok
       PASS! Trusted Advisor check RDS Total Storage Quota is in state ok
       PASS! Trusted Advisor check RDS DB Parameter Groups is in state ok
       PASS! Trusted Advisor check RDS Read Replicas per Master is in state ok
       PASS! Trusted Advisor check RDS DB Security Groups is in state ok
       PASS! Trusted Advisor check RDS DB Instances is in state ok
       PASS! Trusted Advisor check RDS Max Auths per Security Group is in state ok
       PASS! Trusted Advisor check EBS Throughput Optimized HDD (st1) Volume Storage is in state ok
       PASS! Trusted Advisor check EBS Cold HDD (sc1) Volume Storage is in state ok
       FAIL! Trusted Advisor check DynamoDB Read Capacity is in state not_available 
       PASS! Trusted Advisor check DynamoDB Write Capacity is in state ok
       PASS! Trusted Advisor check Route 53 Max Health Checks is in state ok
       PASS! Trusted Advisor check Route 53 Hosted Zones is in state ok
       PASS! Trusted Advisor check Route 53 Reusable Delegation Sets is in state ok
       PASS! Trusted Advisor check Route 53 Traffic Policies is in state ok
       PASS! Trusted Advisor check Route 53 Traffic Policy Instances is in state ok
       FAIL! Trusted Advisor check ENA Driver Version for EC2 Windows Instances is in state not_available 
       FAIL! Trusted Advisor check NVMe Driver Version for EC2 Windows Instances is in state not_available 
       FAIL! Trusted Advisor check Amazon EC2 Reserved Instances Optimization is in state not_available 
       FAIL! Trusted Advisor check Service Limits is in state not_available

**Comment by theOriginalClauBotas** [comment]
Seems that an else if is missing

**Comment by toniblyx** [comment]
I needed it with `bash -x ` to get the entire trace, could you send a PR with the fix?

**Comment by theOriginalClauBotas** [comment]
Sorry, what is a PR?
...
Something like


    if [[ $(echo $QUERY_TA_CHECK_RESULT | grep ok ) ]]; then
      textPass "Trusted Advisor check $TA_CHECKS_NAME is in state $QUERY_TA_CHECK_RESULT"
    elif [[ $(echo $QUERY_TA_CHECK_RESULT | grep warning) ]]; then
      textInfo "Trusted Advisor check $TA_CHECKS_NAME is in state $QUERY_TA_CHECK_RESULT"
    elif [[ $(echo $QUERY_TA_CHECK_RESULT | grep not_available) ]]; then
      textInfo "Trusted Advisor check $TA_CHECKS_NAME is in state $QUERY_TA_CHECK_RESULT"
    else
      textFail "Trusted Advisor check $TA_CHECKS_NAME is in state $QUERY_TA_CHECK_RESULT"
    fi

**Comment by toniblyx** [comment]
It is a Pull Request of a change in the code. I can test your piece of code and do it for you. Thanks!! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by theOriginalClauBotas** [comment]
Yes, please.
