### ISSUE TITLE
2.8 Warning issued for aws/acm master key

### ISSUE THREAD

**Issue by jacobcsmith** [prowler-cloud/prowler#44]
First off thank you for this invaluable tool.

After running the report with the correct permissions I noticed a warning related to the aws/acm key not being set to rotate under section 2.8. The aws/acm key (http://docs.aws.amazon.com/acm/latest/userguide/kms.html) is actually a default master key and should not be checked for rotation. From the prowler output I noticed an AccessDenied error when checking the key rotation status of this key. I have other default master keys in my account and do not receive a permissions error when checking the key rotation status. Not sure why this key is setup differently.

I think this false positive could be avoided if key rotation status is only checked for non-default master keys.

**Comment by toniblyx** [comment]
I agree with you @jacobcsmith and thanks for reporting it. Do you think it may be good idea to leave a message in the 2.8 output besides removing it as positive?

**Comment by jacobcsmith** [comment]
Thanks for the fast response @toniblyx.
 
I think that message could be useful for informational or debugging purposes but may be better as a log message. I don't think they belong as items for 2.8 "Ensure rotation for **customer** created CMKs is enabled" for two reasons: 
1) These default master keys are created by AWS and not by the "customer" (although technically owned by the customer AWS account).
2) The key rotation status is not editable by a customer so there is no need to check it and nothing for us to do.

With that said it wouldn't bother me if the message was included in the output.

**Comment by toniblyx** [comment]
Working on this one too. It will be ready probably at the end of the day. Fingers crossed though :D

**Comment by toniblyx** [comment]
fixed in PR #51
