### ISSUE TITLE
Can't produce file report output 

### ISSUE THREAD

**Issue by saryx123** [prowler-cloud/prowler#451]
Can't produce file report output with prowler to save my dear life. Absolutely positive that i'm missing something obvious but just cant figure out what.

Running the following only results in terminal text output, I need something file based via format I can aggregate and report on.
./prowler -p prod -e -b -s -x /root/cloudtools/prowler/reports/

Any advice?

**Comment by toniblyx** [comment]
Hello @saryx123, thanks for using Prowler.
I think you are using the wrong options to generate a report. To get a standard report of an account called in your profile "prod" you can just run `./prowler -p prod -e -b -s` (that will run the CIS checks only without showing the banner and with the scoring report at the end). Option `-x /directory/` is to include external checks, it has nothing to do with where to store the report. You can just run something like `./prowler -p prod -e -b -s -M mono > prowler-report.txt` or see https://github.com/toniblyx/prowler#usage for more options.

**Comment by saryx123** [comment]
Great.

It was the -M flag.

Thanks.
