### ISSUE TITLE
check_extra720 not considering that the lambda trail can be in a different region

### ISSUE THREAD

**Issue by theOriginalClauBotas** [prowler-cloud/prowler#455]
check_extra720 fails when lambda and trail are in different regions, but technically the trail can be in a different region where lambda is and trail can record lambda api operations anyway.

**Comment by zfLQ2qx2** [comment]
Right - I just turned on AWS organizations and am in the same boat. I think the logic should be if any cloudtrail in account w/ multi-region enabled and configured to log lambda api operations or a local trail configured to log lambda api operations. I think I can implement that.

Particularly in the case of organizations I think there will be several checks that Prowler does that will fail unless done in the master account. I think the logic there is to skip checking organization  trails unless its the master account - but I need to verify I can't create an organization trail in the member accounts first.

**Comment by toniblyx** [comment]
This one was fixed already.
