### ISSUE TITLE
check_extra720

### ISSUE THREAD

**Issue by zfLQ2qx2** [prowler-cloud/prowler#465]
@toniblyx What are the remediation steps for check_extra720? I see what commands the check is running, but I'm unsure what makes a function's name appear there.

**Comment by toniblyx** [comment]
You can find information about that here https://aws.amazon.com/blogs/mt/gain-visibility-into-the-execution-of-your-aws-lambda-functions-with-aws-cloudtrail/

**Comment by toniblyx** [comment]
hey @zfLQ2qx2 feel free to reopen this issue if you need more info
