### ISSUE TITLE
check_extra768

### ISSUE THREAD

**Issue by rkalamaro** [prowler-cloud/prowler#466]
ERROR! python library detect-secrets not found. Make sure it is installed correctly and in your $PATH: syntax error in expression (error token is "! python library detect-secrets not found. Make sure it is installed correctly and in your $PATH")

**Comment by toniblyx** [comment]
Hi @rkalamaro, could you please give more context on what you were doing and how? Did you follow install instructions? https://github.com/toniblyx/prowler#requirements-and-installation. It seems like you didn't install `detect-secrets` with `pip` or maybe `pip3`?

**Comment by toniblyx** [comment]
@rkalamaro feel free to reopen this issue if you can provide more information. Thanks.
