### ISSUE TITLE
SecurityAudit policy outdated for check extra769

### ISSUE THREAD

**Issue by spookerlabs** [prowler-cloud/prowler#468]
Since suggested privileges are based on arn:aws:iam::aws:policy/SecurityAudit and last update was 2019-10-15 18:02 UTC-0300, this policy doesn't have any action to access-analyzer and probably missing much other new actions since last update.

That being said when you run this check with SecurityAudit privileges only it won't work

<img width="1481" alt="image" src="https://user-images.githubusercontent.com/11694775/73478385-bcbd2080-4374-11ea-8055-9df0a7d059f0.png">

Thanks

**Comment by toniblyx** [comment]
As we discussed offline you need to attach https://github.com/toniblyx/prowler/blob/master/iam/prowler-additions-policy.json to the role to make sure it works fine with all existing checks. I'm going to improve documentation based on your feedback. Thanks!
