### ISSUE TITLE
check13 - only checks aged passwords and not Access keys

### ISSUE THREAD

**Issue by angabini** [prowler-cloud/prowler#469]
The check13's premise is to _"Ensure credentials unused for 90 days or greater are disabled (Scored)"_. Though, it only checks and reports **passwords** older than 90 days, and not Access keys (which are also credentials).

Is this intended? If not, happy to add checking for the access keys into it.

**Comment by toniblyx** [comment]
Hi @angabini, in this particular case that's what CIS mandates for. I agree that access keys are also credentials, however this check it is for user/password for console access. It may need a new  extra check for access keys or enhance this one.

**Comment by angabini** [comment]
makes sense, thanks @toniblyx .
