### ISSUE TITLE
Check Extra774 checking account creation date instead of last logon date.

### ISSUE THREAD

**Issue by TopherIsSwell** [prowler-cloud/prowler#490]
Extra774 checks for console login accounts that haven't logged in for 30+ days. But currently the logic is flagging users that haven't been created in the last thirty days.

The check is looking for the date in the 3rd field of the report, but that's the account creation date. it should be the 5th field, which is the "password last used" field.

Pull request for this issue:
https://github.com/toniblyx/prowler/pull/489

**Comment by gliptak** [comment]
https://github.com/toniblyx/prowler/pull/489 was merged. Can this be closed?
