### ISSUE TITLE
-E flag causes report to be incorrectly ordered.

### ISSUE THREAD

**Issue by QuantumBJump** [prowler-cloud/prowler#492]
When running Prowler with the -E flag to exclude certain checks, the report generated is incorrectly ordered numerically, rather than in the order defined by the CIS. This means that, for instance, the result of check 1.10 is reported immediately after check 1.1, instead of after 1.9 as it should be.

**Comment by toniblyx** [comment]
Thanks @QuinnStevens, you can use option `-n` to get the behavior you are looking for. Let me know if it does it to close the issue or go ahead with debugging.

**Comment by QuantumBJump** [comment]
No, using -n does make 1.1 appear as '1.01', but the text output is still ordered 1.01, 1.10, 1.11......1.19, 1.02, 1.20

**Comment by QuantumBJump** [comment]
To give a more explicit example, here are the first few checks from a recent run of Prowler (I've left out the actual results but this is the order the checks were run in):

```
1.1  [check11] Avoid the use of the root account (Scored)
1.10 [check110] Ensure IAM password policy prevents password reuse: 24 or greater (Scored)
1.11 [check111] Ensure IAM password policy expires passwords within 90 days or less (Scored)
1.12 [check112] Ensure no root account access key exists (Scored)
1.13 [check113] Ensure MFA is enabled for the root account (Scored)
1.14 [check114] Ensure hardware MFA is enabled for the root account (Scored)
1.15 [check115] Ensure security questions are registered in the AWS account (Not Scored)
1.16 [check116] Ensure IAM policies are attached only to groups or roles (Scored)
1.17 [check117] Maintain current contact details (Not Scored)
1.18 [check118] Ensure security contact information is registered (Not Scored)
1.19 [check119] Ensure IAM instance roles are used for AWS resource access from instances (Not Scored)
1.2  [check12] Ensure multi-factor authentication is enabled for all IAM users that have a console password (Scored)
1.20 [check120] Ensure a support role has been created to manage incidents with AWS Support (Scored)
1.21 [check121] Do not setup access keys during initial user setup for all IAM users that have a console password (Not Scored)
1.22 [check122] Ensure IAM policies that allow full "*:*" administrative privileges are not created (Scored)
1.3  [check13] Ensure credentials unused for 90 days or greater are disabled (Scored)
1.4  [check14] Ensure access keys are rotated every 90 days or less (Scored)
```

**Comment by toniblyx** [comment]
Can you please share exactly what command are you using? when I run `./prowler -g group1 -E check111` I get the right order

**Comment by QuantumBJump** [comment]
The exact command I use is `./prowler -E extra79,extra712` - so no -g argument, it runs all the tests except those two.

**Comment by toniblyx** [comment]
ok, now I can see what you say.
