### ISSUE TITLE
Correct check13

### ISSUE THREAD

**Issue by lanhhuyet510** [prowler-cloud/prowler#496]
From CIS:
2. For each user having password_enabled set to ` TRUE ` , ensure
` password_last_used_date ` is less than 90 days ago.

- When password_enabled is set to `TRUE`  and `password_last_used` is set to
`No_Information` , ensure `password_last_changed` is less than 90 days ago.
3. For each user having an `access_key_1_active` or `access_key_2_active` to `TRUE` ,
ensure the corresponding `access_key_n_last_used_date` is less than 90 days ago.
- When a user having an `access_key_x_active` (where x is 1 or 2) to `TRUE` and
corresponding `access_key_x_last_used_date` is set to `N/A`,
ensure `access_key_x_last_rotated` is less than 90 days ago.

Current check13: ``` # Only check Password last used for users with password enabled (2) ```

**Comment by marcjay** [comment]
I took a look at this and also at extra774 for PR #538. It does seem like [check13](https://github.com/toniblyx/prowler/blob/master/checks/check13) and [extra774](https://github.com/toniblyx/prowler/blob/master/checks/check_extra774) are trying to check the same thing, just against different timescales (90 days vs 30 days respectively), but without sharing any common code. At the same time, it does seem like check13 should, according to the benchmarks, check that the last_used_date on Access Keys 1 and 2 are within 90 days.

Could I propose a few things to @toniblyx and if he agrees, I'm happy to raise a PR to achieve them:
- Create an `include/check_creds_last_used` file that contains a single check that:
    - Takes a `$1` parameter referred to as `MAX_DAYS` 
    - If `password_enabled` is true, checks if the `password_last_used_date` is more recent than MAX_DAYS days ago
    - If `password_enabled` and `password_last_used_date` is 'no_information' (taking the approach from #538), ensure that `password_last_changed` is less than MAX_DAYS days ago
    - If `access_key_1_active` or `access_key_2_active` is true, ensure the corresponding `access_key_n_last_used_date` is less than MAX_DAYS days ago
    - If `access_key_1_active` or `access_key_2_active` is true and
the corresponding `access_key_x_last_used_date` is set to `N/A`,
ensure `access_key_x_last_rotated` is less than MAX_DAYS days ago.
- Modify `check13` to essentially just read: `check13() { check_creds_last_used 90 }`
- Modify `extra774` to essentially just read: `extra774() { check_creds_last_used 30 }` (I would cancel #538 and incorporate those changes to the common function)

That would add access key checking to both checks - which definitely seems right for 1.3 as it's in the benchmarks, and seems like a reasonable addition to 7.74, assuming the original intention of this check was to be the same as the CIS benchmark, just with a stricter time window. Perhaps @jonnyCodev could confirm, as the check's author

**Comment by marcjay** [comment]
Do you think the above sounds reasonable @toniblyx? If so I'm happy to raise a PR for it.

**Comment by toniblyx** [comment]
Looks good to me. As we add more new and enhanced checks, CIS checks will become a bit obsolete or redundant eventually but it is good to keep them (and improve them when needed) to keep backward compatibility. If you have time to do it, would be great, I'd like to review and merge the white/blacklist feature also this week and try to cut off for v2.3 before Friday. Thank you both!
