### ISSUE TITLE
Any Roadmap for PCI DSS Compliance checklist ?

### ISSUE THREAD

**Issue by muharihar** [prowler-cloud/prowler#500]
Hi team...

Any roadmap for new feature to check/audit PCI DSS Compliance checklist ?

References:
- https://aws.amazon.com/blogs/security/how-to-use-the-aws-security-hub-pci-dss-v3-2-1-standard/

Thanks

**Comment by toniblyx** [comment]
hey @muharihar, indeed! Look at the public roadmap here https://github.com/toniblyx/prowler/projects/3 (PCI it is already in the To do column)

**Comment by muharihar** [comment]
already on the public roadmap:

https://github.com/toniblyx/prowler/issues/296
