### ISSUE TITLE
[Error]  Failed conversion ... in 7.74 [extra774] Check if user have unused console login 

### ISSUE THREAD

**Issue by muharihar** [prowler-cloud/prowler#501]
Hi team,

We got this error, kindly please check:

```
7.74 [extra774] Check if user have unused console login 
       PASS! User *************** has used console login in the past 30 days
Failed conversion of ``no_information'' using format ``%Y-%m-%d''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```

Thank you

**Comment by toniblyx** [comment]
Hi @muharihar, what Operating System are you using?

**Comment by muharihar** [comment]
> Hi @muharihar, what Operating System are you using?

Hi @toniblyx,

i'm using Mac OS (10.14.6)

Thank you

**Comment by toniblyx** [comment]
Can you please try with the latest version of code from the master branch? If it still fails please share the output of `bash -x ./prowler -c extra774` here but fake up or remove sensitive data. Thanks.

**Comment by grayaii** [comment]
I also get this error, both on linux and mac.
Here is the output:

    + for i in '$LIST_USERS_WITH_PASSWORD_ENABLED'
    ++ cat /var/folders/86/wf80z6hs2g3d4z6clc0zhchc0000gn/T/prowler.cred_report-XXXXXX.sOlpgavB
    ++ awk -F, '{ print $1,$5 }'
    ++ grep '^sbokul '
    ++ awk '{ print $1 }'
    + user=sbokul
    ++ cat /var/folders/86/wf80z6hs2g3d4z6clc0zhchc0000gn/T/prowler.cred_report-XXXXXX.sOlpgavB
    ++ grep '^sbokul '
    ++ awk -F, '{ print $1,$5 }'
    ++ awk '{ print $2 }'
    + last_login_date=no_information
    ++ how_many_days_from_today no_information
    ++ DATE_TO_COMPARE=no_information
    +++ date +%s
    ++ TODAY_IN_DAYS=1586566415
    +++ date -jf %Y-%m-%d no_information +%s
    Failed conversion of ``no_information'' using format ``%Y-%m-%d''
    date: illegal time format
    usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
                [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
    ++ DATE_IN_DAYS=
    ++ DAYS_TO=-18363
    ++ echo -18363

**Comment by grayaii** [comment]
I cat'ed out the report file and it contains the **no_information** string.
Here is one with a normal user, and that troublesome user:

    sbokul,arn:aws:iam::123456789:user/sbokul,2019-09-17T17:35:12+00:00,true,no_information,2019-09-17T17:35:13+00:00,N/A,false,false,N/A,N/A,N/A,N/A,false,N/A,N/A,N/A,N/A,false,N/A,false,N/A
    sbradley,arn:aws:iam::123456789:user/sbradley,2019-01-25T14:20:56+00:00,false,N/A,N/A,N/A,false,false,N/A,N/A,N/A,N/A,false,N/A,N/A,N/A,N/A,false,N/A,false,N/A

Oh, and BTW, that **no_information** is coming from:

    aws iam get-credential-report --query Content --output text --region us-east-1 | base64 -d

BTW, I love how easy you made it debug prowler issues!!

**Comment by marcjay** [comment]
If you'd like to test a fix for this, feel free to try the `fix-no-information-extra774-501` branch from #538

**Comment by grayaii** [comment]
@marcjay It works like a charm!!!! thank you so much!!!

**Comment by muharihar** [comment]
Awesome @marcjay!

It works on my mac! 

Thanks you!!!

**Comment by muharihar** [comment]
@toniblyx,

Kindly please check and review the PR from @marcjay. 

https://github.com/toniblyx/prowler/pull/538

Thank you
