### ISSUE TITLE
Prowles does not return Groups and Checks definitions using csv and json formats

### ISSUE THREAD

**Issue by sadon** [prowler-cloud/prowler#503]
Groups and Checks definitions are working option for  **-M mono** flag and at default output.

In details:
**Groups definition**
```
./prowler -L -M mono -b
<list of Groups>
```
But:
```
./prowler -L -M json -b
<empty>
./prowler -L -M csv -b
<empty>
```

**Checks definition**
Does not work json format 
```
 ./prowler -l -M json -b
<empty>
```

**Comment by toniblyx** [comment]
As I said in your other issue #504, options `-L` or `-l` don't execute any check, they only list existing groups of checks respectively.

**Comment by sadon** [comment]
@toniblyx exactly, I want to list all available checks without real scanning, but prowler return the empty  value.

**Comment by toniblyx** [comment]
To list available checks `./prowler -l`, to list available groups `./prowler -L`. Feel free to reopen this case if you need further information.
