### ISSUE TITLE
Check 7.74 [extra774] has strange order

### ISSUE THREAD

**Issue by sadon** [prowler-cloud/prowler#505]
In all output options extra774 has order:
afrer all Group1 Checks:
and in 7 Group itself
Ex:
 ./prowler -l -M csv -b
```
1.20 [check120] Ensure a support role has been created to manage incidents with AWS Support (Scored)
1.21 [check121] Do not setup access keys during initial user setup for all IAM users that have a console password (Not Scored)
1.22 [check122] Ensure IAM policies that allow full "*:*" administrative privileges are not created (Scored)
7.74 [extra774] Check if user have unused console login
2.1 [check21] Ensure CloudTrail is enabled in all regions (Scored)
2.2 [check22] Ensure CloudTrail log file validation is enabled (Scored)
2.3 [check23] Ensure the S3 bucket CloudTrail logs to is not publicly accessible (Scored)
2.4 [check24] Ensure CloudTrail trails are integrated with CloudWatch Logs (Scored)

```
...
```
7.73 [extra773] Check if CloudFront distributions are using WAF (Not Scored) (Not part of CIS benchmark)
7.74 [extra774] Check if user have unused console login
7.75 [extra775] Find secrets in EC2 Auto Scaling Launch Configuration (Not Scored) (Not part of CIS benchmark)

```

**Comment by toniblyx** [comment]
I don't get what you do mean, can you confirm what actual command are you executing? Command `./prowler -l -M csv -b` won't execute anything but listing available checks.

**Comment by sadon** [comment]
hi @toniblyx  I use './prowler -l -M csv -b' command to list all available checks.
And got the above listing. 
Check: right after **1.22** prowler wrote **7.74**, and next **2.1**

I found it strange...

**Comment by toniblyx** [comment]
Option `-l` is to use it stand alone not along with any other parameter. If you want to list all avalable checks `./prowler -l`  and if you want to run Prowler and get a csv output without the banner `./prowler -M csv -b`.

**Comment by sadon** [comment]
@toniblyx I'm focused not on CLI options at all,
I am focusing on the wrong order in prowler listing.

please  take a look http://joxi.ru/L21ZEeyHgVOx8A

**Comment by toniblyx** [comment]
If you look at group1 `groups/group1_iam`, `extra774` is included in that group, that is why you see it there. Feel free to create your own groups if needed.

Please, reopen this issue if you need anything else in this regard.
