### ISSUE TITLE
Server Access logging in s3 log buckets

### ISSUE THREAD

**Issue by QuantumBJump** [prowler-cloud/prowler#506]
Extra test 7.18 checks to see if s3 buckets have server access logging enabled. I've set up logging in most of our s3 buckets, however the check is still failing on the buckets I'm actually storing all the logs in. Is it safe for those buckets to log server access, or would that lead to an infinite regression of logging the logging of the log... etc?

If I can turn logging on for those buckets, can they log to themselves? Or should they log to a different bucket.

**Comment by QuantumBJump** [comment]
Upon further research, it looks like logging the access to the buckets where the logs are actually being stored is discouraged. Is there a way to disable this check for specific buckets?

**Comment by toniblyx** [comment]
Can you please share where did you find that recommendation?

**Comment by rkane2002** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/s3-server-access-logs-same-bucket/

**Comment by toniblyx** [comment]
Awesome thanks for sharing that @rkane2002, @QuinnStevens  this is a good example of use case for whitelist support in Prowler. There is PR about that here https://github.com/toniblyx/prowler/pull/514 I need to test it and make it work with all new changes made. What do you think about that implementation?

**Comment by QuantumBJump** [comment]
Hey Toni! That looks perfect for our purposes! I do have one comment but I'll voice that on the discussion of the PR itself.

**Comment by QuantumBJump** [comment]
This has been fixed by the addition of the whitelist support in #514 so I'm closing.
