### ISSUE TITLE
check121 does not first check if a user has console access

### ISSUE THREAD

**Issue by dnorth98** [prowler-cloud/prowler#513]
check121 (Do not setup access keys during initial user setup for all IAM users that have a console password)

When running, this check flagged 2 keys that were assigned to users that had never been used.  However, these users do not have a console password/login (Console Password == disabled) 

Probably should check that the console password is enabled as well as the keys existing.

**Comment by toniblyx** [comment]
Thanks @dnorth98, that is what it is meant to do... can you please share a sample/fake credentials report with your case that I could test?

**Comment by dnorth98** [comment]
Sure thing.  Probably the easiest thing is here's a screen shot of one of the users that reported a violation and below the report snippet for this user.  You'll see it has console access disabled.

![image](https://user-images.githubusercontent.com/6616703/76416797-210ad100-6372-11ea-927b-cf591c081480.png)

```
 0.1 Generating AWS IAM Credential Report...

 1.21 [check121] Do not setup access keys during initial user setup for all IAM users that have a console password (Not Scored)
       FAIL! service_github_actions has never used Access Key 1
       PASS! No users found with Access Key 2 never used
```

**Comment by dnorth98** [comment]
Ah I took a look at the code for this check and it doesn't filter only users that have a console login - it's looking at all users.  However, there doesn't appear to be a way in the IAM calls to filter users that have a console login.  The best I could find is a field that comes back for the user called `PasswordLastUsed`.  This won't be present for users that don't have a password/console login.

Something like this would filter only users who have a `PasswordLastUsers` field present

`aws iam list-users --query 'Users[?PasswordLastUsed!=null]'`
