### ISSUE TITLE
Enhance accuracy of extra75 find used security groups in other resources eventually in use othan EC2

### ISSUE THREAD

**Issue by dougbyrne** [prowler-cloud/prowler#516]
Hi, check extra75 is meant to list security groups that are not being used. However, it's listing some security groups that are being used. These are the cases I've found:
 * security groups used by application load balancers The CLI can return the list of security groups in use: `aws elbv2 describe-load-balancers --region us-east-1 | jq '.LoadBalancers[].SecurityGroups[]' -r | sort | uniq` but I'm not sure if that's the best way to check.
 * SGs attached to stopped instances
 * SGs used by AKS cluster
 * SGs used by a auto-scaling launch profile or launch configuration when the ASG is at 0 instances. This might be technically correct.

**Comment by toniblyx** [comment]
Hi @dougbyrne, thanks for your comment. If you look at the code, it looks for Security Groups with an actual NetworkInterface attached, therefore SG that are being used, not SG that can be used or are configured somewhere. For the cases you are mentioning I think it is more about configuration to eventually use those SG, am I correct? In that case, should that be a new check or an improvement for this one? I think that could be an improvement for this one. Thoughts?

**Comment by dougbyrne** [comment]
Hi, I reran this check and could only reproduce the SGs that are attached to an ASG that's currently at 0 instances, so I'll focus on that.

For me, this information is only useful if it is actionable. I think that the only action here is to delete security groups that are not in use. If the security group would be used by an ASG, then I can't delete it. If I can't delete, there is no action to take, and I don't think it should be listed here.

ASGs have two ways to define a spec, Launch Configurations and Launch Templates. To get a list of SGs, you might do something like this: 
For Launch Configurations:
```
aws autoscaling describe-launch-configurations --query "LaunchConfigurations[].SecurityGroups" --output text | sort | uniq
```
For Launch Templates:
```
aws ec2 describe-launch-templates  --query "LaunchTemplates[].LaunchTemplateId" --output text | xargs -n 1 aws ec2 describe-launch-template-versions --filters Name=is-default-version,Values=true --query "LaunchTemplateVersions[0].LaunchTemplateData.NetworkInterfaces[].Groups[]" --output text --launch-template-id | tr "\t" "\n" | grep -v "None" | sort | uniq
```

**Comment by toniblyx** [comment]
I get it and makes sense to keep those security groups in, let's say, "stand-by" mode and not make any action with. I will tag this ticket as an enhancement and change title accordingly.

**Comment by nosoulqq** [comment]
Same issue for Lambda in VPC. If your functions are not active for a long period of time, Lambda reclaims its network interfaces, and the function becomes Idle.
It is also important to note that an unused security group created by Cloudformation, if removed manually, can cause environmental inconsistencies.

**Comment by toniblyx** [comment]
good point, I'll take that into account

**Comment by toniblyx** [comment]
Ok, this has to be enhanced making it more comprehensive by looking for security grous attached to:
- ELB/ALBs
- EC2 stopped instances
- EKS clusters
- Auto-scaling launch profile or launch configuration when the ASG is at 0 instances.
- What else?

**Comment by robdew** [comment]
If a security group is used as a Source in another security group rule, it will also not show up as "used" by extra75.

**Comment by n4ch04** [comment]
Hi @dougbyrne we have been reviewing this, and as to cover all the related services in order to ensure the SGs are being used or not implies to reformulate the whole control  we will include it as new feature, to be developed in the future

**Comment by n4ch04** [comment]
Closing it
