### ISSUE TITLE
All CIS 3.X Checks Fail with ./include/check3x: line 18: jq: command not found

### ISSUE THREAD

**Issue by kdustin117** [prowler-cloud/prowler#517]
Other checks complete perfectly but when I try to run any 3.x check it fails with the following code:
./include/check3x: line 18: jq: command not found

**Comment by kdustin117** [comment]
resolved

**Comment by amanludhwaniatgithub** [comment]
How did you resolve it?

**Comment by toniblyx** [comment]
depending on your operating system you have to install `jq` with: `brew install jq` for Mac, `apt-get install jq` or `yum install jq` for Debian/Ubuntu or Redhat/Centos/Fedora. More details here https://github.com/toniblyx/prowler#requirements-and-installation
