### ISSUE TITLE
check32 is checking for MFA signed in instead of non-MFA signed in metric filter

### ISSUE THREAD

**Issue by manh-vnguyen** [prowler-cloud/prowler#523]
Compliance: Ensure a log metric filter and alarm exist for Management Console sign-in without MFA
But I can see the code is checking for logs that contain MFAUsed to be "Yes" instead of "No"
https://github.com/toniblyx/prowler/blob/master/checks/check32

`check32(){
  check3x '\$\.eventName\s*=\s*"ConsoleLogin".+\$\.additionalEventData\.MFAUsed\s*!=\s*"Yes"'
}`

Should be like this?

`check32(){
  check3x '\$\.eventName\s*=\s*"ConsoleLogin".+\$\.additionalEventData\.MFAUsed\s*!=\s*"No"'
}`

The reference I'm using: https://www.cloudconformity.com/knowledge-base/aws/CloudWatchLogs/console-sign-in-without-mfa.html

**Comment by toniblyx** [comment]
If without is yes means that MFA is not used then it is a FAIL because MFA should be used. Are you experiencing different behavior?

**Comment by manh-vnguyen** [comment]
Sorry Toni, my bad!
I'd mistaken the the operator "!=" with "=", my configuration is = "No" so it fails the check, but do you think it'd still make a valid configuration?

**Comment by toniblyx** [comment]
Refer to page 92 on https://d0.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf
