### ISSUE TITLE
check26 is passing the bucket access logging check even when it's not configured

### ISSUE THREAD

**Issue by manh-vnguyen** [prowler-cloud/prowler#525]
The script to check bucket access logging:

`
CLOUDTRAILBUCKET_LOGENABLED=$($AWSCLI s3api get-bucket-logging --bucket $bucket $PROFILE_OPT --region $REGION --query 'LoggingEnabled.TargetBucket' --output text 2>&1)
          if [[ $(echo "$CLOUDTRAILBUCKET_LOGENABLED" | grep AccessDenied) ]]; then
            textFail "Access Denied Trying to Get Bucket Logging for $bucket"
            continue
          fi
          if [[ $CLOUDTRAILBUCKET_LOGENABLED != "null" ]]; then
            textPass "Bucket access logging enabled in CloudTrail S3 bucket $bucket for $trail"
          else
            textFail "Bucket access logging is not enabled in CloudTrail S3 bucket $bucket for $trail"
          fi
`

So I tried to run this command customize to my bucket 

`
CLOUDTRAILBUCKET_LOGENABLED=$($AWSCLI s3api get-bucket-logging --bucket $bucket $PROFILE_OPT --region $REGION --query 'LoggingEnabled.TargetBucket' --output text 2>&1)
`

The output CLOUDTRAILBUCKET_LOGENABLED for a non-configured access logging bucket is "None" instead of "null" which is how the check is being conducted:

`
          if [[ $CLOUDTRAILBUCKET_LOGENABLED != "null" ]]; then
           textPass "Bucket access logging enabled in CloudTrail S3 bucket $bucket for $trail"
          else
            textFail "Bucket access logging is not enabled in CloudTrail S3 bucket $bucket for $trail"
          fi
`

Is this because aws cli output has been updated?

**Comment by toniblyx** [comment]
Make sure you are using the latest AWS CLI v1 (awscli-1.18.31). Using `--output text` gives you `None`, if you don't use `text` you will get a `null`. Prowler is not tested with AWS CLI v2 so it probably won't work. You can use the docker version of prowler to make it run without problems. See the README for sample commands.

**Comment by manh-vnguyen** [comment]
Thanks @toniblyx
