### ISSUE TITLE
Option to Pass External ID When assuming roles with -A - R

### ISSUE THREAD

**Issue by JBarnes94** [prowler-cloud/prowler#528]
While there is the possibility to assume roles with -A and -R there is no ability to pass an external ID with the requests. 

As such it means if the role requires an external ID you need to add it to the CLI Config file. 
Which can be more difficult when running in situation similar to this, when the accounts to be scanned may change frequently 

https://aws.amazon.com/blogs/security/use-aws-fargate-prowler-send-security-configuration-findings-about-aws-services-security-hub/

I believe this could be achieved by adding a new optional argument to prowler to accept the External ID. 

` I )
        ROLE_EXTERNAL_ID=$OPTARG`

And then add an conditional statement to check for its presences in includes/assume_role

Something Like 

 ```
 if [[ -z $ROLE_EXTERNAL_ID ]]; then
        # assume role command
        $AWSCLI $PROFILE_OPT sts assume-role --role-arn arn:aws:iam::$ACCOUNT_TO_ASSUME:role/$ROLE_TO_ASSUME \
            --role-session-name ProwlerAssessmentSession \
            --duration-seconds $SESSION_DURATION_TO_ASSUME > $TEMP_STS_ASSUMED_FILE 
    else 
        $AWSCLI $PROFILE_OPT sts assume-role --role-arn arn:aws:iam::$ACCOUNT_TO_ASSUME:role/$ROLE_TO_ASSUME \
        --role-session-name ProwlerAssessmentSession \
        --duration-seconds $SESSION_DURATION_TO_ASSUME \
        --external-id $ROLE_EXTERNAL_ID > $TEMP_STS_ASSUMED_FILE 
    fi 
```

**Comment by toniblyx** [comment]
Hi @JBarnes94, thanks for the idea, it makes a lot of sense, I thought about it when I added this feature but didn't know if it was going to be used or not, now that I see it, it is time to add what you are asking. Please feel free to send a PR if you have it done and tested already.

**Comment by toniblyx** [comment]
Hey @JBarnes94  your pull request has been merged already, I only made a mistake... resolving conflicts in Github is not my thing... I appreciate your help!
