### ISSUE TITLE
'AuthFailure' error while executing Prowler when providing AWS GovCloud credentials as environment variables.

### ISSUE THREAD

**Issue by MayankRathore4** [prowler-cloud/prowler#533]
Hi,

I'm trying to execute Prowler with my AWS GovCloud credentials. I've set the credentials as environment variables.

Following is the output of the command `./prowler -c check13`
<img width="1292" alt="Screen Shot 2020-04-09 at 10 43 06 AM" src="https://user-images.githubusercontent.com/37398954/78860380-b40d5880-7a4f-11ea-97b8-819826b4939b.png">

FYI:
* Getting no such issue when setting these GovCloud credentials using `aws configure`.
* Getting no such issue when using non-GovCloud (AWS commercial account) credentials as environment variables.

My actual use-case is executing the Prowler inside a docker container, that's the reason I need these credentials to be set as the environment variables.

**Comment by toniblyx** [comment]
Can you try with -r <region> using the govcloud region? Seems like you are running it against us-east-1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MayankRathore4** [comment]
Thanks @toniblyx. It resolved my issue.
