### ISSUE TITLE
Running prowler on Mac, I get an error: date: invalid option -- 'j'

### ISSUE THREAD

**Issue by grayaii** [prowler-cloud/prowler#534]
I just git clon'ed prowler on a mac.
The exact git hash that I have is 8f83da985a7ba129317fa2716583f1181bfc4686, which it current head of master.

Any invocation of prowler gives me this message:

`date: invalid option -- 'j'`

The version of date that I have is:

```
$ date --version
date (GNU coreutils) 8.31
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
```

This also happens on prowler version 2.2.0

**Comment by grayaii** [comment]
Note: If I use the non-GNU date program, that is installed by default on a mac, it works.
In other words, if I use /usr/date, it works.  If I use the GNU date, which is installed from `brew install coretools`, it does not work.

I have an acceptable workaround, but it would be nice if prower was not dependent on what version of date you have installed.

**Comment by jonathanbglass** [comment]
Providing output from latest Prowler on a Mac

```
 2.4  [check24] Ensure CloudTrail trails are integrated with CloudWatch Logs (Scored)
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
./include/os_detector: line 75: (1586549445 -  )/60/60/24: syntax error: operand expected (error token is ")/60/60/24")
```

**Comment by marcjay** [comment]
If you'd like to test a fix for this, feel free to try the handle-gnu-date-as-default-on-mac-osx-534 branch from #539

**Comment by grayaii** [comment]
Thanks @marcjay It works like a charm!!!
