### ISSUE TITLE
extra741: not in gzip format

### ISSUE THREAD

**Issue by grayaii** [prowler-cloud/prowler#535]
On Prowler 2.2.0, I get this error when running extra741:
```
 7.41 [extra741] Find secrets in EC2 User Data (Not Scored) (Not part of CIS benchmark)
       INFO! Looking for secrets in EC2 User Data in instances across all regions... (max 100 instances per region use -m to increase it)
gunzip: ./secrets-XXX/extra741-i-0ebe9f469a9bdefe5-userData.decoded.gz: not in gzip format
detect-secrets: ./secrets-XXX/extra741-i-0ebe9f469a9bdefe5-userData.decoded: No such file or directory
```
I am on a mac. This the version of gunzip:

```
$ gunzip --version
Apple gzip 287.100.2
```

I can't find  a workaround for this.  Any ideas what could be wrong?
Thanks!

**Comment by grayaii** [comment]
Note: This only happens on Mac. It works fine on linux

**Comment by marcjay** [comment]
@grayaii please could you provide the output of:
```
file -b ./secrets-XXX/extra741-i-0ebe9f469a9bdefe5-userData.decoded.gz
```
You'll need to temporarily comment out the `rm -rf $SECRETS_TEMP_FOLDER` command on this line: https://github.com/toniblyx/prowler/blob/master/checks/check_extra741#L67
So the file isn't deleted once Prowler exits

**Comment by toniblyx** [comment]
is this one also related to `coreutils`?

**Comment by grayaii** [comment]
I just did a git pull on master and re-ran this. This is the output of `file`:

    $ file -b ./secrets-XXX/extra741-i-0ebe9f469a9bdefe5-userData.decoded.gz
    JSON data

**Comment by marcjay** [comment]
I'm intrigued to see what the file looks like - are you able to share some of it, e.g. the first line with anything sensitive redacted? Or perhaps the output from `file -D ./secrets-XXX/extra741-i-0ebe9f469a9bdefe5-userData.decoded.gz`, but that outputs a lot of the file.

**Comment by grayaii** [comment]
Absolutely!

```
$ cat secrets-XXX/extra741-i-0ebe9f469a9bdefe5-userData.decoded.gz
{"run_env":"stage",  "role": "consul"}
```

Also, this is what it looks like when I query it:
```

$ aws ec2 describe-instance-attribute --instance-id i-0ebe9f469a9bdefe5 --attribute userData
{
    "InstanceId": "i-0ebe9f469a9bdefe5",
    "UserData": {
        "Value": "eyJydW5fZW52Ijoic3RhZ2UiLCAgInJvbGUiOiAiY29uc3VsIn0="
    }
}
```

**Comment by toniblyx** [comment]
In this line https://github.com/toniblyx/prowler//blob/3a989516d1c9b311277d527316517916b1d6f77f/checks/check_extra741#L35 prowler looks for the format with `file -b` and seems like in your Mac `file -b` gives you JSON instead of ASCII, that is weird because I tested it on a Mac as well... Can you change it as below and test it? 

```
FILE_FORMAT_ASCII=$(file -b $EC2_USERDATA_FILE|grep -E 'ASCII|JSON')
```

**Comment by grayaii** [comment]
it worked!!! Thanks @toniblyx

**Comment by marcjay** [comment]
On the basis that JSON User Data, whilst unusual, is seemingly perfectly valid - I imagine there is something on the instance @grayaii that fetches it from the instance metadata service and uses the JSON object to configure something, I've put out #549 which flips the check around to test if user data is a valid GZIP file, and only then gunzip it first
