### ISSUE TITLE
Check extra764 not compatible with GovCloud

### ISSUE THREAD

**Issue by rkane2002** [prowler-cloud/prowler#536]
Check 764 looks for "arn:aws:s3:::${bucket}" on line 39.  In GovCloud, this will never match because the partition is aws-us-gov, not aws (i.e., the arn begins with "arn:aws-us-gov:s3").  

This causes the check to fail on every bucket even when the proper bucket policy is in place.

**Comment by toniblyx** [comment]
Thanks @rkane2002. I'll try to reproduce it and find a fix.

**Comment by toniblyx** [comment]
hey @rkane2002 extra764 now reads the partition properly but I'm not sure if the `jq` filter is working fine. Please could you test it and let me know?

**Comment by rkane2002** [comment]
Just tried it out, works great

**Comment by toniblyx** [comment]
Can you please test `extra734` as well? and make sure the jq filter works fine in both checks? Thanks in advance

**Comment by rkane2002** [comment]
734 also looks good.  Running it against an account with a variety of bucket configurations (default encryption setup, bucket policy enforcement setup, nothing in place) and it properly detects all of them.  Similar results for 764.

**Comment by toniblyx** [comment]
Thanks!  I have looked for other checks with hardcoded partition and I found these ones below:
```
./checks/check114
./checks/check_extra71
./checks/check_extra720
./checks/check_extra725
./checks/check_extra771
```
I'm going to update them as well.

**Comment by rkane2002** [comment]
Awesome-  There are a few other GovCloud related issues that I've seen, just haven't had time to dig in to see what the issue is.  Do you want separate issues for each or one issue with all of them included?

**Comment by toniblyx** [comment]
those checks mentioned before have been updated to support govcloud partition and region

**Comment by toniblyx** [comment]
I bet the ones you find issues are related to region, please open a separate issue for anything else you find, I'll close this one. Thanks for your support fixing this!
