### ISSUE TITLE
Enhancement: new output format junit-xml including log duration

### ISSUE THREAD

**Issue by grayaii** [prowler-cloud/prowler#537]
When running with -M json (to produce json output), we get something like this:

```
{
  "Profile": "",
  "Account Number": "XXX",
  "Control": "[extra760] Find secrets in Lambda functions code (Not Scored) (Not part of CIS benchmark)",
  "Message": "us-west-2: Potential secret found in Lambda function connect-api-serverless-stage-custom-resource-apigw-cw-role code",
  "Status": "Fail",
  "Scored": "Not Scored",
  "Level": "Extra",
  "Control ID": "7.60",
  "Region": "us-west-2",
  "Timestamp": "2020-04-11T17:54:25Z"
}
```

It would be awesome if there was an entry for "duration".

**Comment by marcjay** [comment]
Purely out of interest, what would be the purpose of knowing what the duration of a check is? What would one do with that information?

**Comment by grayaii** [comment]
You bet!  I'm in the progress of converting the json output of prowler into a junit XML file so that Jenkins can consume it.  That way, we can have a nightly job that runs prowler, jenkins consumes it, and then graph the results over time.

I grabbed a random junit XML file and one of the entries that it has is "duration" (which Jenkins logs).

This is really low priority, but here is a screenshot of a jenkins test run (not from prowler, of course, but of some random tests):
![jenkins_junit_test_results](https://user-images.githubusercontent.com/847072/79054546-af919d00-7c13-11ea-8a62-a738f1541963.jpg)

And jenkins graphs the results over time, which will give us trends (along with alerting if a particular test fails):
<img width="590" alt="Screen Shot 2020-04-11 at 4 45 29 PM" src="https://user-images.githubusercontent.com/847072/79054561-f54e6580-7c13-11ea-8edd-e0b5ebb1d8e8.png">

**Comment by marcjay** [comment]
That makes sense to me - I'm quite familiar with Jenkins and JUnit XML files. If @toniblyx would be happy with this feature addition, I think I could put together a PR for it.

Next question to @toniblyx would be: does adding a `-M junit-xml` option, to add a new output mode which is JUnit XML sound acceptable? Would just be a case of outputting a `<testsuites>` header and `</testsuites>` footer, with a `<testsuite>` for each group and each pass/fail outputting a `<testcase>` tag

**Comment by toniblyx** [comment]
Sound good to me, just adding another output that may be helpful is good idea. Having `junig-xml` makes life easier for @grayaii to avoid conversions and may help others as well. @marcjay seems to be something kind of easy right? If you can send a PR that would be great :) I'm going to change the issue title as well.

**Comment by marcjay** [comment]
@grayaii It would be great if you'd be able to test the PR for this  - it's the `add-junit-xml-output-mode-log-duration-537` branch from #557 - thoughts welcome!
