### ISSUE TITLE
Enhancement: improve how to handle list of checks and groups

### ISSUE THREAD

**Issue by toniblyx** [prowler-cloud/prowler#545]
As stated here https://github.com/toniblyx/prowler/pull/541#issuecomment-612933243, as more checks and groups are created more difficult is also to see what is available. 

The idea is to improve the current `-l` and `-L` as in  `./prowler -L` to see all groups and their IDs, `./prowler -l -g cislevel1` to see all checks within that group, and `./prowler -l` if you just wanted a unique list of every single check (assuming none are orphaned outside of all groups and allow grepping for title). A nice-to-have might then be to have each check listed by -l show a comma-separated list of the group(s) that reference it (perhaps coloured), e.g. `4.1  [check41] Ensure no security ... port 22 (Scored) [group4,cislevel1,cislevel2]`

**Comment by marcjay** [comment]
Thanks for raising this 👍I'll pick it up unless you want it
