### ISSUE TITLE
All regions are not processed after check 21 - getting false negatives

### ISSUE THREAD

**Issue by scaryghosts** [prowler-cloud/prowler#550]
Hi, it looks like a change made on March 9 is clobbering the global variable $REGIONS for all subsequent checks.

Relevant Change(https://github.com/toniblyx/prowler/commit/263926a53b5698e53d69321c1d2d6939801840cc#diff-c03cdd797f9af2628b7ca4450153db42)

This is changing the $REGIONS variable to contain JUST the home CloudTrail region instead of all regions.

My proposed fix would be to add "local" in front of the $REGIONS variable on line 22.

**Comment by scaryghosts** [comment]
added this pull request
https://github.com/toniblyx/prowler/pull/551

**Comment by toniblyx** [comment]
fixed
