### ISSUE TITLE
parse error on check73 (Works on Mac, but not on AWS EC2 Instance)

### ISSUE THREAD

**Issue by grayaii** [prowler-cloud/prowler#558]
I think I found another OS discrepancy with this command:

    ./prowler -c check73 -r us-west-2 -f us-west-2

On a Mac, it works:

     7.3 [extra73] Ensure there are no S3 buckets open to the Everyone or Any AWS user (Not Scored) (Not 
    part of CIS benchmark)
       INFO! Looking for open S3 Buckets (ACLs and Policies) in all regions...
       PASS! us-west-2: XXX-tf-remote-state bucket is not Public

But on Linux (AWS Linux 1 OS)
```
 7.3 [extra73] Ensure there are no S3 buckets open to the Everyone or Any AWS user (Not Scored) (Not part of CIS benchmark) 
       INFO! Looking for open S3 Buckets (ACLs and Policies) in all regions...   
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
       FAIL! us-west-2: XXX-tf-remote-state bucket is Public! 
```

I'll get more debug info for this, but I wanted to create the ticket before I get pulled away.

**Comment by grayaii** [comment]
Doh! Please ignore this.
aws --version
aws-cli/1.14.68

Once I upgraded that ancient version of CLI, everything worked.
I don't know why I missed that.
Sorry about that.

**Comment by toniblyx** [comment]
ok cool, I'll close this one then. (I love the easy ones haha)
