### ISSUE TITLE
Feature Request: extra768 Only check latest version of ECS task definition

### ISSUE THREAD

**Issue by grayaii** [prowler-cloud/prowler#559]
When running extra768, prowler checks ALL versions of a task definition.

Since we cannot delete specific task definitions from AWS, even if we fix the issue, prowler will still fail:

7.68 [extra768] Find secrets in ECS task definitions variables (Not Scored) (Not part of CIS benchmark) 
       INFO! Looking for secrets in ECS task definitions' environment variables across all regions...  
       FAIL! us-west-2: Potential secret found in ECS task definition XXX--celery_inspect:1 variables 
       FAIL! us-west-2: Potential secret found in ECS task definition XXX--celery_inspect:2 variables 
       PASS! us-west-2: No secrets found in ECS task definition  XXX--celery_inspect:3 variables 

Is there a way to say "only check the latest version" of a task definition?

**Comment by grayaii** [comment]
I quickly looked at how to get this information, and it's not trivial with Bash (especially if you're using bash 3.X, since that version does not support hashmaps).

I think the solution would be to have the checks/check_extra768 call an inline python script to figure that out.  Just my 2 cents, if you decide to support this enhancement.

**Comment by toniblyx** [comment]
How would you do that in bash 4? and in python? We can add that inline python code, that's not a big deal, people love python :) 

If you give me info/steps to reproduce it I can try as well. Thanks!

**Comment by grayaii** [comment]
I created a PR by what I mean by a python script to get the latest version:
https://github.com/toniblyx/prowler/pull/560
It's rough around the edges (and helper scripts are probably not in the right spot), but it's a start.

**Comment by marcjay** [comment]
I'm all for Python, but just wondering if it's definitely needed here? Could it be achieved by calling `list-task-definition-families` to get the set of all families, and then for each family, calling `list-task-definitions --family-prefix <family> --sort DESC` using `--max-items 1` or jq to just get the first result. This is on the basis that the docs for `--sort` say:

> Setting this parameter to DESC reverses the sort order on family name and revision so that the newest task definitions in a family are listed first.

**Comment by grayaii** [comment]
You are absolutely right.
I updated the PR with your ideas: https://github.com/toniblyx/prowler/pull/560

**Comment by toniblyx** [comment]
#560 merged, thanks @grayaii
