### ISSUE TITLE
No Column Headers in CSV output

### ISSUE THREAD

**Issue by S733** [prowler-cloud/prowler#565]
Hi when I output the scan result to csv, no column headers were there in the output.

default | 8888888888 | us-east-1 | 2.6 | PASS | Scored | Level 1 | [check26] Ensure S3 bucket access logging is enabled on the CloudTrail S3 bucket (Scored)  | Bucket access logging enabled in CloudTrail S3 bucket 

What are the column headers for the above scan result. Is this a bug that headers are not in the csv file.

**Comment by toniblyx** [comment]
Thanks @S733  What is the command you do run? What are the steps to reproduce it? It is comma separated and comes with header...   

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toniblyx** [comment]
Please use the latest code in master or latest release and you will see CSV header. See this as example:

```
./prowler -M csv

Generating "," delimited report on stdout for profile , account 1234566789012
PROFILE,ACCOUNT_NUM,REGION,TITLE_ID,RESULT,SCORED,LEVEL,TITLE_TEXT,NOTES
<results here comma separated>
```

Please feel free to reopen this ticket if that is not your case and let us know how did you installed, run prowler, etc, to reproduce your issue.

**Comment by toniblyx** [comment]
pull latest code please, I added the header to the output file in addition to the stdout.
