### ISSUE TITLE
Avoid "Permission denied" errors when using Docker image

### ISSUE THREAD

**Issue by marcjay** [prowler-cloud/prowler#570]
Example output below using `-M csv` but see the same with other modes

```
$ docker run -ti --rm --name prowler toniblyx/prowler:latest -M csv

Generating "," delimited report on stdout for profile INSTANCE-PROFILE, account 1234567890
tee: prowler-output-1234567890-20200424142501.csv: Permission denied
PROFILE,ACCOUNT_NUM,REGION,TITLE_ID,RESULT,SCORED,LEVEL,TITLE_TEXT,NOTES
0.0 Show report generation info
tee: prowler-output-1234567890-20200424142501.csv: Permission denied
tee: prowler-output-1234567890-20200424142501.csv: Permission denied
```

Maybe an option to specify an output directory might help? Then a user could bind that output directory to a local directory on the host

**Comment by toniblyx** [comment]
Good catch @marcjay! What if we hit two birds with the same stone? (this is a saying Google, I don't want peta.org to close this repo :P) 
We could implement the S3 integration and be like `-z s3://<bucketname>`. I think nobody wants a report inside a container and probably neither inside an instance.

**Comment by marcjay** [comment]
Hehe yup I think that makes sense!
