### ISSUE TITLE
Selecting json-asff output mode outputs both json and json-asff

### ISSUE THREAD

**Issue by marcjay** [prowler-cloud/prowler#571]
Snippet from running:
```
$ ./prowler -M json-asff
{"Profile":"","Account Number":"123456789","Control":"[check11] Avoid the use of the root account (Scored)","Message":"Root user in the account wasn't accessed in the last 1 days","Status":"Pass","Scored":"Scored","Level":"Level 1","Control ID":"1.1","Region":"eu-west-1","Timestamp":"2020-04-24T15:39:14Z"}
{"SchemaVersion":"2018-10-08","Id":"prowler-1.1-123456789-eu-west-1-Root_user_in_the_account_wasn_t_accessed_in_the_last_1_days"...
```
I think it's from `"${MODES[@]}" =~ "json"` matching on `json-asff` as well

**Comment by toniblyx** [comment]
hmmm and creates two output files as well

**Comment by toniblyx** [comment]
`"${MODES[@]}" =~ "^json$"` ?

**Comment by marcjay** [comment]
> `"${MODES[@]}" =~ "^json$"` ?

I think that would break on `-M json,csv` for example?

**Comment by deathbywedgie** [comment]
> `"${MODES[@]}" =~ "^json$"` ?

It wouldn't break other output modes, but it doesn't quite work anyway. I've submitted a PR for a modified syntax that does fix it, though. I tested with `-M json,csv` to be sure, and it still works fine.

https://github.com/toniblyx/prowler/pull/572
