### ISSUE TITLE
Errors with json-asff in CentOS: tr: range-endpoints of '~-\012' are in reverse collating sequence order

### ISSUE THREAD

**Issue by deathbywedgie** [prowler-cloud/prowler#573]
When running in a CentOS docker image and using the json-asff output mode I am seeing errors in the output:
`tr: range-endpoints of '~-\012' are in reverse collating sequence order`

The script is completing successfully, and if I pipe stderr to a file or to /dev/null I see all the output that I would expect in stdout, so it does appear to be working properly otherwise, I just get tons of those errors in stderr that I have to sift through or filter out.

I don't see those errors when I run from MacOS.

**Comment by deathbywedgie** [comment]
I've tracked the issue down to the "generateJsonAsffOutput" function in include/output:

`  --arg UNIQUE_ID "$(LC_ALL=C echo -e "${message}" | tr -cs '[:alnum:]._~-\n' '_')" \`

I'll submit a PR to suppress the error, but I wonder if it wouldn't make more sense to just switch to sed instead of tr since that "reverse collating sequence order" is a known issue that can come up with tr from time to time anyway. (Even with the error suppressed, the script still exits with error code 3 regardless if there are any test fails in the results, regardless of which OS I've tested on _or_ what output mode I choose.)

**Comment by deathbywedgie** [comment]
> I'll submit a PR to suppress the error, but I wonder if it wouldn't make more sense to just switch to sed instead of tr since that "reverse collating sequence order" is a known issue that can come up with tr from time to time anyway. (Even with the error suppressed, the script still exits with error code 3 regardless if there are any test fails in the results, regardless of which OS I've tested on _or_ what output mode I choose.)

Actually it seems that error code 3 is coming from somewhere else, so ignore that and just take a look at that PR for now please. I'll just have to factor non-zero exit codes into my own scripts when I invoke yours. :)

**Comment by marcjay** [comment]
From googling there are some possible other fixes for this issue which I'll test on my CentOS VM - we should be able to resolve the error without suppressing it I reckon

**Comment by deathbywedgie** [comment]
@marcjay I like your solution better. I'm withdrawing my PR in lieu of the one you've opened.

**Comment by deathbywedgie** [comment]
@toniblyx Please take a look at this issue when you can. Turns out this isn't just causing error output, it's also affecting the data itself, because the "UNIQUE_ID" variable definition is failing and results in the "Id" field in json-asff output being incomplete for every result when run in CentOS. The PR from @marcjay resolves both aspects for me.

**Comment by toniblyx** [comment]
Thank you both for helping out with this fix!
