### ISSUE TITLE
Proposal to have a new RESULT value "VERIFICATION_REQUIRED".

### ISSUE THREAD

**Issue by rams3sh** [prowler-cloud/prowler#579]
I am trying to automate prowler findings to end up as a ticket in our internal work flow tool.
Currently prowler has the following three results :- 
```
PASS
FAIL
INFO
```
The usage of INFO is not clearly defined.
For example , lets take the two examples below :- 

**_i._** For check 
```
[check28] Ensure rotation for customer created CMKs is enabled (Scored)
```
a sample result is as follows :- 
```
RESULT - INFO
NOTES - eu-north-1: This region doesn't have ANY encryption keys
```

**_ii._** For check 
```
[check44] Ensure routing tables for VPC peering are "least access" (Not Scored)
```
a sample result is as follows :- 

```
RESULT - INFO
NOTES - ap-south-1: pcx-123456deadbeef - review routing tables
```

In , the first example there is no keys to check for , hence the INFO status fits well for the context of the check

However, in the second case, there is a need for an external intervention for reviewing the finding to confirm whether it is actually a PASS or a FAIL.

Due to lack of a distinction or a defined filter criteria, one may not be able to identify the ones which needs to be actioned upon. The issue I am personally facing is how to identify the ones which are to be actioned upon. Currently I was considering only "FAIL" result as a ticket. However on a closer review , identified some INFO cases also required manual verification.

The output referred in this issue is of csv format. However , this might be the case with other formats as well. Let me know if there is any alternative to find such cases without depending on RESULT alone in case this issue is not considered as valid, as I feel this has a good use case for external integrations.

**Comment by toniblyx** [comment]
Interesting to see use cases. I'll go though this and let you know.

**Comment by toniblyx** [comment]
There is a task in the roadmap to add more severity levels to Prowler: Informational, Low, Medium, High, Critical. I would work more on that than changing specific checks. In this case information could be `This region doesn't have ANY encryption keys` or just skip those kind of messages and low for the peering example.

**Comment by rams3sh** [comment]
@toniblyx  sure. The only concern behind raising this issue was to find a method or have a criteria of filtering actionable items. The title was just an idea.

**Comment by toniblyx** [comment]
I agree with you that Prowler should give information more granular, the goal is like ASFF with the severity levels mentioned above. That should be on v3 for sure. Date? I don't know but few months from today ;)

**Comment by toniblyx** [comment]
I'm going to go ahead and close this issue for three reasons:
- Any FAIL finding in Prowler can be verified so that status is more a status of the ticket system than the scanner.
- Using Prowler with Security Hub this can be used as part the workflow in that end.
- Using automated whitelisting FAIL items with justify note can be added to whitelist and they will be marked as WARNING only and not FAIL.
