### ISSUE TITLE
Exclude website hosting buckets in extra764 check

### ISSUE THREAD

**Issue by yumminhuang** [prowler-cloud/prowler#580]
According to [AWS S3 Documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html),
> Amazon S3 website endpoints do not support HTTPS.

Shall we exclude website hosting buckets when checking bucket policy in check [`extra764`](https://github.com/toniblyx/prowler/blob/master/checks/check_extra764)?

**Comment by toniblyx** [comment]
I added my thoughts to your pull request, white/blacklisting whould be a better idea see PR #514

**Comment by toniblyx** [comment]
This has been implemented see PR #514
