### ISSUE TITLE
"Info" missing from json-asff output

### ISSUE THREAD

**Issue by deathbywedgie** [prowler-cloud/prowler#584]
Not really sure if this is an issue or if it was intentional, but I wanted to check to be sure... I noticed today that the result counts are different between json and json-asff output, and it turns out it's because it's missing from the "textInfo" function.

Was this deliberate or an oversight?

**Comment by marcjay** [comment]
This was deliberate as the json-asff output is designed to be sent to AWS Secuity Hub, where each finding should concern a resource in AWS being either in or out of compliance. If you take a look at the info output, you'll see it's almost all textual info (often across multiple lines and therefore multiple textInfo calls) that is non-actionable. e.g. "This check requires manual checking" or "No buckets found in region X". When doing this it felt like having these text messages in Secuity Hub would just be noise, so I excluded them.

**Comment by toniblyx** [comment]
Yes, that's exactly the point.

**Comment by deathbywedgie** [comment]
How about an option (or maybe even default behavior) to include info in stdout without necessarily sending to Security Hub? I like the asff format, but I'm automating some tracking/trending around AWS account configs and would like that informational data.

**Comment by toniblyx** [comment]
You can add that logic to `include/outputs` into the function `textInfo` but without the `tee` command. I'd like to know more about the use case though.

**Comment by toniblyx** [comment]
Closing this issue since that info is implemented using json format and can be used for the purpose explained by the user.
