### ISSUE TITLE
extra726 - [Error] An error occurred (AccessDeniedException) when calling the DescribeTrustedAdvisorCheckResult

### ISSUE THREAD

**Issue by muharihar** [prowler-cloud/prowler#588]
Hi Team,

I got an error for check item `extra726`:

```
7.26 [extra726] Check Trusted Advisor for errors and warnings (Not Scored) (Not part of CIS benchmark)

An error occurred (AccessDeniedException) when calling the DescribeTrustedAdvisorCheckResult operation: User: ******* is not authorized to perform: support:DescribeTrustedAdvisorCheckResult
```

How to fix this error?

Thank you!

**Comment by toniblyx** [comment]
I guess a policy allowing action `support:DescribeTrustedAdvisorCheckResult` is not attached to the role that is being use by Prowler right?

**Comment by toniblyx** [comment]
If you go to https://github.com/toniblyx/prowler#requirements-and-installation and look at the last section you will see that you need `arn:aws:iam::aws:policy/SecurityAudit`, 
`arn:aws:iam::aws:policy/job-function/ViewOnlyAccess` and https://github.com/toniblyx/prowler/blob/master/iam/prowler-additions-policy.json

**Comment by muharihar** [comment]
Ok, thanks a lot @toniblyx !
