### ISSUE TITLE
junit-xml output should show failures that are ignored due to whitelisting as skipped checks

### ISSUE THREAD

**Issue by marcjay** [prowler-cloud/prowler#590]
Noticed that in #514, failures that are downgraded to warnings as the resources are whitelisted are excluded from junit-xml output. I think it would be reasonable to indicate that these checks are 'skipped' as that is the closest equivalent in this case

**Comment by toniblyx** [comment]
Thanks @marcjay, if you please can look at the json-asff report as well and point me to the code where we can remove WARNINGS there? It would be good to remove them from asff or at least to not send them to Security Hub, I don't like that option but to keep consistency... what do you think?

**Comment by marcjay** [comment]
I did a quick check of that to make sure that WARNING was a valid compliance level according to the schema, and it is. The description is as follows:

> WARNING – Some information is missing or this check is not supported given your configuration.

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-findings-format.html#asff-compliance

Do you think this is appropriate for a whitelisted check? Is this option any better?:

> NOT_AVAILABLE – Check could not be performed due to a service outage or API error. The NOT_AVAILABLE status can also indicate that the result of the AWS Config evaluation was NOT_APPLICABLE. In that case, after 3 days, Security Hub automatically archives the finding.

Otherwise yes do you think they should be excluded entirely?

Off-topic - did you get anywhere with requesting a product ID for Prowler within Security Hub?

**Comment by toniblyx** [comment]
I think we can leave it as it is then. Let's see how it goes with the users use case.

> Off-topic - did you get anywhere with requesting a product ID for Prowler within Security Hub?

I'm working on it

**Comment by toniblyx** [comment]
Main topic of this issue was solved already. Closing it.
