### ISSUE TITLE
Wrong Compliance Status provided to Security Hub

### ISSUE THREAD

**Issue by rafaljanicki** [prowler-cloud/prowler#599]
Prowler version: 2.3.0RC0

When sending an event to Security Hub, Prowler uses a wrong JSON for failed checks what causes SH to error. The reason for that is that currently, Prowler uses FAIL as Compliance -> Status, but should use FAILED per documentation: https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_Compliance.html#securityhub-Type-Compliance-Status

**Comment by marcjay** [comment]
This has been fixed in #592 but you'll need to use the `master` branch of prowler until 2.3.0 (or another release candidate) is released

**Comment by rafaljanicki** [comment]
Sorry!
