### ISSUE TITLE
check_extra734 Failing when bucket policy is empty

### ISSUE THREAD

**Issue by theOriginalClauBotas** [prowler-cloud/prowler#604]
Next line doesn't consider that when the bucket policy is empty aws cli returns "An error occurred (NoSuchBucketPolicy) when called the GetBucketPolicy operation: The bucket policy does not exist"

$AWSCLI s3api get-bucket-policy $PROFILE_OPT --bucket $bucket --region $BUCKET_LOCATION --output text --query Policy > $TEMP_SSE_POLICY_FILE 2>&1

The if statements are not considering the "Could not connect to the endpoint" to the url of the policy is an answer for an unexistent bucket policy

Replicate:
Run the check with a bucket whit  no bucket policy

**Comment by w0rmr1d3r** [comment]
Hello @theOriginalClauBotas ,
has this been fixed?
Isn't that if statement the one on this line?
https://github.com/toniblyx/prowler/blob/master/checks/check_extra734#L68

Cheers!

**Comment by toniblyx** [comment]
Yes, that particular behaviour was fixed here https://github.com/toniblyx/prowler/pull/407 (probably wasn't using that version). Please feel free to reopen this issue if you identify the error again.
