### ISSUE TITLE
output folder should be outside of the prowler folder

### ISSUE THREAD

**Issue by tekdj7** [prowler-cloud/prowler#605]
**output** folder should be outside of the prowler folder made when doing git clone, and as such, should be renamed to **output_prowler** or **output-prowler**

So that if user deletes prowler and downloads a newer version via git clone, they don't lose the reports it's saved.

**Comment by toniblyx** [comment]
In ephemeral deployments  this feature is not needed since output files are copied to an S3 bucket.
