### ISSUE TITLE
HTML report - save to pdf, option for landscape not easily available

### ISSUE THREAD

**Issue by tekdj7** [prowler-cloud/prowler#612]
In HTML report, print & save to pdf, option to change layout to landscape is not easily available.  Instead, have to go to More Settings ->  Print Using System Dialog, then can change layout.  Using Chrome browser.

On other websites, when you click Print, immediately an option shows in Chrome to change layout to landscape, before saving to PDF.  Or maybe if there's a way to default the website to landscape, when you go to print.

**Comment by toniblyx** [comment]
https://github.com/toniblyx/prowler/issues/707
