### ISSUE TITLE
HTML report - copy/paste lines format messes up.

### ISSUE THREAD

**Issue by tekdj7** [prowler-cloud/prowler#615]
In HTML report, if you copy lines including the header, it pastes perfectly in emails/notes.

However, if you copy lines in the middle, where header isn't shown, and paste into email/notes, then formatting messes up.

I believe issue is related to when starting to highlight to copy, I can only do it on the cell where it says Pass/Fail, I can't do it on the cell with the icon, thus first line, shows everything shifted back by 1 cell.  Yet the subsequent lines in the highlight, do bring over the cell with the icon (though empty), and now everything is shifted to the right by 1 cell.

**Comment by toniblyx** [comment]
https://github.com/toniblyx/prowler/issues/707
