### ISSUE TITLE
Prowler runs in loop when a particular permission is removed

### ISSUE THREAD

**Issue by laxmanvijay** [prowler-cloud/prowler#617]
When a permission is removed from the role given to prowler to perform a certain check, instead of just showing permission denied, prowler runs that particular check in loop continuously.

This occurs for many checks eg: check21 but some other checks do not suffer from this issue, they terminate eg: extra748

**Comment by toniblyx** [comment]
Thanks @laxmanvijay, could you please give specific instructions to reproduce it? Can you also run it as `bash -x ./prowler -c check21` and see where the loop happens? It could be a specific aws-cli command or something else.

**Comment by laxmanvijay** [comment]
@toniblyx  For reproducing the exact same issue you have to create a role without the permission for executing a particular check. For example, in case of check21 it is "cloudtrail:DescribeTrails" and configure that role in aws cli. Then you can run " ./prowler -c check21 " which will start to run in a loop saying "An error occurred (AccessDeniedException) when calling the DescribeTrails operation: User is not authorized to perform: cloudtrail:DescribeTrails" for all the regions.

Instead this should be like if there is no permission, it should stop without looping all the regions.

And also, 

genCredReport() {
  textTitle "0.1" "Generating AWS IAM Credential Report..." "NOT_SCORED" "SUPPORT"
  until $( $AWSCLI iam generate-credential-report --output text --query 'State' $PROFILE_OPT --region $REGION |grep -q -m 1 "COMPLETE") ; do
    sleep 1
  done
}

In this genCredReport() function in credentials_report file, this code loops if there is no permission to generate-credentials saying, "An error occurred (AccessDenied) when calling the GetCredentialReport operation: User is not authorized to perform: iam:GetCredentialReport on resource: * "

**Comment by laxmanvijay** [comment]
Also, if try_assume_role function fails, the program should exit saying it doesn't have permission. But it continues to run and all other checks fail.

**Comment by toniblyx** [comment]
Thanks for the heads up @laxmanvijay, I'll look at that as soon as I can, in any case, fee free to send a pull request if you manage to fix it.

**Comment by m3Ik0r** [comment]
Hi - also have this problem - if an action has access denied error, it gets stuck in a loop and does not carry out the rest of the checks

**Comment by zfLQ2qx2** [comment]
@laxmanvijay I raised https://github.com/toniblyx/prowler/pull/723 to take care of the assume role issue.

**Comment by zfLQ2qx2** [comment]
@toniblyx I raised https://github.com/toniblyx/prowler/pull/726 to address the endless loop in genCredReport

**Comment by zfLQ2qx2** [comment]
@toniblyx I raised https://github.com/toniblyx/prowler/pull/726 to address access denied when calling describe-trails

**Comment by toniblyx** [comment]
As mentioned by @zfLQ2qx2 these issues were already fixed. Thanks!
