### ISSUE TITLE
SecurityHub import fails with AccessDenied if finding is in another region

### ISSUE THREAD

**Issue by DenSpirit** [prowler-cloud/prowler#618]
Even with policy allowing BatchImportFindings, API call can fail if we are trying to import finding from one region to Security Hub in another region, e.g. missing VPC flow logs in ap-south-1 being imported into us-east-1 Security Hub.
Region-locking prowler (-r switch) does not seem to help, because some checks are global.
This can be important if AccessDenied events are monitored by some CloudWatch alerts, and because of that we can't run prowler frequently without disturbing the team.

**Comment by toniblyx** [comment]
Thanks for your feedback @DenSpirit, have you tested running prowler from a region (in an EC2 in that region) where is the same as your Security Hub? You can filter also region by `-f` to just do that region and avoid any other region that you don't need to check.

For the access denied you can use `-f` along with your own group of checks and/or whitelisting `-w` see README for more information. If you don't have permissions to check a particular service, resource or region you can avoid it.

**Comment by toniblyx** [comment]
@marcjay what do you think about this issue?

**Comment by marcjay** [comment]
Interesting! I wasn't aware that Security Hub had this restriction, though it makes sense, though means you can't consolidate all your findings if you're multi-regional into one 'Security Hub' environment.

I've raised #621 which should resolve this - forcing the finding to be imported to it's associated region. @DenSpirit please could I possibly ask you to try that `sechub-import-to-finding-region-618` branch to see if it resolves your issue?
