### ISSUE TITLE
Error )UnrecognizedClientException) when calling the DescribeTrustedAdvisorChecks operation

### ISSUE THREAD

**Issue by redxking** [prowler-cloud/prowler#626]
im running the following command ./prowler -E -A 447554752567 -R EADMIN -T 3600 -b -M csv,html
The EADMIN has full adminstrator access but im getting this error.

An error occurred (UnrecognizedClientException) when calling the DescribeTrustedAdvisorChecks operation: The security token included in the request is invalid.

**Comment by toniblyx** [comment]
Not sure if that call depends on the account subscription but you can exclude it from the checks with `-E extra726`
