### ISSUE TITLE
Add remediation commands as recommendation option

### ISSUE THREAD

**Issue by toniblyx** [prowler-cloud/prowler#63]
As security assessment tool, I don't think is good idea to allow Prowler to fix or apply changes to the infrastructure. That would mean a big change on the role that allows Prowler to get all the info (readOnly as good practice). However, I think it would be very helpful to have an option that shows a list of commands to fix or remediate all findings, then the user will chose what to run and under what role.

**Comment by wassies** [comment]
+1 to not changing the role associated with Prowler.

How would you like to display the fixes that cannot be completed via commands? Just display a link to the relevant documentation?

**Comment by toniblyx** [comment]
That is probably a good idea. Link to the document is always good since it is the main source of truth for the CIS benchmark.

**Comment by wassies** [comment]
Were you working on this issue somewhere already @toniblyx ? More than happy to help out where I can.

**Comment by toniblyx** [comment]
Hi @wassies, I've got to close other issues first so feel free to add this feature, it would be great! You can add a flag like `-s` to show fix solution recommendations (or whatever flag that is not used already). Thanks again!

**Comment by toniblyx** [comment]
This is actually possible to automate with code as explained here https://aws-quickstart.s3.amazonaws.com/quickstart-compliance-cis-benchmark/doc/cis-benchmark-on-the-aws-cloud.pdf
