### ISSUE TITLE
Html doe'snt appear to render properly when served up.

### ISSUE THREAD

**Issue by mrpackethead** [prowler-cloud/prowler#631]
When i place the html content in a S3 bucket and serve it up via a Cloudfront distribution i get a bunch of errors related to the rendering of the pages. 

Refused to load the stylesheet 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' because it violates the following Content Security Policy directive: "style-src 'self'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

prowler-output-099xxxxxxxxxx437-20200708031211.html:9 Refused to load the stylesheet 'https://cdn.datatables.net/v/dt/jqc-1.12.4/dt-1.10.21/b-1.6.2/sl-1.3.1/datatables.min.css' because it violates the following Content Security Policy directive: "style-src 'self'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

prowler-output-099xxxxxxxxx437-20200708031211.html:10 Refused to load the stylesheet 'https://pro.fontawesome.com/releases/v5.10.0/css/all.css' because it violates the following Content Security Policy directive: "style-src 'self'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

8Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

prowler-output-099xxxxxxxxxxx437-20200708031211.html:78 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-jmX6glpRTaqD7IJEBFRJYx/HErm5xkMOCjrj33dgdEM='), or a nonce ('nonce-...') is required to enable inline execution.

prowler-output-099xxxxxx7-20200708031211.html:84 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-utzSfCnLR1T19s6JseL5isSFFX7T11ZMQkrM9kq7t6c='), or a nonce ('nonce-...') is required to enable inline execution.

prowler-output-0998xxxxxxx37-20200708031211.html:85 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-utzSfCnLR1T19s6JseL5isSFFX7T11ZMQkrM9kq7t6c='), or a nonce ('nonce-...') is required to enable inline execution.

prowler-output-0998xxxxxxxxxxxxx37-20200708031211.html:1 Refused to load the image 'https://raw.githubusercontent.com/toniblyx/prowler/master/util/html/prowler-logo.png' because it violates the following Content Security Policy directive: "img-src 'self'".

prowler-output-099xxxxxxxxxxx437-20200708031211.html:24267 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-qS6M9Q5O3XTT5kISGRAFiWPQnJdXUlyIUzF0PZkzTFo='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by toniblyx** [comment]
I haven't seen that before, I would say that you may need to modify the html template and load all css and js from the same bucket as well. Have you tried that? Look at file https://github.com/toniblyx/prowler/blob/master/include/html_report

**Comment by mrpackethead** [comment]
Thanks... I inlcuded this, and it makes soem improvements, but the rest Are CORS errors.  I'll look at bit deeper at this now i know where to look and hopefuly come back with an answer for it and submit a PR

<meta http-equiv="Content-Security-Policy" content="content_security_policy": "default-src 'self' style-src 'self' 'unsafe-inline';" >**

**Comment by toniblyx** [comment]
Hey @mrpackethead feel free to send a PR if you improved that template. Thanks in advance.
