### ISSUE TITLE
Include CIS Level info in outputs

### ISSUE THREAD

**Issue by MrSecure** [prowler-cloud/prowler#64]
Mark each of the items as Level 1 or Level 2.

Add check groups for level1  and level2  to run only the benchmarks in each level.

**Comment by toniblyx** [comment]
Ok, that's like in the CIS-CAT tool. In the guide is called Profile Applicability.

Definitions below extracted from page 8 here https://d0.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf  

Profile Definitions
The following configuration profiles are defined by this Benchmark:

Level 1: Items in this profile intend to:
- be practical and prudent;
- provide a clear security benefit; and
- not inhibit the utility of the technology beyond acceptable means.

Level 2: This profile extends the "Level 1" profile. Items in this profile exhibit one or more of
the following characteristics:
- are intended for environments or use cases where security is paramount
- acts as defense in depth measure
- may negatively inhibit the utility or performance of the technology.

**Comment by toniblyx** [comment]
@MrSecure how would you implement it? I think it is very straightforward doing it like here 
https://github.com/Alfresco/prowler/blob/master/prowler#L1368

```
callCheckByLevel(){
 if [[ $LEVELNUMBER ]];then
  case "$LEVELNUMBER" in
   level1 ) checkN1...checkN;;
   level2 ) checkM1...checkM;;
 fi
```
WDYT?

**Comment by toniblyx** [comment]
here is a list of checks per Level:
```
Level 1 
check11 
check12
check13
check14
check15
check16
check17
check18
check19
check110
check111
check112
check113
check115
check116
check117
check118
check119
check120
check122
check123
check124
check21
check23
check24
check25
check26
check31
check32
check33
check34
check35
check38
check312
check313
check314
check315
check41
check42

Level 2
check114
check121
check22
check27
check28
check36
check37
check39
check310
check311
check43
check44
check45
```

**Comment by MrSecure** [comment]
I was thinking it'd be easiest to just add "level1" and "level2" as check groups that call all of the check functions in each level. ... keeping it part of callCheck()
then there are no new flags to add, and it's just
`prowler -c level1 ...`

**Comment by toniblyx** [comment]
ok I got it, makes sense and it makes it easier.

**Comment by toniblyx** [comment]
I'll add it tonight

**Comment by toniblyx** [comment]
I think that's all what we need to support Profile Definitions.
