### ISSUE TITLE
Add extra info for compliance checks in output

### ISSUE THREAD

**Issue by gchib297** [prowler-cloud/prowler#640]
Map compliance checks with their relevant clause or requirements in output. 

A column in csv and html report that lists extra info (Category, Objective ID, Objective name) for the check could be a nice addition. I can crate mappings for checks with HIPAA, ISO and GDPR (similar to #636 #637 #639 ). 

Any ideas how we can add this in prowler?

_Example_ - For check21 ISO mapping:
```
Category: A.12 Operations Security
Objective ID: A.12.4
Objective name: Logging and monitoring
```

**Comment by toniblyx** [comment]
Agree, this would be very helpful for compliance.

**Comment by toniblyx** [comment]
Version 2.5 adds information like the one requested partially in csv, html and json outputs. It is planned to increase the coverage of compliance information for version 3. As a reference, I like the way it is handled from in ElectricEye by @jonrau1, here is an example for Glue https://github.com/jonrau1/ElectricEye/blob/31960e1e1cfb75c5d354844ea9e07d5295442823/eeauditor/auditors/aws/AWS_Glue_Auditor.py#L98-L104 . I'll add a note about this ticket to the roadmap just to make sure it is taken into consideration. Closing it.
