### ISSUE TITLE
Threashold in check 121 (last used aws key)

### ISSUE THREAD

**Issue by WtfJoke** [prowler-cloud/prowler#645]
Hi there

Currently we have some false positives on [check 121](https://github.com/toniblyx/prowler/blob/master/checks/check121) with some users. 

They arise when the access key has just been created quite recently and nobody used it so far. What do you think of having a threshold of some days in there? E.g the check will not fail, if we have created the access key less than x days.

I know I could whitelist that, but if for some reason this access key is unused for a longer period of time it would be cool to know that. 
If you think thats a bad idea, feel free to tell me 👍 :)

**Usecase**
We rotate the credentials of our iam users quite often (1-7 days) and when we execute the check and nobody has yet used the access key, the check fails.

**Comment by toniblyx** [comment]
Thanks for your comment @WtfJoke, I think it makes sense for your use case but not sure for the rest of the users following CIS recommendations. 

I recommend you to add a variable to control that needed period in your use case but it should work as it is now out of the box. Please feel free to send a PR with that in case it may benefit other with similar needs.

**Comment by toniblyx** [comment]
I will close this issue but please feel free if you need more info or have any comment. Thanks!
