### ISSUE TITLE
Add Extras section with additional helpful checks

### ISSUE THREAD

**Issue by toniblyx** [prowler-cloud/prowler#66]
I'm thinking to add more checks that are helpful for auditing an account security, I'm thinking on detailed S3 bucket analysis or EBS snapshots permissions, among many other checks that might come up.
It would be section "Extras" outside CIS.

**Comment by MrSecure** [comment]
I added one to look for admins who do not have MFA tokens enabled, in #73

**Comment by MrSecure** [comment]
Another candidate:  identify S3 buckets open to the world

**Comment by toniblyx** [comment]
Yes, that's one around S3  I have written already and also the EBS snapshots public check. I'll send the PR later today. They are check72 and check73

**Comment by toniblyx** [comment]
Added check72 and check73
7.2  Ensure there are no EBS Snapshots set as Public (Not Scored) (Not part of CIS benchmark)
7.3  Ensure there are no S3 buckets open to AllUsers (Not Scored) (Not part of CIS benchmark)
