### ISSUE TITLE
Prowler versions later than 2.3.0RC3 skips scanning multi-region

### ISSUE THREAD

**Issue by jackalxyz** [prowler-cloud/prowler#661]
When using Prowler versions later than 2.3.0RC3, the swtich `-f 'us-east-1 eu-west-1...'` no longer scan multiple regions correctly. Only one region is randomly selected from the specified regions to scan.

**Comment by toniblyx** [comment]
Hi @ssteo, option `-f region` is used to query just one region. I have tested it in latest code in master with this command `./prowler -f 'us-east-1 eu-west-1' -c check42` and it shows results from both regions correctly. To be honest I never tried regions separated with space and between single quotes (thanks!) but it works. Remember that for those checks that are global you won't see any difference.

**Comment by jackalxyz** [comment]
Thanks for the response. Actually I wasn't sure if `-f region` supports multiregion initially but looking at https://github.com/toniblyx/prowler/blob/master/prowler#L236-L240 it appears to be able to handle space separated multiple regions.

Did you try with region specific resources? I was scanning EBS volume which exist in some regions but the scan results from the current master branch code is not showing some of the regions. So I reverted back to this commit 43d95ac18c2618ac5d0cb6e973934886bba29a40 and so far it works fine.

**Comment by toniblyx** [comment]
can you please share the exact command you are running to test it in my side? I don't see the link between the version label and regions...

**Comment by jackalxyz** [comment]
Sure, here's the command used.

./prowler -b -q -f us-east-1 us-west-2 ap-south-1 ap-southeast-1 eu-central-1 eu-west-1 sa-east-1 -g [custom_check_group] -r eu-west-1 -A [aws_accound_id] -R [internal_iam_role_name] -M html,json

**Comment by toniblyx** [comment]
I have tested this one `./prowler -b -q -f 'us-east-1 us-west-2 ap-south-1 ap-southeast-1 eu-central-1 eu-west-1 sa-east-1' -c check41 -r eu-west-1  -M html,json` with latest code in master and works fine for those regions with resources, in this case security groups. Have you used single quotes?

**Comment by jackalxyz** [comment]
@toniblyx yeah, there's single quote in my command too. Sorry, I've accidentally left out the single quote when pasting in GitHub comment earlier.

**Comment by jackalxyz** [comment]
I'll try again later with the latest master branch code whenever possible. Thanks
