### ISSUE TITLE
Prowler attempting to access resources in unsupported regions

### ISSUE THREAD

**Issue by dsudduth** [prowler-cloud/prowler#662]
Hello @toniblyx,

I've noticed that Prowler is attempting to scan a few services (ECS, EKS) in regions that do not support them.

```
Could not connect to the endpoint URL: "https://ecs.ap-northeast-3.amazonaws.com/"
Could not connect to the endpoint URL: "https://eks.ap-northeast-3.amazonaws.com/clusters"
Could not connect to the endpoint URL: "https://eks.ap-northeast-3.amazonaws.com/clusters"
Could not connect to the endpoint URL: "https://eks.ap-northeast-3.amazonaws.com/clusters"
Could not connect to the endpoint URL: "https://eks.ap-northeast-3.amazonaws.com/clusters"
```

Looks as if a similar issue has come up. Ref: https://github.com/toniblyx/prowler/issues/300
Would you still recommend using `2> /dev/null` or is there a better option?

**Comment by toniblyx** [comment]
Hi @dsudduth, Prowler runs over all available regions by default, see here https://github.com/toniblyx/prowler/blob/master/prowler#L235-L240

If you want to run Prowler on specific regions only use `-f` to filter the regions you want, like:
```
./prowler -f 'us-east-1 us-east-2 eu-central-1 eu-west-2'
```
Note the regions separated by space and between single quotes.

**Comment by dsudduth** [comment]
@toniblyx thanks for your response and sorry for the delay getting back to you. I may have not explained it well. The issue that I'm seeing is that we do want the region scanned. However, that region does not support a particular service. I am using Prowler's JSON output so I can process the results however, Prowler transitions from JSON to strings when it encounters this scenario. In my execution, I've piped the results out and ignored the error so I can avoid parsing issues.

```bash
./prowler -b -n -q -M json | grep { > prowler-output.txt
```

Just wanted to check in to see if this is something we can look at as a feature (log issues as JSON as well) or if you'd recommend keeping the snippet above as the best option. The reason I referenced that ticket is that it looks like others have seen similar issues.

Thanks again for your help!

**Comment by toniblyx** [comment]
I think both solutions are fine if they work for you, I would prefer to detect what checks are giving you that error and add `2> /dev/null` to prevent any post-pipe grep. In any case, remember that the latest versions of Prowler already generate a json file in the output folder using `-M json` or any other supported format. Have you checked if that one still has the error text? You don't need to redirect the output when using `-M`.

**Comment by brendan-s1** [comment]
Thank you for this, the -f 'region1 region2' really needs to be on the main documentation page.

**Comment by w0rmr1d3r** [comment]
Can't find it in the Readme @brendan-s1 , but it does appear in the help menu:
```
-f <filterregion>   specify an AWS region to run checks against
                      (i.e.: us-west-1 or for multiple regions use single quote like 'us-west-1 us-west-2')
```
Shall we put an example in the readme as well?

**Comment by w0rmr1d3r** [comment]
Don't mind my previous comment, on branch `2.5` it already exists:
https://github.com/toniblyx/prowler/tree/2.5#regions

I believe we can close this issue now.

**Comment by toniblyx** [comment]
I added that to the readme as well in branch 2.5.

**Comment by toniblyx** [comment]
This was already documented.
