### ISSUE TITLE
Exit code 3  - date: invalid date ‘@None’ / date: invalid date ‘+%s’"

### ISSUE THREAD

**Issue by deanvaturi** [prowler-cloud/prowler#669]
**Hi,**

**while I am trying to run the bottom script as a Jenkins pipeline, in order to Create a prowler report for a development env, I am encountering an issue which the console prints:****

"14:51:02  + export AWS_REGION=eu-central-1
14:51:02  + ./prowler -p XXXX -r eu-central-1 -M text,junit-xml
15:42:55  date: invalid date ‘@None’
15:42:55  date: invalid date ‘+%s’"

**which I think that leads eventually to
the error:**

"[Pipeline] End of Pipeline
ERROR: script returned exit code 3
Finished: FAILURE" 
**What could be the problem?**

`git clone https://github.com/toniblyx/prowler
cd prowler
export AWS_PROFILE=XXXX
pwd
export AWS_REGION=us-east-1
./prowler -p XXXX -r us-east-1 -M text,junit-xml > YYY-prowler-$env.BUILD_ID-report.txt
cat YYY-prowler-$env.BUILD_ID-report.txt | ansi2html -l > YYY-prowler-$env.BUILD_ID-report.html`

**Comment by toniblyx** [comment]
What OS and AWSCLI version are you using? If you want to run Prowler to only one region use `-f` instead to filter by region.

**Comment by toniblyx** [comment]
I still can't see where that `date` command is failing, can you run prowler using `bash -x ./prowler -f eu-central-1` to reduce the time and see where command date is actually giving an error? 

I have tested it with ubuntu:16.04, botocore-1.18.17 and awscli-1.18.158 without errors. Can you try updating your components? At least awscli and boto3. If you have the chance of using docker you can see some examples here: https://github.com/toniblyx/prowler#usage with that you can make sure it is not anything related to your environment.

**Comment by deanvaturi** [comment]
I am sorry, but i couldn't find anything related to "invalid date" inside of the output of "bash -x ./prowler -f eu-central-1"  ill have to dig it to the bottom and get back to you.
 added my  Jenkins pipeline console output, hope it will help.

Second thing is, when I am using the following command "-M HTML" in order to create a colored HTML report I keep getting blank white one, different than the one you posted on your example in the instructions 
*console output
`[Pipeline] withEnv
[Pipeline] {
[Pipeline] sh
12:48:50  + rm -rf prowler
12:48:50  + git clone https://github.com/toniblyx/prowler
12:48:50  Cloning into 'prowler'...
12:48:49   > git rev-parse refs/remotes/origin/devsecops-prowler-new^{commit} # timeout=10
12:48:49   > git rev-parse refs/remotes/origin/origin/devsecops-prowler-new^{commit} # timeout=10
12:48:49   > git config core.sparsecheckout # timeout=10
12:48:49   > git checkout -f 8374c5f7b8fd2b24a17bbe16e2e3505ad6c8f92c # timeout=10
12:48:49   > git rev-list --no-walk 8374c5f7b8fd2b24a17bbe16e2e3505ad6c8f92c # timeout=10
12:48:52  + cd prowler
12:48:52  + export AWS_PROFILE=one-prowler
12:48:52  + pwd
12:48:52  /home/automation/workspace/devopsprowler
12:48:52  + export AWS_REGION=us-east-1
12:48:52  + ./prowler -p dev-prowler -r us-east-1 -M html
13:33:44  date: invalid date ‘@None’
13:33:44  date: invalid date ‘+%s’`

**Comment by deanvaturi** [comment]
I am sorry, but I couldn't find anything related to "invalid date" inside of the output of "bash -x ./prowler -f eu-central-1" ill have to dig it to the bottom and get back to you.
added my Jenkins pipeline console output, hope it will help.

Second thing is, when I am using the following command "-M HTML" in order to create a colored HTML report I keep getting a blank white one, different than the one you posted on your example in the instructions
*console output
[Pipeline] withEnv [Pipeline] { [Pipeline] sh 12:48:50 + rm -rf prowler 12:48:50 + git clone https://github.com/toniblyx/prowler 12:48:50 Cloning into 'prowler'... 12:48:49 > git rev-parse refs/remotes/origin/devsecops-prowler-new^{commit} # timeout=10 12:48:49 > git rev-parse refs/remotes/origin/origin/devsecops-prowler-new^{commit} # timeout=10 12:48:49 > git config core.sparsecheckout # timeout=10 12:48:49 > git checkout -f 8374c5f7b8fd2b24a17bbe16e2e3505ad6c8f92c # timeout=10 12:48:49 > git rev-list --no-walk 8374c5f7b8fd2b24a17bbe16e2e3505ad6c8f92c # timeout=10 12:48:52 + cd prowler 12:48:52 + export AWS_PROFILE=one-prowler 12:48:52 + pwd 12:48:52 /home/automation/workspace/devopsprowler 12:48:52 + export AWS_REGION=us-east-1 12:48:52 + ./prowler -p dev-prowler -f us-east-1 -M html 13:33:44 date: invalid date ‘@None’ 13:33:44 date: invalid date ‘+%s’

**Comment by deanvaturi** [comment]
maybe this is the problem? i have added dump which shows that in the date section its empty 
`bash -x ./prowler -f eu-central-1  > dump.txt
+ OPTRED=''
+ OPTNORMAL=''
+ PROWLER_VERSION=2.3.0RC4
++ dirname ./prowler
+ PROWLER_DIR=.
+ REGION=
+ FILTERREGION=
+ MAXITEMS=100
+ MONOCHROME=0
+ MODE=text
+ QUIET=0
+ SEP=,
+ KEEPCREDREPORT=0
+ EXITCODE=0
+ SEND_TO_SECURITY_HUB=0
++ date -u +%Y-%m-%dT%H:%M:%S%z`

**Comment by toniblyx** [comment]
could you please attach the output dump.txt file of this command? `bash -x ./prowler -f eu-central-1 2> dump.txt` otherwise it is almost impossible to find that out. You can also fake some of your account data from the dump.txt file if needed. Thanks.

**Comment by toniblyx** [comment]
In https://github.com/toniblyx/prowler#save-your-reports you can see that the option is `-M html` in uppercase won't work. That saves a report in the output directory, as other formats.

Back to this error, that date command is failing in a particular check, to reduce the time to run it, do first filtering by region as I show in my example from yesterday. Identify the check that is failing or do that dump and share it. Thanks.

**Comment by deanvaturi** [comment]
you are right i miss typed it with uppercase, added the output of the HTML so you could see its different than the one you posted (colored), I am currently working on extracting the "date" failure 
![Screen Shot 2020-10-21 at 10 32 02](https://user-images.githubusercontent.com/67010637/96687842-1b09b380-1389-11eb-9397-121ebe08e011.png)

**Comment by deanvaturi** [comment]
@toniblyx after running it again I looked inside of the output and I saw:

19:11:15  [0;35m 7.30 [extra730] Check if ACM Certificates are about to expire in 7 days or less (Not Scored) (Not part of CIS benchmark) [0;39m 
19:11:41  date: invalid date ‘@None’
19:11:41  date: invalid date ‘+%s’"

could be that the error is related to the lines above it?
besides that, I can't see anything that failed that might have caused the exit code 3

**Comment by deanvaturi** [comment]
@toniblyx I have excluded the following "extra730" that gives "date: invalid date ‘@None" and it didn't show in this run, but still fails.
it runs from top to bottom but at the end 
![image](https://user-images.githubusercontent.com/67010637/97114722-e1270d00-16fa-11eb-9a6c-16072bec1260.png)

**Comment by deanvaturi** [comment]
@toniblyx is there a way to print the lines in verbose so I could troubleshoot it?

**Comment by toniblyx** [comment]
sorry @deanvaturi but there is no way to help with the info you provided. First, I don't see what command you run. Second I asked if you can share dump.txt from here https://github.com/toniblyx/prowler/issues/669#issuecomment-712448426. Please, make our work to help you easier. Thanks.

**Comment by deanvaturi** [comment]
@toniblyx the commands I ran are as following 
`rm -rf prowler
git clone https://github.com/toniblyx/prowler
cd prowler
export AWS_PROFILE=dev-prowler
pwd
export AWS_REGION=us-east-1
sudo ./prowler -p Profile1-prowler -r us-east-1 -e -M html
cd output
zip USE1-report.zip *.html`

I cant send you the dump as it is confidential, I can try and go over it line by line and replace the info with XXXX if it helps.

**Comment by toniblyx** [comment]
That is not why I'm asking you. See my previous comments please.

**Comment by deanvaturi** [comment]
@toniblyx "bash -x ./prowler -f eu-central-1 > dump.txt" right? the "2" was a typo?

**Comment by deanvaturi** [comment]
@toniblyx Hi, here is a partial part of the dump which includes all the lines that led to "exit code 3" hope it's good enough. 
[dump.txt](https://github.com/toniblyx/prowler/files/5471072/dump.txt)

**Comment by deanvaturi** [comment]
@toniblyx is there anything else I can help you with in order to solve this issue?

**Comment by deanvaturi** [comment]
@toniblyx your help is much appreciated, thanks in advance

**Comment by toniblyx** [comment]
I did my best, can you try with the latest version of Prowler? Your previous commands are not correct, read README and go little by little. If you need examples on how to run Prowler with CodeBuild just look at here https://github.com/toniblyx/prowler#codebuild-deployment

**Comment by gitbhavesh07** [comment]
@toniblyx , If using docker , I cant archive my artifacts? Is there any way to archive the artifacts (html report)

**Comment by gitbhavesh07** [comment]
Or If not using docker , sh "./prowler -f ap-south-1 -M html" .This runs prowler in a jenkins script 

How to generate the artifact(report) out of it ?. something like ,sh "./prowler -f ap-south-1 -M html  > report.html"

If this is done , then I will archive the artifacts and send the report over an email ,like this

```
    post{
        always{

            archiveArtifacts artifacts: 'report.html',onlyIfSuccessful: true
            emailext attachLog: false, attachmentsPattern: 'report.html', body: 'prowler report', subject: 'Prowler Report', to: 'xxxxxx@gmail.com'
        }
    }

```

**Comment by jfagoagas** [comment]
Please @gitbhavesh07, keep this topic within the discussions here https://github.com/prowler-cloud/prowler/discussions/1447, this issue is already closed and not related with your question.

Thanks!
