### ISSUE TITLE
html report looks poor - not as shown in readme file

### ISSUE THREAD

**Issue by deanvaturi** [prowler-cloud/prowler#670]
Hi,
After prowler is collecting all the needed information from my AWS account, I am trying to export it to HTML file using the following command "-M html" my output doesn't look like the output in the readme example: 
![image](https://user-images.githubusercontent.com/67010637/96727416-b025a000-13bb-11eb-8c62-6d1a01a45e05.png)
 
it looks very poor, as shown in the followed picture (sorry I placed a huge square in the middle, it's for personal security purposes, hope you can get the bigger picture of how it looks like)
![image](https://user-images.githubusercontent.com/67010637/96727985-57a2d280-13bc-11eb-906c-07caad875ffe.png)

is there a way to create a report that looks like the one in the example?
I used "ansi2html" to create a colored one, but it still doesn't look as good as in the picture mentions in the readme file.

thanks in advance.

**Comment by toniblyx** [comment]
are you sure you are using the latest code in master branch?  You are maybe using v2.2 instead of the latest.

**Comment by deanvaturi** [comment]
yes as I am always pulling the latest one 
` rm -rf prowler
                      
git clone https://github.com/toniblyx/prowler `

**Comment by toniblyx** [comment]
I'm afraid that you are doing something I can't control. The latest code in master branch generates the html report showed in README.md inside output folder. `./prowler -V` should show `Prowler 2.3.0RC4`

**Comment by deanvaturi** [comment]
added the output of "./prowler -V"
![image](https://user-images.githubusercontent.com/67010637/96732515-152fc480-13c1-11eb-88ec-b256417daae1.png)

**Comment by toniblyx** [comment]
in that case if you run `./prowler -M html` it creates a html report file inside `prowler/output` folder. It that is not the case please review again all steps to install and test prowler. First run it as `./prowler` to see that works fine. Not sure if I can do much more for you.

**Comment by deanvaturi** [comment]
Hi Toni, seems like the issue was a redirect i have done ("./prowler -p prowler -r eu-central-1 -M html > prowler-report.html"
when I removed the "> prowler-report.html" I managed to find the file that was automatically generated inside of the output folder which was the right one, that looks like the one you showed in the example.
Thank you so much for your tolerance and patience.

**Comment by deanvaturi** [comment]
Is there a way to modify the name of the HTML file that is being created while being created? or it will stick with the "prowler-output-AWSACCOUNTID-YYYYMMDDHHMMSS.format" format? as I create 3 reports one after the other and I need to identify them by their names.
thanks in advance
