### ISSUE TITLE
Prowler is trying to query us-easy-1.amazonaws.com for S3 buckets.

### ISSUE THREAD

**Issue by mattderen** [prowler-cloud/prowler#672]
```
7.3 [extra73] Ensure there are no S3 buckets open to the Everyone or Any AWS user (Not Scored) (Not part of CIS benchmark)
prowler-development,xxxxxxxxxxxx,us-east-1,7.3,INFO,Not Scored,Extra,[extra73] Ensure there are no S3 buckets open to the Everyone or Any AWS user (Not Scored) (Not part of CIS benchmark),Looking for open S3 Buckets (ACLs and Policies) in all regions...
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
prowler-development,xxxxxxxxxx
Could not connect to the endpoint URL: "https://s3.us-easy-1.amazonaws.com/Could?location",7.3,FAIL,Not Scored,Extra,[extra73] Ensure there are no S3 buckets open to the Everyone or Any AWS user (Not Scored) (Not part of CIS benchmark),
Could not connect to the endpoint URL: "https://s3.us-easy-1.amazonaws.com/Could?location": Could bucket is Public!
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
.......
./output/prowler-output-xxxxxxxx-20201025010442.csv:Invalid bucket name ""https://s3.us-easy-1.amazonaws.com/"": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$": "https://s3.us-easy-1.amazonaws.com/" bucket is Public!
```

**Comment by mattderen** [comment]
I have to admit, this one is very bizarre. Your checks are so simplistic with awscli calls I dunno how in the world there could ever be a failure here. us-easy-1 doesn't _seem_ valid, but who knows?

**Comment by mattderen** [comment]
Ah. https://github.com/stedolan/jq/issues/501

**Comment by toniblyx** [comment]
Hi @mattderen I have never seen that type of thing like us-easy-1, have you tried to run prowler as `bash -x ./prowler -c extra73` and see how the get regions work? I don't think you get that region from `aws ec2 describe-regions --query 'Regions[].RegionName'`. I don't see relation with that jq issue.

**Comment by pingoleon108** [comment]
I have the same issue

This is the first part where it start to fail

`+ [[ us-east-1 == \E\U ]]
++ /usr/bin/aws s3api get-public-access-block --profile prowler34 --region us-east-1 --bucket XXX --output json
+ BUCKET_PUBLIC_ACCESS_BLOCK='usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
++ jq -r .PublicAccessBlockConfiguration.RestrictPublicBuckets
parse error: Invalid numeric literal at line 1, column 6
+ ACCOUNTRESTRICTPUBLICBUCKETS=
+ [[ '' == \t\r\u\e ]]
++ /usr/bin/aws s3api list-buckets --query 'Buckets[*].{Name:Name}' --profile prowler34 --output text
`

It's weird because it does not fail for all accounts.

**Comment by toniblyx** [comment]
I don´t see your region set as `us-easy-1` but in the other case it could be a typo in `~/.aws/credentials`  or `~/.aws/config`. 

In order to debug it, could you run `bash -x ./prowler -c extra73` with two different accounts and see what is different? Also try with AWS CLI v1 and v2.

**Comment by toniblyx** [comment]
Since no feedback was provided to debug and clarify this issue I'm closing it. To me that was a typo on config file.
