### ISSUE TITLE
Prowler report with only CIS benchmark

### ISSUE THREAD

**Issue by deanvaturi** [prowler-cloud/prowler#675]
Is there a way of creating a prowler report with only the CIS benchmark (without extras)?
tried "./prowler -E -g extras" with no success.

**Comment by toniblyx** [comment]
if you run `./prowler -h` you will see an option `-e exclude group extras`, that means that if you run `./prowler -e` will run only CIS. you can also see all available groups `-L` and use `-g cislevel1` or cislevel2 depending what you want.

**Comment by deanvaturi** [comment]
thank you
