### ISSUE TITLE
check_extra736 Fails for key policy created by CloudTrail

### ISSUE THREAD

**Issue by grzegorznittner** [prowler-cloud/prowler#679]
The check_extra736 is reporting CMK key created by CloudTrail, the key policy is kind of default, but doesn't seem to expose the key publicly.
https://docs.aws.amazon.com/awscloudtrail/latest/userguide/default-cmk-policy.html

Check 736 only verifies presence of "AWS": "*" which is quite weak check. I suggest check does not report a key which has additional conditions set, as for the keys created by CloudTrail.

Even though check is only warning users about possible issue, it will be better not to report false positives.

**Comment by toniblyx** [comment]
Any idea on how to improve it?

**Comment by grzegorznittner** [comment]
As a very basic improvement we can suppress warning when conditions are applied to the policy's statement, like in the policy created by CloudTrail:
```
        {
            "Sid": "Allow principals in the account to decrypt log files",
            "Effect": "Allow",
            "Principal": {"AWS": "*"},
            "Action": [
                "kms:Decrypt",
                "kms:ReEncryptFrom"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {"kms:CallerAccount": "aws-account-id"},
                "StringLike": {"kms:EncryptionContext:aws:cloudtrail:arn": "arn:aws:cloudtrail:*:aws-account-id:trail/*"}
            }
        },
```

There is a risk the check will not detect misconfigurations, however, currently check verifies that only all AWS Principals are allowed, which is definitely generating false positives.

**Comment by toniblyx** [comment]
This was fixed in https://github.com/toniblyx/prowler/pull/849
