### ISSUE TITLE
checks extra_7116 and extra_7117 fail by default even if aws glue is not used

### ISSUE THREAD

**Issue by ImmoStanke** [prowler-cloud/prowler#687]
As far as I understand, the glue data catalog always exists, regardless of if one uses this service. The default settings are such that checks extra_7116 and extra_7117 fail. So if someone uses prowler, they either have to ignore these checks or change the glue default settings.
Ignoring the checks is problematic because one might forget to re-enable then at the point where one is actually starting to use aws glue.
Changing the default settings is problematic because it means writing unnecessary infrastructure code (unless it is in fact a security issue to leave the default settings of this service even if it's not utilized).

I'm now wondering:
1. Is this intended behavior because this is actually an issue (e.g. because this may leak metadata even if one does not intend to use AWS glue)?
2. If not, is there some way to determine if data is actually potentially leaked? Similar to the other glue checks who don't fail because the resources don't exist. Unfortunately I don't know anything about aws glue so I'm not sure what condition might be sensible.
3. If neither is the case, is it desirable to document (e.g. as a comment in the check files) that the check can be safely ignored if aws glue is not used?

**Comment by toniblyx** [comment]
Thanks for your comments and testing these new Glue checks @ImmoStanke :)

There is a way to improve those two checks, actually if there are no tables, it doesn't make sense to show error if "Metadata encryption" is not enabled, same behavior should be in place for "Encrypt connection passwords" for connections. @ramondiez is working on an enhancement.

**Comment by toniblyx** [comment]
fixed by #692
