### ISSUE TITLE
False positive in check119 when ec2 instance is shutting down

### ISSUE THREAD

**Issue by stku1985** [prowler-cloud/prowler#689]
This happens in our k8s cluster running on spot instances on AWS. When such a cluster reaches a certain number of nodes, this check randomly fails, since there is a small time window when the status is still `shutting-down` but the instance role is already `null`.

A small PR to fix this issue is forthcoming.

**Comment by toniblyx** [comment]
Cool, good point @stku1985. Thanks for the heads up and enhancement!
