### ISSUE TITLE
Rename OK! and WARNING! to PASS! and FAIL! like in other CIS tools

### ISSUE THREAD

**Issue by toniblyx** [prowler-cloud/prowler#69]
Don't know if this is good idea or keep Prowler doing its own way... I think OK! and WARNING! is fine and easy to understand too. Not very important but the change is pretty straightforward, just changing 2 lines of code.

**Comment by MrSecure** [comment]
It might help with #54 to align the terminology with what CIS uses.
👍

**Comment by toniblyx** [comment]
Nice, thanks!

**Comment by crashGoBoom** [comment]
This seems like a really simple change and it would be super helpful. Can I help out and make a PR for this? Thanks @toniblyx !

**Comment by toniblyx** [comment]
Hi @crashGoBoom, I think we could take advantage of all changes for v2.0 and make this change. You can look at the devel branch to see all changes I have done already. I can do this change now, I need to finish some other things and push v2 for beta in few hours or so.  BTW, https://github.com/kindlyops/prowlerCsv2md looks pretty interesting!

**Comment by crashGoBoom** [comment]
@toniblyx man you are on it! Just glancing at some of the changes in v2 and they look great! As always nice work on this. 
Thanks @toniblyx !

**Comment by toniblyx** [comment]
This was done already
