### ISSUE TITLE
extra740 scans showing public ebs snapshots

### ISSUE THREAD

**Issue by caseybecking** [prowler-cloud/prowler#695]
This scan shows all ebs snapshots that are public and there can be a lot that come up. Is there a way to ignore the public snapshots shared with an account?

**Comment by toniblyx** [comment]
Hi @caseybecking, I think yuo are referring to extra72 `7.2 [extra72] Ensure there are no EBS Snapshots set as Public`

**Comment by toniblyx** [comment]
by default it uses `--max-items 100` unless you run prowler with `-m <higher value>`.  Also that check runs this command `aws ec2 describe-snapshots --region REGION --owner-ids ACCOUNTID --output text --query 'Snapshots[*].{ID:SnapshotId}' --max-items 100` hence it shows only snapshots own by the account where the check is being ran. 

If you are really talking about check extra740 it works the same way.

**Comment by toniblyx** [comment]
reading doc, I see that `--owner-ids` can a combination of AWS account IDs, self , and amazon. Not sure if in your case self would make the trick. Can you try and let me know? Thanks.

**Comment by Kirizan** [comment]
@caseybecking are you using a different default output in your .aws/config file? I noticed a similar issues in my scans when the default output was modified. I just submitted issue #696 related to this.

**Comment by caseybecking** [comment]
Interesting yes it may have been config related. After removing the AWS_DEFAULT_OUTPUT="text" from my env variables and leaving it blank i no longer get the notification of failed snaps due to encryption.

**Comment by toniblyx** [comment]
Can you please confirm that? I can confirm that both checks extra740 and extra72 use `--output text` explicit in their code so I doubt it is related to output.

**Comment by caseybecking** [comment]
I just tested a couple version it did not have the issue in RC2 but has the same issue in RC4 & RC5 and it looks to be something with jq possibly. If i add the environment variable of AWS_DEFAULT_OUTPUT="text" to zsh it breaks the output, if i unset it and run the same command the output looks to be fine.

With variable - 
```
./prowler -c check740 -p REMOVED -r us-east-1
jq: error (at <stdin>:1): Cannot index number with string "Account"
parse error: Invalid numeric literal at line 1, column 17
jq: error (at <stdin>:1): Cannot index number with string "Arn"
parse error: Invalid numeric literal at line 1, column 17
jq: error (at <stdin>:1): Cannot index number with string "UserId"
parse error: Invalid numeric literal at line 1, column 17
                          _
  _ __  _ __ _____      _| | ___ _ __
 | '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
 | |_) | | | (_) \ V  V /| |  __/ |
 | .__/|_|  \___/ \_/\_/ |_|\___|_|v2.3.0RC5
 |_| the handy cloud security tool

 Date: Tue 24 Nov 2020 05:57:30 AM PST

 Colors code for results:
 INFO (Information), PASS (Recommended value),  WARNING (Ignored by whitelist),  FAIL (Fix required),  Not Scored

 This report is being generated using credentials below:

 AWS-CLI Profile: [REMOVED] AWS API Region: [us-east-1] AWS Filter Region: [all]
 AWS Account: [] UserId: []
 Caller Identity ARN: []


 7.40 [extra740] Check if EBS snapshots are encrypted (Not Scored) (Not part of CIS benchmark)
       INFO! Looking for EBS Snapshots in all regions...
       FAIL! eu-north-1: snap-066d68b937472d8f2 is currently not encrypted!
       FAIL! eu-north-1: snap-037c7cf91e3e4390d is currently not encrypted!
```
After unseting the variable - 

```
./prowler -c check740 -p REMOVED -r us-east-1
                          _
  _ __  _ __ _____      _| | ___ _ __
 | '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
 | |_) | | | (_) \ V  V /| |  __/ |
 | .__/|_|  \___/ \_/\_/ |_|\___|_|v2.3.0RC5
 |_| the handy cloud security tool

 Date: Tue 24 Nov 2020 05:59:38 AM PST

 Colors code for results:
 INFO (Information), PASS (Recommended value),  WARNING (Ignored by whitelist),  FAIL (Fix required),  Not Scored

 This report is being generated using credentials below:

 AWS-CLI Profile: [REMOVED] AWS API Region: [us-east-1] AWS Filter Region: [all]
 AWS Account: [REMOVED] UserId: [REMOVED]
 Caller Identity ARN: [arn:aws:iam::REMOVED:user/REMOVED]


 7.40 [extra740] Check if EBS snapshots are encrypted (Not Scored) (Not part of CIS benchmark)
       INFO! Looking for EBS Snapshots in all regions...
       INFO! eu-north-1: No EBS Snapshots found
```

**Comment by zfLQ2qx2** [comment]
AWS cli takes output preferences via environment and command line, the question here is that when both are specified, which takes precedence? It sounds like environment does, so maybe we need to unset AWS_DEFAULT_OUTPUT in the prowler startup.

I can reproduce with AWS_DEFAULT_OUTPUT="text" ./prowler -c check740

@toniblyx I raised https://github.com/toniblyx/prowler/pull/725
