### ISSUE TITLE
[: ==: unary operator expected

### ISSUE THREAD

**Issue by virtualjj** [prowler-cloud/prowler#7]
I get the following errors for check112:

1.12 Ensure no root account access key exists (Scored) 
./prowler: line 390: [: ==: unary operator expected
      Found access key 1 
./prowler: line 395: [: ==: unary operator expected
      Found access key 2

![image](https://cloud.githubusercontent.com/assets/10323889/18681056/48619c4c-7fa1-11e6-8e78-81c86cce4537.png)

I have confirmed that my Credential Report is showing FALSE for both access keys.
![image](https://cloud.githubusercontent.com/assets/10323889/18681028/23702e1c-7fa1-11e6-83dc-784d033140eb.png)

I tried changing line 390:

`if [[ $ROOTKEY1 == "false" ]];then`

This removes the unary operator expected message but result is still incorrect:

![image](https://cloud.githubusercontent.com/assets/10323889/18681162/c4fdeb0c-7fa1-11e6-825f-35149f4063ce.png)

It appears that the $ROOTKEY1 and $ROOTKEY2 variables are not populating with a value.

**Comment by toniblyx** [comment]
Hi virtualjj, thanks for testing prowler.

The way it works that check and others in the section 1, is to extract information from a generated report encoded in base64 that has to be dumped to a file (it is not an on-the-fly extraction) with the command:
https://github.com/Alfresco/aws-cis-security-benchmark/blob/master/prowler#L205 that command creates a report and then I dump the report to a file to parse afterwards:
https://github.com/Alfresco/aws-cis-security-benchmark/blob/master/prowler#L214

What I think is happening there is that I missed to support the option -d for the base64 GNU command (linux). I wrote the option for the BSD (osx) command which uses -D option instead. Let me fix it in a little quick.

**Comment by toniblyx** [comment]
Ok, fixed.

**Comment by toniblyx** [comment]
@virtualjj let me know if it runs fine now in order to close the issue. Thanks.

**Comment by virtualjj** [comment]
Thank you very much - works perfectly now. 

![image](https://cloud.githubusercontent.com/assets/10323889/18687071/69c7e0ea-7fb9-11e6-956f-0880e9b8eca0.png)

Thank you so much for putting this together!
