### ISSUE TITLE
Group3 check3x fails on spaces in Filter Name; Filter name is split into multiple parts by space(s)

### ISSUE THREAD

**Issue by sonicshrub** [prowler-cloud/prowler#700]
First off, I find this tool extremely useful and I appreciate the level of effort and generosity involved with giving it to the community.  Thank you!

Running the tool against over 30+ AWS accounts in a large organization. Ideally there would be no spacing in the Filter Names, however we have seen many inconsistencies where spaces are present. 

--AWS Metric Filter---
Filter Name: S3 Event   <----
Filter Pattern:
{ ($.eventSource = s3.amazonaws.com) && (($.eventName = PutBucketAcl) || ($.eventName = PutBucketPolicy) || ($.eventName = PutBucketCors) || ($.eventName = PutBucketLifecycle) || ($.eventName = PutBucketReplication) || ($.eventName = DeleteBucketPolicy) || ($.eventName = DeleteBucketCors) || ($.eventName = DeleteBucketLifecycle) || ($.eventName = DeleteBucketReplication)) }
Metric:  CISBenchmark/S3Event

--Prowler results can be any of group3 checks processed by check3x---
3.8  [check38] Ensure a log metric filter and alarm exist for S3 bucket policy changes (Scored)
       INFO! ***DEBUG*** Metric Filter Name: S3    
       INFO! ***DEBUG*** Metric Filter Name: Event
       FAIL! CloudWatch group CloudTrail/DefaultLogGroup found with metric filter S3 but no alarms associated
       FAIL! CloudWatch group CloudTrail/DefaultLogGroup found with metric filter Event but no alarms associated
       FAIL! CloudWatch group aws-cloudtrail-logs-xxxxxxx  found but no metric filters or alarms associated

--for loop is in check3x appears to be splitting, by spaces, values in $METRICFILTER_SET

 for metric in $METRICFILTER_SET; do

$ for metric in $METRICFILTER_SET; do echo $metric; done
CIS_301_unauthorized_API_calls_Filter
CIS_302_Management_Console_sign-in_without_MFA_Filter
CIS_304_IAM_policy_changes_Filter
S3  <---------------
Event  <-----------------  should be S3 Event
notify_root_login
~$

Could double quotes be applied and then later removed to prevent word splitting ?
https://stackoverflow.com/questions/18383291/loop-over-set-of-strings-containing-spaces

 METRICFILTER_SET=$(echo $METRICFILTER_CACHE | jq -r --arg re "$grep_filter" '.metricFilters[]|select(.filterPattern|test($re))|.filterName' | awk '{print "\""$0"\""}')
 for metric in "${METRICFILTER_SET[@]}"; do
          textInfo "***DEBUG*** Metric Filter Name: $metric"
          metric=$(echo $metric | sed "s/\"/'/g")
          textInfo "***DEBUG**** Metric Filter Remove Quotes: $metric"
          metric_name=$(echo $METRICFILTER_CACHE | jq -r --arg name "$metric" '.metricFilters[]|select(.filterName==$name)|.metricTransformations[0].metricName')

Thank you!

**Comment by toniblyx** [comment]
Closing this one since it is duplicated in #745. Labeled as bug
