### ISSUE TITLE
Push results from one account into a central securityhub account

### ISSUE THREAD

**Issue by fitchtravis** [prowler-cloud/prowler#702]
We have all our accounts pushing securtyhub findings into a central master account.

Is there a way to scan member accounts and push the findings into the master account?

- Travis

**Comment by toniblyx** [comment]
if you have that security hub centralized configuration in place (either with master-member relationship or organizations), any account/region finding that Prowler injects should behave the same way, you don't have to do anything special.

**Comment by fitchtravis** [comment]
Thanks for the feedback. So that means that in each member account one needs to allow for import findings from prowler.

**Comment by toniblyx** [comment]
That is correct. You have to enable Prowler incoming findings on each region you have security have per each account.
You have some sample CLI commands in here to help you do so https://github.com/toniblyx/prowler#security-hub-integration
