### ISSUE TITLE
check27: nothing reported when cloudtrail does not exist

### ISSUE THREAD

**Issue by sonicshrub** [prowler-cloud/prowler#703]
$ aws cloudtrail describe-trails --profile xyz --region us-east-1
{
    "trailList": []
}

$ aws cloudtrail describe-trails --profile xys --region us-east-1 --query 'trailList[].[Name,KmsKeyId]' --output text
$

I believe the while loop is exiting before the if/else conditions can check $trail and $key:
$AWSCLI cloudtrail describe-trails --query 'trailList[].[Name,KmsKeyId]' --output text $PROFILE_OPT --region $REGION | while read trail key; do
    if [[ "$trail" ]] ; then
        if [[ "$key" != "None" ]] ; then
            textPass "KMS key found for $trail"
        else
            textFail "Encryption is not enabled in your CloudTrail trail $trail (KMS key not found)!"
        fi
    else
        textFail "CloudTrail bucket doesn't exist!"
    fi
  done

Could be resolved by adding after check for null after done that flags as a fail or if you prefer an info

done
 if [[ -z "$trail" ]] ; then
      textFail "No CloudTrail to encrypt"
  fi
}

**Comment by toniblyx** [comment]
https://github.com/toniblyx/prowler/issues/704
