### ISSUE TITLE
check22 and check27: nothing reported when cloud trail does not exist 

### ISSUE THREAD

**Issue by sonicshrub** [prowler-cloud/prowler#704]
$ aws cloudtrail describe-trails --profile xys --region $regx --query 'trailList[*].Name' --output text --no-include-shadow-trails
$
similar to check 27, it seems there should be some reporting, either a FAIL or an INFO, to alert that the check cannot be tested because there is nothing to test. 
  
  done
  if [[ -z "$LIST_OF_TRAILS" ]] ; then
                textFail "No CloudTrail to apply log file validation to"
        fi
}

**Comment by toniblyx** [comment]
Hi @sonicshrub, I get what you mean, `check22` needs an `else` in `if [[ $LIST_OF_TRAILS ]];then` with `textFail "No CloudTrail to apply log file validation to"`, in any case the `check21` already checks if there are trails or not.

**Comment by toniblyx** [comment]
This one was fixed here https://github.com/toniblyx/prowler/pull/721
