### ISSUE TITLE
[help wanted] Is it possible to push finding to SecurityHub by assuming role from central account ?

### ISSUE THREAD

**Issue by bkdinoop** [prowler-cloud/prowler#705]
#### Description

We are trying to run security assessment using **_prowler_** on multiple accounts from a central account and push it as finding to security hub of the respective account. We are running prowler in a Fargate from central account and sends the Target account id, IAM role and other parameters as arguments of the docker.

Unfortunately, Prowler is trying to sent the finding to central account's Security hub where the fargate runs. But what i was expecting is to be sent to the securityhub of the target account as it has already assumed to that account.

#### To Reproduce

Docker file I have used is refered from [prowler/utils](https://github.com/toniblyx/prowler/blob/master/util/Dockerfile)

```dockerfile
FROM alpine:latest

ARG USERNAME=prowler
ARG USERID=34000

RUN addgroup -g ${USERID} ${USERNAME} && \
    adduser -s /bin/sh -G ${USERNAME} -D -u ${USERID} ${USERNAME} && \
    apk --update --no-cache add python3 py3-pip bash curl jq file coreutils git && \
    pip3 install --upgrade pip && \
    pip3 install awscli boto3 detect-secrets && \
    git clone https://github.com/toniblyx/prowler

WORKDIR /prowler

RUN chown -R prowler . 

ENTRYPOINT ["./prowler"]
```

Invoking fargate task by sending prowler argument as docker's argument.

```python
ecsClient = boto3.client("ecs")
resp = ecsClient.run_task(
        cluster=FARGATE_CLUSTER,
        launchType="FARGATE",
        taskDefinition=FARGATE_TASK_DEF_NAME,
        platformVersion='LATEST',
        overrides={
            'containerOverrides': [
                {
                    "command": ["-A", "111111111", "-R", "SECAUDITROLE", "-S", "-M","json-asff","-b", "-q","-g", "group4", "-f", AWS_REGION_NAME],
                    "name": "prowler-sechub-task",                    
                }
            ]
        },
        networkConfiguration={
            'awsvpcConfiguration': {
                'subnets': SUBNETS,
                'assignPublicIp': "DISABLED",
                'securityGroups': [SG_ID],
            },
        }
    )
```

**_SECUDITROLE_** has following permission to push to security hub
```
- securityhub:GetFindings
- securityhub:BatchImportFindings
```

And the FARGATE Task role has required permission to assume secudit role.

##### OUTPUT:

Finding are trying to reaching in central account's Security Hub. Since i have disabled the accept finding it fails to push.

If we remove the argument `"-S"` then prowler works fine and findings are generated. The only issue is w.r.t sending to Securityhub.

If I dont assume role `-A and -R` finding are sent properly to Central account's SecurityHub.

Any hint would be very helpful ? 

##### PS:
We are planning to use this fargate along with AWS Batch and do a scheduled scan each accounts in managed, controlled way.

**Comment by toniblyx** [comment]
Thanks @bkdinoop gonna test it and let you know.

**Comment by toniblyx** [comment]
Hi @bkdinoop, in collaboration with @cdemko-mwr we have been testing the templates and looks like the issue is you are not specifiying a specific region with `-r`, your command has to be like:
```
 "command": ["-A", "111111111", "-R", "SECAUDITROLE", "-S", "-M","json-asff","-b", "-q","-g", "group4", "-f", AWS_REGION_NAME, "-r", AWS_REGION_NAME],
```
With that you are filtering region with `-f` and also making sure the API calls are sent to the right region with `-r` otherwise Prowler sents to all regions Security Hubs and fails if they all are not enabled or doesn't have permission.

You can see another way to make it work thanks to the work of @cdemko-mwr with some of your shared content:
https://github.com/cdemko-mwr/prowler-multiaccount/blob/main/prowler-multi-main.yaml#L164

**Comment by bkdinoop** [comment]
Thanks @toniblyx @cdemko-mwr for testing the templates.

But still I got below error even after mentioning `"-r"`

```
ERROR! Security Hub is enabled in eu-west-1 but Prowler integration does not accept findings. Enable it running '/usr/bin/aws securityhub --region eu-west-1  enable-import-findings-for-product --product-arn arn:aws:securityhub:eu-west-1::product/prowler/prowler'. More info: https://github.com/toniblyx/prowler/#security-hub-integration
```
Since it worked for you guys, then it should work for me 😕  

Then I found something interesting. In the central account from where I run fargate, I have disabled the prowler finding. When I enabled there it started to work. It started to push to Security Hub in the correct assumed child account. I again disabled and re checked it stoped sending

_**So I think the check; whether prowler integration is enabled or not is checking the central account but pushing the value to correct account.**_

 I m closing this issue ! If you guys also feel the same way then you can create a different issue with correct heading. 
 
 Thanks a lot guys !! ❤️

**Comment by toniblyx** [comment]
Thanks for clarifying! @bkdinoop are you ok if we take part of your templates as well as part of @cdemko-mwr and put it as part of this repo? It may help other users. Thanks!

**Comment by bkdinoop** [comment]
Sure @toniblyx ! I m happy if its part of this repo so prowler users can find it helpful. 

It would be grateful if you can mention my name as part of author credits. ☺️

**Comment by toniblyx** [comment]
Sure thing, thank you very much!!
