### ISSUE TITLE
Enhance HTML output report - list of enhancements 

### ISSUE THREAD

**Issue by toniblyx** [prowler-cloud/prowler#707]
This was reported in multiple issues by @tekdj7:

1. HTML report - copy/paste lines format messes up
In HTML report, if you copy lines including the header, it pastes perfectly in emails/notes. However, if you copy lines in the middle, where header isn't shown, and paste into email/notes, then formatting messes up. I believe issue is related to when starting to highlight to copy, I can only do it on the cell where it says Pass/Fail, I can't do it on the cell with the icon, thus first line, shows everything shifted back by 1 cell. Yet the subsequent lines in the highlight, do bring over the cell with the icon (though empty), and now everything is shifted to the right by 1 cell.

2.  HTML report - column headers & Show Entries & Search box dissapear as you scroll
In HTML report, as you scroll through the page the column headers, show entries, and search box disappear. They should always remain, even when scrolling through.

3. HTML report - save to pdf, option for landscape not easily available
In HTML report, print & save to pdf, option to change layout to landscape is not easily available. Instead, have to go to More Settings -> Print Using System Dialog, then can change layout. Using Chrome browser. On other websites, when you click Print, immediately an option shows in Chrome to change layout to landscape, before saving to PDF. Or maybe if there's a way to default the website to landscape, when you go to print.

4. HTML report - no colors when saving to PDF in browser
In HTML report, when clicking Print, Save as PDF, the colors for green/red/etc are not showing.

5. HTML report - show table grid/borders
In HTML report, I think it's easier to read, and makes it better when printing or saving out to PDF, if you include the borders around the cells.

6.   HTML report - option to reset sort back to default
In HTML report, provide an option to reset sort back to default

7.  HTML report - allow sort on all columns
In HTML report, allow sort on all columns

**Comment by juliandgon** [comment]
Hey @toniblyx 
Using the latest version, when exporting to html, i don't have any dynamic content (no search box, sorting, etc.).

![image](https://user-images.githubusercontent.com/79880978/109831335-164de980-7c1e-11eb-8cbd-8626f96af591.png)

Do you know what i'm missing?

**Comment by toniblyx** [comment]
That is because for some reason it is not adding the bottom part of the html template. How are you running it? Just -M html?

**Comment by juliandgon** [comment]
Correct, just:
$> ./prowler -M html
Running it from cloudshell

**Comment by toniblyx** [comment]
ok, that can be for two reasons, CloudShell timeout after 20 minutes or so of inactivity or if you have a lot of resources in that account and takes more than 1 hour to Prowler it may struggle to refresh credentials that expire after an hour inside CloudShell. Can you try this and let me know how it goes?

```
# install screen, screen manager with VT100/ANSI terminal emulation
sudo yum install screen -y
# run Prowler in a screen session
screen -dmS prowler sh -c "./prowler -M html"
# Check on screen sessions
screen -ls
# attach to the prowler session
screen -r prowler
# use 'Ctrl+a d' to detach without terminating
 ```

**Comment by toniblyx** [comment]
We are closing this issue. We will take these and other improvements for reporting into consideration for Prowler v3.
