### ISSUE TITLE
Prowler validating check extra774 even after using -e command line option

### ISSUE THREAD

**Issue by ghost** [prowler-cloud/prowler#708]
I am trying to validate my aws infrastructure for all checks excluding extras using below command

./prowler -r eu-central-1 -f eu-central-1 -e -M html

 It is excluding all other extras check but somehow it is including check extra774, Could you please check this and let me know how I can skip this check.

Tried below option but It didn't work

./prowler -r eu-central-1 -f eu-central-1 -e -E extra774 -M html

**Comment by toniblyx** [comment]
Hi @nayabatgithub, if you want to run only CIS related checks you can use group cislevel2 `./prowler -r eu-central-1 -f eu-central-1 -g cislevel2 -M html`. But in this particular case `extra774` is similar to `check13` but with less days. If you don't want to use it remove it from `groups/group1_iam`.

**Comment by ghost** [comment]
Ok got it, thanks.


Thanks
Nayab

**Comment by toniblyx** [comment]
Closing it as it was solved.
