### ISSUE TITLE
[bug] Check extra73 Fail: Message omits bucket name

### ISSUE THREAD

**Issue by urazie1** [prowler-cloud/prowler#713]
The textFail message appears to indicate that there was an access issue but the bucket name is left off or omitted.

Example: "Access Denied Trying to Get Public Access Block for "

If I had to guess, it looks like I'm seeing the output from line 43 in check_extra73, where `$bucket` isn't defined yet.

**Comment by toniblyx** [comment]
Hi @urazie1, thanks for the heads up. First of all make sure you are using the latest version of Prowler from master since line 43 in checks/check_extra73 is empty. Then run prowler as `bash -x ./prowler -c extra73` and see what is the result of the variable `$ALL_BUCKETS_LIST`. It seems to be empty in your case.

**Comment by urazie1** [comment]
I was pulling the latest container from the master branch prior to running, so we got that error using the latest in the master branch (I must have been looking at an older file version when filing the bug report though).

Specifically, the line is now on 48 (from the Sept 2, 2020 commit)
`textFail "Access Denied Trying to get Public Access Block for $bucket"`

If I'm understanding right, I only see $bucket declared further down in the For loop (line 76), which could cause the blank name in the message.

**Comment by toniblyx** [comment]
Prowler gets the list of existing buckets in variable `ALL_BUCKETS_LIST` from line 66 the uses `$bucket` to query each one. If you run prowler with `bash -x` as mentioned before you will see the result of that `aws s3api list-buckets` command and if the error is somehow related to it.

**Comment by zfLQ2qx2** [comment]
@toniblyx I see what he is talking about, I raised https://github.com/toniblyx/prowler/pull/724 to fix

**Comment by toniblyx** [comment]
Ok, it was a matter of the message itself. This is adressed now. Thanks!
