### ISSUE TITLE
Mono report missing headers

### ISSUE THREAD

**Issue by zfLQ2qx2** [prowler-cloud/prowler#717]
I've noticed that mono report doesn't include any headers or context, its just a bunch of pass/fail statements:

```
       PASS! Root user in the account wasn't accessed in the last 1 days
       PASS! No users found with Password enabled and MFA disabled
       PASS! No users with access key 1 older than 90 days
       PASS! No users with access key 2 older than 90 days
       PASS! Password Policy requires upper case
```

With no context as to which check is being run, like you get on the console:

 ```
   1.4  [check14] Ensure access keys are rotated every 90 days or less (Scored)
       PASS! No users with access key 1 older than 90 days
       PASS! No users with access key 1 older than 90 days
       PASS! No users with access key 2 older than 90 days
       PASS! No users with access key 2 older than 90 days
```

If I enable two formats then the headers disappear and I get something like this instead which requires a lot of transformation to get like the above:

```
{"Profile":"ENV","Account Number":"433624884903","Control":"[check14] Ensure access keys are rotated every 90 days or less (Scored)","Message":"No users with access key 2 older than 90 days","Severity":"Medium","Status":"Pass","Scored":"Scored","Level":"Level 1","Control ID":"1.4","Region":"us-east-1","Timestamp":"2021-01-05T19:56:50Z","Compliance":"ens-op.acc.1.aws.iam.4,ens-op.acc.5.aws.iam.3"}
       PASS! No users with access key 2 older than 90 days
       PASS! No users with access key 2 older than 90 days
```

So my question is if the check headers being omitted from the mono report is intentional or a bug? Its something I could work on fixing if the later.

**Comment by toniblyx** [comment]
Hi @zfLQ2qx2! Long time no see :D 

Just tested it using `./prowler -M mono` or `./prowler -M mono,csv` or  `./prowler -M mono,csv,json` and titles are shown, can you share what command are you exactly running?  Probably `./prowler -M json,mono`?
