### ISSUE TITLE
Password checks contradict NIST recommendations

### ISSUE THREAD

**Issue by reubenfirmin** [prowler-cloud/prowler#720]
NIST: Verifiers SHOULD NOT impose other composition rules (e.g., requiring mixtures of different character types or prohibiting consecutively repeated characters) for memorized secrets. Verifiers SHOULD NOT require memorized secrets to be changed arbitrarily (e.g., periodically). However, verifiers SHALL force a change if there is evidence of compromise of the authenticator.

https://pages.nist.gov/800-63-3/sp800-63b.html

-----

Your checks drive behavior counter to that:

 1.5  [check15] Ensure IAM password policy requires at least one uppercase letter (Scored)   
       FAIL! Password Policy missing upper-case requirement 

 1.6  [check16] Ensure IAM password policy require at least one lowercase letter (Scored)   
       FAIL! Password Policy missing lower-case requirement 

 1.7  [check17] Ensure IAM password policy require at least one symbol (Scored)   
       FAIL! Password Policy missing symbol requirement 

 1.8  [check18] Ensure IAM password policy require at least one number (Scored)   
       FAIL! Password Policy missing number requirement

**Comment by zfLQ2qx2** [comment]
@reubenfirmin Those checks (15-18) come from AWS CIS Foundations v1.2.0 parts 1.5 - 1.8. [See here] (https://d1.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf)

The NIST guidance is probably more forward looking - in practice the password recipes and rotation requirement leads to people writing down passwords and other bad habits (I've lost count of the number of places I've been where the password everyone uses is monthYY!, seasonYY!, or companysucksYY!), but in the absence of 2FA and a password manager is probably better than nothing.

**Comment by toniblyx** [comment]
yep, those checks are CIS so if you don't want Prowler to take them into account just remove them from execution with exclude flag `-E` like `./prowler -E check15,check16,check17,check18` or create your own group of checks with those you need and then run it like `./prowler -g yourgroup`.

**Comment by toniblyx** [comment]
I hope this is now more clear, please @reubenfirmin  feel free to reopen it in case you need more information.
