### ISSUE TITLE
Add an option for choosing output directory for reports

### ISSUE THREAD

**Issue by elyrian** [prowler-cloud/prowler#728]
Hi,
I suggest to add an option to select the output directory for the reports. In case the user needs multiple formats, the usage of `$ ./prowler -M html,csv > /my/output` is not possible.

For example : 
`$ ./prowler -M html,csv -o /my/specific/folder`

**Comment by toniblyx** [comment]
Yes! That is very good idea, thanks @elyrian. Something as you mention supporting local filesystem and additionally s3 bucket as `s3://bucket-name/` (in that case it would save report locally and upload it to s3 once it is finished, put object permissions must be added to the role that prowler uses).

Would you be willing to make that new feature? Everything is in `include/output`.

**Comment by elyrian** [comment]
Cool, I'm glad you like the idea, this is the first time I post an issue on Github. 

Ok, I will develop that feature. I already looked for developping the local output and it should be very simple. On the contrary, I never manipulated S3 buckets. I will have a look and let you know if I'm able to develop this part.

**Comment by toniblyx** [comment]
Awesome, let me know if you have any question. Also please, remember to keep the existing behavior as the default one for backward compatibility, in other words. If no output is specified, prowler/output will be use.

**Comment by toniblyx** [comment]
Implemented in the working branch 2.5 https://github.com/toniblyx/prowler/commit/49533de21ba8dbd1f194a8d9a7d842e03107bcb9
