### ISSUE TITLE
No valid ip adress

### ISSUE THREAD

**Issue by Al0ne-collab** [prowler-cloud/prowler#730]
`File /usr/local/lib/python3.9/dist-packages/dispy/__init__.py, line 884, in __init__
    raise Exception('No valid IP address found')
Exception: No valid IP address found
` i got thats error when i execute the program.
`python3 prowler.py`
with root: `./prowler.py`

**Comment by toniblyx** [comment]
Hi @QairexStudio there is not a `prowler.py` file in this repo, are you using a third party wrapper or a different project?

**Comment by Al0ne-collab** [comment]
> Hi @QairexStudio there is not a `prowler.py` file in this repo, are you using a third party wrapper or a different project?

sorry i was not to pay attention it i saw it new np thanks
