### ISSUE TITLE
Prowler excludes some groups when running checks.

### ISSUE THREAD

**Issue by kelvynk01** [prowler-cloud/prowler#735]
./prowler -L

This shows all the checks in prowler. It displays this information in groups. For instance Group 7 belongs to the category titled "extras" while group 21 is titled SOC2 readiness, and groups 1-4 are the CIS level1 benchmarks

./prowler -l
This shows all the checks in each group.
However, this skips groups 8 to 24

Is there any way to actually ensure prowler runs a check on ALL groups 1 to 24? It currently does not go beyond 7

Also, is there a way to exclude only group 7 , while running all checks between 1 and 24 ?

**Comment by toniblyx** [comment]
Hi @kelvynk01, prowler shows all checks when running `./prowler -l` that actually list any check included in any group. then if you want to check existing groups then use `./prowler -L`. To show checks in each group you need to use `./prowler -g group -l` as it is mentioned in `./prowler -h`. To run all checks (included CIS and Extras) just run `./prowler`. To run only cis you have option `-e`. Let me know if it is more clear now. I

**Comment by toniblyx** [comment]
btw, extras 759 and 760 (lambda variables and code secrets finder are not included because they may take too much time). To run detect-secrets with those two checks use `./prowler -g secrets`

**Comment by toniblyx** [comment]
I hope my answer clarified your question, if you need more info please reopen this case and let me know any other related question.

**Comment by kelvynk01** [comment]
Yes, thanks
