### ISSUE TITLE
extra7116 failing after recent commit although Glue is not used

### ISSUE THREAD

**Issue by chbiel** [prowler-cloud/prowler#739]
Hi,
we see the following error in our checks, starting yesterday. Everything was ok on 1st februrary.

It seems to be connected to https://github.com/toniblyx/prowler/commit/e6d175d62e6605f31be392cefadd2e0efbb200d1as this is the only relevant change in that timespan.
We don't use Glue and have not set anything around it.

`7.116 [extra7116] Check if Glue data catalog settings have metadata encryption enabled.    
       FAIL! eu-central-1: Glue data catalog settings have metadata encryption disabled`

You have an idea what the problem could be? Can I help fixing it or give some more information?

**Comment by toniblyx** [comment]
Hi @chbiel, can you run this command and see if you actually have some configuration in place?
`aws glue get-data-catalog-encryption-settings --region eu-west-1 --output text --query DataCatalogEncryptionSettings.EncryptionAtRest.CatalogEncryptionMode` is the output `DISABLED`?

**Comment by chbiel** [comment]
sorry for not getting back earlier.
i checked it for two of our accounts. one fails the check one succeeds.
both give "DISABLED" as the output when running the above command.
we are in "eu-central-1" when that helps (i change your command accordingly before running it and also tried with "eu-west-1")

**Comment by toniblyx** [comment]
Yes, in your case, having resources in `eu-central-1` you have to run `aws glue get-data-catalog-encryption-settings --region eu-central-1 --output text --query DataCatalogEncryptionSettings.EncryptionAtRest.CatalogEncryptionMode`. If you get DISABLED then FAIL in Prowler is the expected result. You can also use https://github.com/toniblyx/prowler#whitelist-or-allowlist-or-remove-a-fail-from-resources to avoid that in your reports.

**Comment by chbiel** [comment]
you have an idea why it fails for one account but succeeds in another with the same output "DISABLED"?

**Comment by toniblyx** [comment]
can you debug it using `bash -x ./prowler -c extra7116` in both accounts and actually see what is different? use `-f your-region` to have quicker response.

**Comment by chbiel** [comment]
big thanks, that hint was helpful!
