### ISSUE TITLE
CSV output has incorrect scored data

### ISSUE THREAD

**Issue by MrSecure** [prowler-cloud/prowler#74]
the third argument to titleText was removed from the not-scored items recently.

One hidden side-effect of the change - that was used to update the flag used to determine if a check was scored. I'll create PR shortly.

**Comment by toniblyx** [comment]
My bad, I didn't read properly the PR at that time. I'll take care next time.

**Comment by MrSecure** [comment]
I think that approach is too subtle, hidden.    A more clear approach is to call a setScored() function before the titleText() call in each check.  That also creates a natural place to add in per-check scoring rules for a future scoring system.

I've got some time to work on that this evening.

**Comment by toniblyx** [comment]
BTW, I added check72 and I'm not sure how to make a proper CSV output of it.

**Comment by MrSecure** [comment]
Thinking the code below to make the 3rd (and added 4th) parameters required for every call to `textTitle` would make it more clear - including the intent of the parameter (rather than 1 vs. 0)

```
check11(){
  ID11="1.1"
  TITLE11="Avoid the use of the root account (Scored)."
  COMMAND11=$(cat $TEMP_REPORT_FILE| grep '<root_account>' | cut -d, -f5,11,16 | sed 's/,/\ /g')
  textTitle "$ID11" "$TITLE11" "SCORED" "LEVEL1"
  textNotice "Root account last accessed (password key_1 key_2): $COMMAND11"
}
```

Reasonable?

**Comment by MrSecure** [comment]
I'd also like to capture the Level in the CSV output to make it accessible downstream - pivot tables, etc.
LEVEL1, LEVEL2, EXTRA
