### ISSUE TITLE
Fix extra714: result is FAIL when CloudFront is configured for real-time logs via Kinesis

### ISSUE THREAD

**Issue by sectoramen** [prowler-cloud/prowler#741]
Consider adding a check for kinesis stream logging before failing this check. See https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/real-time-logs.html

**Comment by toniblyx** [comment]
Thanks @sectoramen good point! That is a new feature that I didn't take into consideration, I think the trick is to see if there is an existing RealtimeLogConfigArn set up for a distribution. This query `aws cloudfront get-distribution --id DISTRIBUTIONID --query Distribution.DistributionConfig.DefaultCacheBehavior.RealtimeLogConfigArn`

**Comment by toniblyx** [comment]
Can you test this one and see if that is somehow what is needed? https://gist.github.com/toniblyx/7c248593c2443e244289a7631305ddf9
