### ISSUE TITLE
Group7_Extras

### ISSUE THREAD

**Issue by oracle85-oss** [prowler-cloud/prowler#743]
Hi, I wonder if you have prowler/groups/group7_extras **Remediation**, please. Thanks

**Comment by toniblyx** [comment]
Hi @oracle85-oss there is no remediation for extras however you main find some AWS Config rules with remediation here https://docs.aws.amazon.com/config/latest/developerguide/remediation.html or here https://asecure.cloud/p/auto_remediation_package/

**Comment by oracle85-oss** [comment]
> Hi @oracle85-oss there is no remediation for extras however you main find some AWS Config rules with remediation here https://docs.aws.amazon.com/config/latest/developerguide/remediation.html or here https://asecure.cloud/p/auto_remediation_package/

Hi, Thank you very much for your help.
