### ISSUE TITLE
Fix check32: fails when metric name contain spaces in it

### ISSUE THREAD

**Issue by ayushme001** [prowler-cloud/prowler#745]
Metric is **Console sign-in without MFA**
and prowler is reading ['Console', 'sign-in', 'without', 'MFA']

```[
  {
    "Account Number": "",
    "Control": "[check32] Ensure a log metric filter and alarm exist for Management Console sign-in without MFA (Scored)",
    "Message": "CloudWatch group aws-cloudtrail-logs-a12sa26a8 found with metric filter **Console** but no alarms associated",
    "Severity": "Medium",
    "Status": "FAIL",
    "Scored": "Scored",
    "Level": "Level 1",
    "Control ID": 3.2,
    "Region": "us-east-2",
    "Compliance": "ens-op.exp.8.aws.trail.4"
  },
  {
    "Account Number": "",
    "Control": "[check32] Ensure a log metric filter and alarm exist for Management Console sign-in without MFA (Scored)",
    "Message": "CloudWatch group aws-cloudtrail-logs-a12sa26a8 found with metric filter **Login** but no alarms associated",
    "Severity": "Medium",
    "Status": "FAIL",
    "Scored": "Scored",
    "Level": "Level 1",
    "Control ID": 3.2,
    "Region": "us-east-2",
    "Compliance": "ens-op.exp.8.aws.trail.4"
  },
  {
    "Account Number": "",
    "Control": "[check32] Ensure a log metric filter and alarm exist for Management Console sign-in without MFA (Scored)",
    "Message": "CloudWatch group aws-cloudtrail-logs-a12sa26a8 found with metric filter **without** but no alarms associated",
    "Severity": "Medium",
    "Status": "FAIL",
    "Scored": "Scored",
    "Level": "Level 1",
    "Control ID": 3.2,
    "Region": "us-east-2",
    "Compliance": "ens-op.exp.8.aws.trail.4"
  },
  {
    "Account Number": "",
    "Control": "[check32] Ensure a log metric filter and alarm exist for Management Console sign-in without MFA (Scored)",
    "Message": "CloudWatch group aws-cloudtrail-logs-a12sa26a8 found with metric filter **MFA** but no alarms associated",
    "Severity": "Medium",
    "Status": "FAIL",
    "Scored": "Scored",
    "Level": "Level 1",
    "Control ID": 3.2,
    "Region": "us-east-2",
    "Compliance": "ens-op.exp.8.aws.trail.4"
  }
]```

**Comment by toniblyx** [comment]
Hi, thanks for the comment. I don´t see an issue in your output, to know more about what is the filter for that check look at this line https://github.com/toniblyx/prowler/blob/138ece153e96fe70a0d758f5b6b77a37443e9177/checks/check32#L48

**Comment by ayushme001** [comment]
I have 2 metric filter one with name "CloudTrail Changes" and another one with name "cloud_trail" as visible in screenshot

![image](https://user-images.githubusercontent.com/28739174/107636129-35e29980-6c92-11eb-81b3-a42dd0dd75cb.png)

but when I run prowler Report for "check35" 

![image](https://user-images.githubusercontent.com/28739174/107636455-abe70080-6c92-11eb-9d83-00865b0fc3de.png)

It return 2 FAIL and 1 PASS 

Prowler taking  "CloudTrail Changes"  not as a single metric filter but 2 different metric filter ie. "CloudTrail" and "Changes", seperating them with whitespaces.

its happening with all the checks associated with metric filter

**Comment by zfLQ2qx2** [comment]
@ayushme001 I see it, the metric name has a space in it and when iterating the group names that is being treated as two groups.

@toniblyx maybe this could be fixed by base64 encoding the metric name and decoding it before the result is used/printed?  Otherwise this would need a larger rewrite of check3x. I can take a shot at it if the approach is ok with you.

Looks like same issue as https://github.com/toniblyx/prowler/issues/700

**Comment by toniblyx** [comment]
@zfLQ2qx2 I think that encoding workaround can make the trick, there are other checks doing similar way.

**Comment by n4ch04** [comment]
@ayushme001 please check https://github.com/prowler-cloud/prowler/tree/PRWLR-26-fix-check-32-fails-when-metric-name-contain-spaces-in-it-745 it should be solved
