### ISSUE TITLE
adding 'Account Name' data field

### ISSUE THREAD

**Issue by mario-platt** [prowler-cloud/prowler#746]
Currently we have in the data model, 'Account number' to differentiate between the different accounts we're running Prowler against. It would make creating dashboards (in Kibana for instance) much easier to interpret if `Account Name` was also part of the data set, namely when dealing with multiple accounts under the same data index

**Comment by toniblyx** [comment]
Hi @mario-platt, thanks for your comment. Prowler gets data from the API, where do you store account name? As far as I know there is not such a parameter unless you are talking about Account Alias https://docs.aws.amazon.com/IAM/latest/UserGuide/console_account-alias.html#AboutAccountAlias or a resource tag. In any case it is pretty easy to add it as part of the CSV or JSON output if needed. I would like to know more about how do you process Prowler and generate dashboards. Thanks.

**Comment by zfLQ2qx2** [comment]
Maybe account name in organizations? though not universal

**Comment by mario-platt** [comment]
@toniblyx I was doing some more research and though the information appears when we login (the different account names) I can't find much on that. https://docs.aws.amazon.com/general/latest/gr/acct-identifiers.html that information relates to aliases (https://docs.aws.amazon.com/IAM/latest/UserGuide/console_account-alias.html) but none of the output of those CLI elements seem to have that info. I'm told that it maybe requires access to the root account ? I thought this would be more locally on the accounts but can't seem to find it

**Comment by zfLQ2qx2** [comment]
@mario-platt Does this command show what you are looking for? aws iam list-account-aliases

**Comment by mario-platt** [comment]
@zfLQ2qx2 that's what I was alluding to in the last comment. it seems that `aws iam list-account-aliases` only provides the output if ran from the root account, and not on the individual accounts under it

**Comment by zfLQ2qx2** [comment]
I spot tested one account and  list-account-aliases does seem to work in the individual accounts, but only for the account where run. Where are you trying to make it appear in the output?

**Comment by mario-platt** [comment]
[
![Screenshot 2021-02-19 at 14 39 56](https://user-images.githubusercontent.com/37125349/108518401-6c3a9d00-72c0-11eb-918c-f3b263a8e19c.png)
](url)

Even though when I login to AWS account I can see the alias there, using list-account-aliases returns empty

**Comment by toniblyx** [comment]
`aws iam list-account-aliases` command doesn't seem to work consistently. I think the one that gives account name consistently is `aws organizations list-accounts --query Accounts[].Name` but only works from the master account so I don't see how to take advantage of it.

**Comment by toniblyx** [comment]
As far as I can see the only way to get the account name (and more details like Id or email) is running this command from the AWS Organizations master account:
`aws organizations list-accounts --query Accounts[].[Name,Id,Email]`
Any member account can run the following command to know if it is part of an organization but can't `list-accounts`:
`aws organizations describe-organization --query Organization.MasterAccountId`
For accounts that are not part of any organization previous command will get error `AWSOrganizationsNotInUseException`.

With that said, it only makes sens to implement this feature if Prowler runs from the Organizations master account and I think that is not very common use case. 

Please, let me know what do you think.

**Comment by mario-platt** [comment]
I would agree with that, thanks for the research you've done into this. It's a bit disappointing but until AWS supports that, there doesn't seem to be much we can do at the individual account level

**Comment by bulebuk** [comment]
```
aws iam list-account-aliases 
{
    "AccountAliases": [
        "my-account-name"
    ]
}
```

I believe the size of AccountAliases can be 0 or 1. 

Ref: https://docs.aws.amazon.com/IAM/latest/APIReference/API_ListAccountAliases.html

**Comment by jfagoagas** [comment]
Hi @bulebuk currently we extract the AWS Account name from the AWS Organizations service if the role passed to Prowler has the `describe_account` and `list_tags_for_resource`. I'm thinking that maybe the IAM `list-account-aliases` could be called as a fallback but I think there is no relationship between the IAM account alias and the AWS Organizations account name and I'm not sure if this can lead to some kind of conflicts. What do you think?
