### ISSUE TITLE
Region is not getting set properly for the AWS Config events

### ISSUE THREAD

**Issue by srikarduplo** [prowler-cloud/prowler#748]
I see the below events in the logs where prowler is suggesting a failure in the AWS Config for the region but the region value is not populated properly.
{
	"prowler": {
		"scored": "Scored",
		"status": "FAIL",
		"aws_account_id": "",
		"prowler_version": "Prowler 2.3.0-22012021",
		"Severity": "Medium",
		"timestamp": "2021-02-12T15:17:44Z",
		"message": "Region could has AWS Config disabled or not configured",
		"Compliance": "ens-op.exp.1.aws.cfg.1",
		"aws_profile": "default",
		"control": "[check25] Ensure AWS Config is enabled in all regions (Scored)",
		"control_id": "2.5",
		"aws_account_alias": "default",
		"level": "Level 1",
		**"region": "could",**
		"Service": "configservice"
	},
	"integration": "prowler"
}

{
	"prowler": {
		"scored": "Scored",
		"status": "FAIL",
		"aws_account_id": "",
		"prowler_version": "Prowler 2.3.0-22012021",
		"Severity": "Medium",
		"timestamp": "2021-02-12T15:17:45Z",
		"message": "Region found has AWS Config disabled or not configured",
		"Compliance": "ens-op.exp.1.aws.cfg.1",
		"aws_profile": "default",
		"control": "[check25] Ensure AWS Config is enabled in all regions (Scored)",
		"control_id": "2.5",
		"aws_account_alias": "default",
		"level": "Level 1",
		**"region": "found",**
		"Service": "configservice"
	},
	"integration": "prowler"
}

**Comment by zfLQ2qx2** [comment]
@srikarduplo Try pulling the latest master and ensure your IAM policy has ec2:DesribeRegions on *, I believe this was fixed in https://github.com/toniblyx/prowler/pull/723

**Comment by toniblyx** [comment]
@srikarduplo  can you confirm if that is already solved? Thanks both!
