### ISSUE TITLE
Fix extra726: doesn't work in GovCloud because needs to be pointed to us-gov-west-1 otherwise use us-east-1

### ISSUE THREAD

**Issue by zanesewell** [prowler-cloud/prowler#758]
Input: prowler -r us-gov-west-1 -f us-gov-west-1 -b -n -q -M json

Error: An error occurred (UnrecognizedClientException) when calling the DescribeTrustedAdvisorChecks operation: The security token included in the request is invalid

Root Cause: check_extra726 is hard-coded to pass in us-east-1 and doesn't account for the GovCloud endpoint us-gov-west-1

Source: https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/customer-supp.html

**Comment by toniblyx** [comment]
Thanks for the heads up, that needs to be fixed. If `us-gov-*` us called as `-r` (API calls) or `-f` (just query that fileterd region) use `us-gov-west-1` otherwise use `us-east-1`.

**Comment by justhereforthecroissants** [comment]
@zanesewell change us-east-1 to $REGION, there are three entries.

**Comment by zanesewell** [comment]
@cajual the trusted advisor endpoint for the entire commercial partition is in us-east-1 and the endpoint for the entire govcloud partition is us-gov-west-1. Making the change you described would fix my issue but would be a breaking change for many other regions. Toni has already described an actual solution above.

**Comment by justhereforthecroissants** [comment]
@zanesewell ah that makes sense, I did not check the endpoint for TA, I just updated my check to switch us-east-1 for us-gov-west-1 per @toniblyx solution.

**Comment by toniblyx** [comment]
This check also needs to be improved by showing only security related checks from Trusted Advisor otherwise is too verbose and may take too long to complete.

**Comment by toniblyx** [comment]
This is already implemented in 2.7
