### ISSUE TITLE
Log checks without permissions to execute

### ISSUE THREAD

**Issue by pablopagani** [prowler-cloud/prowler#759]
The only check I found that it's logging permissions denied is Access Analyzer.
Need to check with "bash -x ./prowler -c check123 -f region"  which checks return an access denied error and what's the error string returned to be able to parse it and add it to the csv output as a FAIL

**Comment by toniblyx** [comment]
That control is available in some checks already. It can be extended to all checks but a bit time consuming. Applying the required and provided role it shouldn't be a problem. I will close this issue for now. Thanks!
