### ISSUE TITLE
Cannot describe regions when assuming role

### ISSUE THREAD

**Issue by HG00** [prowler-cloud/prowler#762]
If a "no permissions" user is used, we need to assume role before getting regions. This should be done after the assumerole check, when it is done before, REGIONS is an UnauthorizedOperation error string which is later split, causing issues. Running this after assumerole allows the user to get ec2:DescribeRegions from the role.

**Comment by toniblyx** [comment]
Hi @HG00, I've been working on that issue as well recently and I've seen your code easier than my local one. I have merged it in branch 2.4 so far. Thanks!
