### ISSUE TITLE
Can -e flag work together with -E flag? 

### ISSUE THREAD

**Issue by NMuee** [prowler-cloud/prowler#764]
Hello, 

Need some help here, wondering if -e and -E can be used together?
I am running prowler with the command below 

`./prowler -r us-east-1 -f us-east-1 -e -E check14,check15,extra767,extra786 -M csv,html`

I would like prowler to run all checks except extras, but there are some check that I would also want them to be excluded.
However, after running the above command, prowler is still performing a complete scan with the -E flag 

Is there a way that I can let prowler to perform scan on all groups except extras together with the -E flag? 

Thank you!

**Comment by toniblyx** [comment]
Currently that could be done by changing the way the function `get_all_checks_without_exclusion` works but probably the quickest way for you to do so is creating your own custom group by following example here https://github.com/toniblyx/prowler/blob/master/groups/groupN_sample.

**Comment by toniblyx** [comment]
This is not going to be implemented, a custom group of checks can be used easier to solve this requirement.
