### ISSUE TITLE
check_extra7102 - missing public IPs

### ISSUE THREAD

**Issue by ghost** [prowler-cloud/prowler#768]
[check_extra7102 in Line 36](https://github.com/toniblyx/prowler/blob/806eaa0b981e28a392a5a2a607a365df150eace9/checks/check_extra7102#L36) tries to get all public IPs. However, it is only getting the elastic IPs. This is also documented in the used [describe-addresses reference ](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-addresses.html).

The solution is to use _describe-network-interfaces_ instead and filter for the PublicIPs. I usually use the following command:
```bash
aws ec2  describe-network-interfaces --query "NetworkInterfaces[*].Association.PublicIp"
```

**Comment by toniblyx** [comment]
Hi @as-km, Thanks for your comment. I have been looking at your command and the one that is used in Prowler and I see the following as you mention:

In Prowler `aws ec2 describe-addresses --query 'Addresses[*].PublicIp'`. In doc describe-addresses: Describes the specified Elastic IP addresses or all of your Elastic IP addresses. (Console EC2 / Network & Security / Elastic IPs). I see that includes all Elastic IPs including those not associated. 

Your suggestion `aws ec2  describe-network-interfaces --query "NetworkInterfaces[*].Association.PublicIp"`. In doc  describe-network-interfaces: Describes one or more of your network interfaces. (Console EC2 / Network & Security / Network Interfaces). I see that includes all Elastic and Public IPs that are associated. 

That means that probably usage of `describe-network-interfaces` may make Prowler more accurate for used interfaces. Would you mind to send a fix to branch 2.4? If you can't, please let me know. Thanks again!
