### ISSUE TITLE
add scoring to html output

### ISSUE THREAD

**Issue by HG00** [prowler-cloud/prowler#771]
It will be handy to have the prowler score added to html output, not just console

**Comment by toniblyx** [comment]
Hi @HG00, the plan is to publish a template to visualize the CSV output (from one or multiple accounts assessments) in Quicksight and eventually in Kibana and Grafana.

Can you please attach a screenshot of your html output to see how it looks like? Thanks!

**Comment by HG00** [comment]
Templates sounds much nicer, but here is what the html scoring i made looks like - poss it can be a colored div showing a percentage? 
![htmlscoring](https://user-images.githubusercontent.com/4258663/113910970-54b46680-97d1-11eb-8170-88721af0e49d.png)

**Comment by toniblyx** [comment]
Ok, this is the new html output since 2.4:

![Screenshot 2021-04-08 at 12 11 26 AM](https://user-images.githubusercontent.com/3985464/113941288-1635a080-97ff-11eb-92cc-64b351b0b18d.png)

**Comment by HG00** [comment]
That looks so much nicer than what I did, thanks!

**Comment by toniblyx** [comment]
it will be merged into master coming from 2.4 branch
