### ISSUE TITLE
Security Hub resource type is always empty

### ISSUE THREAD

**Issue by achdc-1192** [prowler-cloud/prowler#776]
Downloaded prowler just now, updated aws cli `aws-cli/1.19.51 Python/3.7.4 Darwin/19.6.0 botocore/1.20.51`

Ran prowler with the following command:
```
./prowler -f us-west-2 -M json-asff -S -q

,"Resources":[{"Type":"","Id":"AWS::::Account:<ACCOUNT-ID-REDACTED>","Partition":"aws","Region":"us-west-2"}],"Compliance":{"Status":"FAILED","RelatedRequirements":["Software and Configuration Checks"]}}

 ERROR! Failed to send check output to AWS Security Hub

Resource Type is always empty. I'm running with Admin Access.
```
This is happening for all checks

**Comment by toniblyx** [comment]
Thanks @anurag1192, I have tested it as well and it fails also with awscli v2, working on it.

**Comment by toniblyx** [comment]
Please, try from branch 2.4.1, not should be fixed.

**Comment by toniblyx** [comment]
New in master and release 2.4.1
