### ISSUE TITLE
./prowler: line 2: $'\r': command not found

### ISSUE THREAD

**Issue by s1mrankaur** [prowler-cloud/prowler#777]
I am on windows 10 and using cygwin to run Prowler but running into the following error. Help?

```
$ ./prowler
./prowler: line 2: $'\r': command not found
./prowler: line 4: $'\r': command not found
./prowler: line 9: $'\r': command not found
./prowler: line 12: $'\r': command not found
./prowler: line 13: $'\r': command not found
./prowler: line 22: $'\r': command not found
./prowler: line 30: $'\r': command not found
./prowler: line 33: $'\r': command not found
./prowler: line 37: $'\r': command not found
./prowler: line 53: $'\r': command not found
./prowler: line 64: syntax error near unexpected token `$'{\r''
'/prowler: line 64: `usage(){

```

**Comment by zfLQ2qx2** [comment]
@s1mrankaur cygwin is having issue with the unix line endings, see https://stackoverflow.com/questions/43693127/cygwin-r-command-not-found-error for details and solution

**Comment by toniblyx** [comment]
As a workaround you can use the docker container and forget about dependencies, etc.

**Comment by s1mrankaur** [comment]
@zfLQ2qx2  Is it just the prowler file that I will need to convert with notepad++?

**Comment by toniblyx** [comment]
Since there is no more feedback here, closing it. Feel free to reopen it if needed.
