### ISSUE TITLE
Permission Error despite having proper IAM configuration

### ISSUE THREAD

**Issue by ankit82** [prowler-cloud/prowler#780]
Hi, I am receiving below error 
"An error occurred (UnauthorizedOperation) when calling the DescribeInstances operation: You are not authorized to perform this operation"
i have verified everything, policies, credentials.  it is able to verify password policies, IAM users but giving error in listing resources.

what could be the cause? please help.

**Comment by toniblyx** [comment]
I would say that still a problem of permissions. What managed policies are you using? Remember at least SecurityAudit and ViewOnlyAccess.

**Comment by ankit82** [comment]
Yes I aded securityaudit, and viewonlyaccess. for test purpose i gave adminstrator access also to this user. but still receiving same error.

**Comment by toniblyx** [comment]
can you run `aws sts get-caller-identity` and `aws ec2 describe-regions --query 'Regions[].RegionName'`? also share how are you running Prowler?

**Comment by ankit82** [comment]
I was able to successfully run scan .  there is an SCP policy which was preventing this. Thank You.

**Comment by toniblyx** [comment]
Glad to hear that you managed to make it work. Thanks for let me know. I close the issue.
