### ISSUE TITLE
Check security groups query

### ISSUE THREAD

**Issue by jfagoagas** [prowler-cloud/prowler#783]
I am thinking if the following query is correct. Is that so?
```
    SG_LIST=$($AWSCLI ec2 describe-security-groups --query 'SecurityGroups[?length(IpPermissions[?((FromPort==null && ToPort==null) || (FromPort==`20` && ToPort==`21`)) && (contains(IpRanges[].CidrIp, `0.0.0.0/0`) || contains(Ipv6Ranges[].CidrIpv6, `::/0`))]) > `0`].{GroupId:GroupId}' $PROFILE_OPT --region $regx --output text)
```
```
    SG_LIST=$($AWSCLI ec2 describe-security-groups --query 'SecurityGroups[?length(IpPermissions[?((FromPort==`20` && ToPort==`21`)) && (contains(IpRanges[].CidrIp, `0.0.0.0/0`) || contains(Ipv6Ranges[].CidrIpv6, `::/0`))]) > `0`].{GroupId:GroupId}' $PROFILE_OPT --region $regx --output text)
```

If `(FromPort==null && ToPort==null) ||` is not present in the `describe-security-groups` query this control does not fail if the security group has an ingress permission from`0.0.0.0.0/0` to any port. 

I think it is better to check `any open ports to 0.0.0.0/0` on one side and `a specific open port to 0.0.0.0/0" on the other side. 

What do you think about it?

**Comment by toniblyx** [comment]
Hi @jfagoagas, thanks for your comment. However, I'm not sure if I get what you mean. Any open port implicitly includes 21, there is a check that does ANY also  `7.48 [extra748] Ensure no security groups allow ingress from 0.0.0.0/0 or ::/0 to any port`. Do you mean that all of those checks looking for a particular port shouldn't include `(FromPort==null && ToPort==null)` because there is a check that does the same already?

**Comment by jfagoagas** [comment]
That is correct, this is what I mean. I think it is useful but in any case it is redundant because this control is already checked.

In this scenario, I think may be more useful to only set as "Failed" the control that checks for any open ports from internet.

|Type | Protocol | Port range | Source 
|---|---|---|---|
HTTP | TCP | Any | 0.0.0.0/0

**Comment by toniblyx** [comment]
I agree with the redundancy but it makes sense to me. Also any customer can create its own group of checks or disable some checks in particular with `-E` or even using the whitelisting capability in Prowler.

**Comment by jfagoagas** [comment]
I think that create a custom group could be a better solution, thanks Toni.
