### ISSUE TITLE
Monitoring Compliance, Output is shown as "No CloudWatch group found for CloudTrail events" if multi region cloud trail is not present

### ISSUE THREAD

**Issue by cparadkar** [prowler-cloud/prowler#786]
For prowler version 2.2.0 this issue is observed.
The Monitoring Compliance checks when we run, in case if multi region cloud trail is not present, then Output is shown as "No CloudWatch group found for CloudTrail events"

**Comment by toniblyx** [comment]
Hello @cparadkar, could you please be more specific with the command you run, output, expected output, etc? Thanks.

**Comment by cparadkar** [comment]
The monitoring checks. From check 31 to check314. In case if multi region cloud trail is not present, then Output is shown as "No CloudWatch group found for CloudTrail events"

**Comment by cparadkar** [comment]
any update team ?

**Comment by toniblyx** [comment]
Hello, sorry to not to respond earlier but I don't quite get your question, I need more information or there is something wrong since checks 3x don't take cloudtrail multiregion flag into consideration. Please review `include/check3x` file for more information.

**Comment by toniblyx** [comment]
Since no more feedback was provided I'm going to close this one, not clear what the issue was.
