### ISSUE TITLE
allow saving reports with filename based on alias instead of account number

### ISSUE THREAD

**Issue by HG00** [prowler-cloud/prowler#791]
If a lot of accounts are being scanned, it would be handy to be able to save the output using an alias, eg instead of:
prowler-output-123123123-202105060123
we can add an alias to commandline and get something like
prowler-output-mycoolaccountname-123123123-202105060123

(I'd like to work on this, pls let me know if anyone has already started though!)

**Comment by toniblyx** [comment]
Another good idea, please go ahead with it. Probably is time to add support to getopts to process long and short command line options (like `-r` = `--region` or `-f` = `--filter-region` etc...)

**Comment by toniblyx** [comment]
This is available in branch 2.5.1 using the option `-F` see usage (./prowler -h) for more details.
