### ISSUE TITLE
allow symlinking to "latest" output files

### ISSUE THREAD

**Issue by HG00** [prowler-cloud/prowler#792]
After a while the output directory will become quite full. In order to find the file you want, it would be handy to have a -latest file, symlinked to the latest output file. This will just overwrite every time it runs.
I'd like to work on this, please let me know if anyone has already started

**Comment by toniblyx** [comment]
that is a good idea, I'm not aware of anybody working on that.

**Comment by toniblyx** [comment]
Not planning to implement this, just with `ls -ltra` in the output directory you get the latest in tha list. As far as I know, most users process files in many ways in an automated fashion and I don't think this report-latest.extension feature makes sense at this point.
