### ISSUE TITLE
Getting "API: s3:PutBucketPolicy Access Denied" while creating S3bucket.

### ISSUE THREAD

**Issue by Sbhalsing0** [prowler-cloud/prowler#793]
Hello 

I am trying to create S3bucket using ProwlerS3.yaml cloudformation script but getting "API: s3:PutBucketPolicy Access Denied" 
issue when I am trying to create with an AccountID. To resolve it I have removed "BlockPublicPolicy: True" from "PublicAccessBlockConfiguration". Kindly check it once.
Also let me know if I have missed anything or is there any other way to fix the PutBucket policy issue. 

Thanks for your help.
SanketBhalsing

**Comment by toniblyx** [comment]
@tekdj7 can you help on this please?

**Comment by Sbhalsing0** [comment]
@tekdj7 can you please help in this issue?

**Comment by Sbhalsing0** [comment]
Thanks.

**Comment by toniblyx** [comment]
The template is correct, its execution may fail like in this particular case based on other restrictions but not for the template itself.
