### ISSUE TITLE
Provide command line options for the report location and report file name 

### ISSUE THREAD

**Issue by yangsec888** [prowler-cloud/prowler#795]
The prowler main command does not provide a mean for user to specify the report location and report file name currently. By default, "output" directory would be the location, "prowler-output-${ACCOUNT_NUM}-${OUTPUT_DATE}" would be the report name.

It would be ideal that user has the options to overwrite the above default behavior.

**Comment by toniblyx** [comment]
Hi @yangsec888, thanks for your contribution, option for custom directory is implemented already in branch 2.5, give it a look here https://github.com/toniblyx/prowler/commit/49533de21ba8dbd1f194a8d9a7d842e03107bcb9.
Could you please send the file name option to branch 2.5? Thanks again!

**Comment by yangsec888** [comment]
Hi @toniblyx the file name option was sent to branch 2.5. Please review when you have the chance.

**Comment by yangsec888** [comment]
Hi @toniblyx the file name option was resent to branch 2.5. Please review it again when you have the chance. Best
