### ISSUE TITLE
Codebuild Issue

### ISSUE THREAD

**Issue by brendan-s1** [prowler-cloud/prowler#804]
Hello, while running the latest version in CodeBuild (from the CF template provided) i get the following error message towards the end of the build:

`
[Container] 2021/05/26 01:57:02 Command did not exit successfully ./prowler $PROWLER_OPTIONS exit status 3
978 | [Container] 2021/05/26 01:57:02 Phase complete: BUILD State: FAILED
979 | [Container] 2021/05/26 01:57:02 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: ./prowler $PROWLER_OPTIONS. Reason: exit status 3
980 | [Container] 2021/05/26 01:57:02 Entering phase POST_BUILD
981 | [Container] 2021/05/26 01:57:02 Running command echo "Uploading reports to S3..."
982 | Uploading reports to S3...
983
<br class="Apple-interchange-newline">`

My build options are as follows:
`-g cislevel2 -M text, junit-xml,html`

Please advise.

**Comment by w0rmr1d3r** [comment]
Hello @brendan-s1 !
Could it be due to having a whitespace between the `text,` and `junit-xml` ?

**Comment by toniblyx** [comment]
Hello, yes, I agree with @w0rmr1d3r, that won´t work if it has space. the only flag that supports spaces is `-f` (filter regions) that for more than one region can be like `-f 'us-east-1 us-east-1'`, any other flag is comma separated.

**Comment by brendan-s1** [comment]
I changed the params to only include:
`-g cislevel2 -M html`
And i'm still getting that same error message.

**Comment by toniblyx** [comment]
Ok, my bad (I didn't read your full error). That is a codebuild phase error due to errors (fails) from Prowler, so if you run prowler and you get at least one FAIL from prowler, the build will fail that is why you get:
```
[Container] 2021/05/25 13:54:45 Command did not exit successfully ./prowler $PROWLER_OPTIONS exit status 3
[Container] 2021/05/25 13:54:45 Phase complete: BUILD State: FAILED
[Container] 2021/05/25 13:54:45 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: ./prowler $PROWLER_OPTIONS. Reason: exit status 3
```

So for example try running prowler with a check that pass and right afterwards run echo $? and you will get a 0. If you do the same with a check that ends with a fail echo $? will give you a 3.

In order to change that behavior you can try something like this in the parameters:
` -c check32 -M csv,html && echo OK || echo FAILED`
That will make CodeBuild to to give you a 0, so it will finish fine any time.

**Comment by brendan-s1** [comment]
I tried it, the way you have it and still get:

`

4.2  [check42] Ensure no security groups allow ingress from 0.0.0.0/0 or ::/0 to port 3389 (Scored)
--
971 | &nbsp;
972 | 4.3  [check43] Ensure the default security group of every VPC restricts all traffic (Scored)
973 | &nbsp;
974 | 4.4 [check44] Ensure routing tables for VPC peering are "least access" (Not Scored)
975 | &nbsp;
976 | [Container] 2021/05/26 13:11:58 Command did not exit successfully ./prowler $PROWLER_OPTIONS exit status 3
977 | [Container] 2021/05/26 13:11:58 Phase complete: BUILD State: FAILED
978 | [Container] 2021/05/26 13:11:58 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: ./prowler $PROWLER_OPTIONS. Reason: exit status 3
979 | [Container] 2021/05/26 13:11:58 Entering phase POST_BUILD
980 | [Container] 2021/05/26 13:11:58 Running command echo "Uploading reports to S3..."
981 | Uploading reports to S3...
982 | &nbsp;
983 | [Container] 2021/05/26 13:11:58 Running command aws s3 cp --sse AES256 output/ s3://$BUCKET_REPORT/ --recursive
984 | Completed 256.0 KiB/344.1 KiB (3.4 MiB/s) with 1 file(s) remaining
985 | Completed 344.1 KiB/344.1 KiB (2.1 MiB/s) with 1 file(s) remaining

`

The configuration:
`-g cislevel2 -M html && echo OK || echo FAILED`

**Comment by toniblyx** [comment]
can you try from the command line and right afterwards run `echo $?` to see what is the exit?

**Comment by toniblyx** [comment]
This is fixed in PR https://github.com/toniblyx/prowler/pull/865 currently in branch 2.4.1.
