### ISSUE TITLE
Checks for ISO 27001

### ISSUE THREAD

**Issue by w0rmr1d3r** [prowler-cloud/prowler#805]
Hello!
I haven't found any issue related to this (maybe I didn't search enough?).
The thing is, are there any group checks regarding [ISO 27001](https://en.wikipedia.org/wiki/ISO/IEC_27001).

I haven't found any discussions in this repo.

Thank you anyways! The project is awesome!

**Comment by toniblyx** [comment]
Hi @w0rmr1d3r you can list all existing groups with `./prowler -L` and content of any group with `./prowler -g groupId -l`. There is actually a group called iso27001 :)

**Comment by w0rmr1d3r** [comment]
Thank you @toniblyx ! 
Indeed it exists:
`18.0 ISO 27001:2013 Readiness - ONLY AS REFERENCE - [iso27001] *****`
