### ISSUE TITLE
Error when executing group secrets

### ISSUE THREAD

**Issue by w0rmr1d3r** [prowler-cloud/prowler#806]
When executing the group secrets (with or without the `-m` option), when reaching the lambda section, an error appears saying:
`[scan]	ERROR	No plugins to scan with!`

Everything was being scanned fine, until it reached that point. Did I miss anything? Some requirements maybe?

After those errors (a lot of them, trust me), Prowler keeps scanning just fine actually.

Executed Prowler like this:
`./prowler -g secrets -m 200`
`./prowler -g secrets`

Thank you!

**Comment by toniblyx** [comment]
Hi @w0rmr1d3r, message`[scan] ERROR No plugins to scan with!` is not coming from Prowler, it should be from detect-secrets, the module that Prowler uses underneath. Look at here https://github.com/toniblyx/prowler/blob/master/include/secrets_detector and see how it is used, you can try manually as in line 44 and see if you get any result. I wonder if latest version of detect-secrets has some issues with plugins, they are all enabled by default but you can check it out with `detect-secrets scan --list-all-plugins`, more info here https://github.com/Yelp/detect-secrets#viewing-all-enabled-plugins

**Comment by w0rmr1d3r** [comment]
Hi @toniblyx !
I found more info!
The plugins are all installed, because running `detect-secrets scan --list-all-plugins` it prompts all the plugins.

So the issue must be with the lambdas.
I ran checks `extra759` (Lambda variables) and `extra760` (Lambda code). Like this:
`./prowler -c extra759` and `./prowler -c extra760`

The first one works just fine, it's the second one that gives that error. 
Could it be due to the lambda function code being too large? Sometimes in AWS, if the lambda code is too large it isn't shown in the Console.

**Comment by toniblyx** [comment]
I know what is going on, if you run `bash -x ./prowler -c extra760 -f <region>` (the region part is to make sure it takes less time to finish since it does only your desired region). You will see the command that prowler runs underneath and then how detect-secrets fails when trying to analyze a zip file. I need to see what is wrong with it

**Comment by w0rmr1d3r** [comment]
I ran that, what it does, it downloads the zip file and unzips it in the tmp folder `./secrets-ACCOUNT_ID/` inside where the repo is (that's where I'm executing Prowler from).
When it unzips it, is when it prompts the messages.

The command Prowler is executing is:
```
detect-secrets scan --hex-limit 3.0 --base64-limit 4.5 --all-files ./secrets-ACCOUNT_ID/unziped_folder
```
Of course, replace `ACCOUNT_ID` and `unziped_folder` with correct values.
I tried to redirect the output (stdout and stderr) with `COMMAND_FROM_ABOVE &> output.txt`.
And opened that file, it just prompts the messages `[scan]	ERROR	No plugins to scan with!` and at the end it shows this:
```
{
  "version": "1.1.0",
  "plugins_used": [
    {
      "name": "ArtifactoryDetector"
    },
    {
      "name": "AWSKeyDetector"
    },
    {
      "name": "AzureStorageKeyDetector"
    },
    {
      "name": "Base64HighEntropyString",
      "limit": 4.5
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "name": "CloudantDetector"
    },
    {
      "name": "HexHighEntropyString",
      "limit": 3.0
    },
    {
      "name": "IbmCloudIamDetector"
    },
    {
      "name": "IbmCosHmacDetector"
    },
    {
      "name": "JwtTokenDetector"
    },
    {
      "name": "KeywordDetector",
      "keyword_exclude": ""
    },
    {
      "name": "MailchimpDetector"
    },
    {
      "name": "NpmDetector"
    },
    {
      "name": "PrivateKeyDetector"
    },
    {
      "name": "SlackDetector"
    },
    {
      "name": "SoftlayerDetector"
    },
    {
      "name": "SquareOAuthDetector"
    },
    {
      "name": "StripeDetector"
    },
    {
      "name": "TwilioKeyDetector"
    }
  ],
  "filters_used": [
    {
      "path": "detect_secrets.filters.allowlist.is_line_allowlisted"
    },
    {
      "path": "detect_secrets.filters.common.is_ignored_due_to_verification_policies",
      "min_level": 2
    },
    {
      "path": "detect_secrets.filters.heuristic.is_indirect_reference"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_likely_id_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_lock_file"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_not_alphanumeric_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_potential_uuid"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_prefixed_with_dollar_sign"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_sequential_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_swagger_file"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_templated_secret"
    }
  ],
  "results": {},
  "generated_at": "2021-05-31T06:33:38Z"
}
```

Hope it helps!

**Comment by toniblyx** [comment]
`[scan] ERROR No plugins to scan with!` is given when the zip file is in the folder. Seems like detect-secrets is not working as it was before. Looking at it.

**Comment by toniblyx** [comment]
I found the issue, seems to be a matter of python version https://github.com/Yelp/detect-secrets/issues/452

**Comment by w0rmr1d3r** [comment]
I checked my versions and guess what:
```
> detect-secrets --version
1.1.0
> python3 --version
Python 3.9.5
```
I prefer to wait for the issue Yelp/detect-secrets#452 to get resolved and fixed instead of forcing a downgrade in some dependencies, either that or we force prowler to use version 1.0.3 of detect-secrets until it gets solved.

**Comment by toniblyx** [comment]
Just tested with
```
$ detect-secrets --version
1.0.3
$ python --version
Python 3.9.4
```

so `pip install detect-secrets==1.0.3` made the trick so far.

**Comment by w0rmr1d3r** [comment]
Correct!
I reinstalled detect-secrets with:
```
$ pip3 install detect-secrets==1.0.3
$ detect-secrets --version
1.0.3
$ python3 --version
Python 3.9.5
```

Executed:
```
./prowler -c extra760 -f eu-west-1
```

And isn't showing the error from before.
Shall we keep this issue open until it gets fixed from Yelp? What should we do here @toniblyx ?

Thanks!

**Comment by toniblyx** [comment]
To close it we should add that version constraint to the README, Dockerfile and Pipfile. Otherwise better to keep it open.

**Comment by w0rmr1d3r** [comment]
Okai! Let's keep it open!

**Comment by toniblyx** [comment]
It looks like that the Yelp library is no longer maintained and there is a better handled fork maintained by IBM now.

More info:
https://github.com/Yelp/detect-secrets/issues/473
https://github.com/IBM/detect-secrets

The command to install the one from the fork and to update README, Dockerfile and Pipfile is:
`pip install --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"`

**Comment by toniblyx** [comment]
Somehow related to https://github.com/toniblyx/prowler/issues/806

**Comment by w0rmr1d3r** [comment]
True!
I saw this comment -> https://github.com/Yelp/detect-secrets/issues/473#issuecomment-888423120
I don't know if the IBM fork is reliable enough.

What about using https://github.com/Skyscanner/whispers or https://github.com/zricethezav/gitleaks ?
Can any of those projects replace Yelp/detect-secrets ?

Cheers!

**Comment by toniblyx** [comment]
We have done some tests with the IBM fork and seems pretty good, stable and it is active so the idea is to switch to that one and adapt documentation accordingly.

`whispers` seems to be a potential candidate to replace detect-secrets but I would keep it as it is now since it works fine using the IBM fork. I have detected false positives thoug, for example in these cases:

- Random strings generated from CloudFormation created resources like in: `arn:aws:secretsmanager:us-east-1:123456789012:secret:DBkey-jNwT8bfXoSL6-53YNmj` (in a Lambda variable) That string is not a secret at all but the heuristic of detect-secrets get it as it is.
- In an EC2 user data detects as secret the string after `ssh_authorized_keys` which is the ssh public key and shouldn't be taken as secret.

**Comment by w0rmr1d3r** [comment]
Perfect @toniblyx !

I believe this issue can be closed once the migration to the IBM fork is done.

Thank you!

**Comment by toniblyx** [comment]
I have updated README.md, util/Dockerfile and Pipfile with the proper version.
