### ISSUE TITLE
html output file not being generated properly

### ISSUE THREAD

**Issue by s1mrankaur** [prowler-cloud/prowler#809]
Here's the command I am running:

`./prowler -c check310 -M html > sandboxoutput.html`

This is what my HTML file renders as in the browser:
`
This report is being generated using credentials below: AWS-CLI Profile: [1;33m[default][0;39m AWS API Region: [1;33m[us-west-2][0;39m AWS Filter Region: [1;33m[all][0;39m AWS Account: [1;33m[parse error: Invalid numeric literal at line 1, column 8][0;39m UserId: [1;33m[parse error: Invalid numeric literal at line 1, column 8][0;39m Caller Identity ARN: [1;33m[parse error: Invalid numeric literal at line 1, column 8][0;39m [0;34m 3.10 [0;39m [check310] Ensure a log metric filter and alarm exist for security group changes (Scored)`

This is what I see in the text editor:

```

 This report is being generated using credentials below:

 AWS-CLI Profile: [1;33m[default][0;39m AWS API Region: [1;33m[us-west-2][0;39m AWS Filter Region: [1;33m[all][0;39m
 AWS Account: [1;33m[parse error: Invalid numeric literal at line 1, column 8][0;39m UserId: [1;33m[parse error: Invalid numeric literal at line 1, column 8][0;39m
 Caller Identity ARN: [1;33m[parse error: Invalid numeric literal at line 1, column 8][0;39m


[0;34m 3.10 [0;39m [check310] Ensure a log metric filter and alarm exist for security group changes (Scored)   



```

How do I get it to output a formatted HTML report? The AWS profile is configured and the tool is able to run okay , just the reports are messed up.

**Comment by s1mrankaur** [comment]
@toniblyx  Tried that as well. The output folder only has `prowler-output-parse` file and no HTML files.  When I run the command:

`./prowler -c check310 -M html
`
This is what I get:
```

/prowler $ ./prowler -c check310 -M html
./include/outputs: line 54: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect

 This report is being generated using credentials below:

 AWS-CLI Profile: [default] AWS API Region: [us-west-2] AWS Filter Region: [all]
 AWS Account: [parse error: Invalid numeric literal at line 1, column 8] UserId: [parse error: Invalid numeric literal at line 1, column 8]
 Caller Identity ARN: [parse error: Invalid numeric literal at line 1, column 8]


 3.10  [check310] Ensure a log metric filter and alarm exist for security group changes (Scored)
parse error: Invalid numeric literal at line 1, column 8
./include/outputs: line 387: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 388: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 389: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 390: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 391: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 392: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 393: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 394: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 395: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 396: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 397: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 398: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 399: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 400: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 401: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./include/outputs: line 402: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
./prowler: line 635: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
```

**Comment by toniblyx** [comment]
could you please try with the latest version from master? I just tested it and it works fine. Also make sure you have all needed dependencies (error `parse error: Invalid numeric literal at line 1, column 8` is probably due to lack of `jq` package installed), please review https://github.com/toniblyx/prowler#requirements-and-installation

**Comment by s1mrankaur** [comment]
@toniblyx I am using this docker: https://hub.docker.com/r/toniblyx/prowler . I am on a windows machine and jq package is installed on the container. Had logged in as user=root and ran `apk add jq` to install the package.

**Comment by toniblyx** [comment]
if you are using that docker container you don't need to install anything, it is installed already. Can you please let me know how to reproduce your error using the container? I mean, following instructions like here should be fine https://github.com/toniblyx/prowler#codebuild-deployment (see the docker examples), change `"-c check310"` for whatever options you need.

**Comment by s1mrankaur** [comment]
@toniblyx 

I ran aws configure to set up the profile and then the prowler command

` ./prowler -c check310 -M html`

This is all I have to reproduce. I added the check just so that execution would not take too long. The behavior is the same with this check and others.

**Comment by toniblyx** [comment]
You can try with `bash -x ./prowler -c check310 -M html` to see what is actually failing.

**Comment by eprothro** [comment]
I had this same issue. It seemed the parsing of the AWS output was suspect. 

I was using a profile in `~/.aws/credentials` that had no matching profile in `~/.aws/config` (using separate STS profile). Once I added a matching prifle in the config file with an `output` field, things worked properly.

Strangely, reverting back to the original setup did not reproduce the issue. So, unsure if this is a red herring, or if aws client caches profile config or something, but figured I would mention.

**Comment by toniblyx** [comment]
I´ve been looking at this one a couple of times and I think it is the way Prowler handles or discover who is running it, basically this: https://github.com/toniblyx/prowler/blob/master/include/aws_profile_loader#L19-L47 I still would like to see the debug information to confirm if it is the same.

**Comment by eprothro** [comment]
I wish I could provide it, but I can no longer reproduce.

A sample of my original output when I saw the error, where the parse error occurs where I would expect to see the AWS account number:

```
./include/outputs: line 384: ${OUTPUT_FILE_NAME}.$EXTENSION_HTML: ambiguous redirect
redacted-profile-name,parse error: Invalid numeric literal at line 1, column 6,us-east-2,1.3,PASS,Scored,Level 1,[check13] Ensure credentials unused for 90 days or greater are disabled (Scored),User redacted has used access key 2 in the past 90 days,ens-op.acc.1.aws.iam.3 ens-op.acc.5.aws.iam.4,Medium,iam,AwsIamUser,Software and Configuration Checks/Industry and Regulatory Standards/CIS AWS Foundations Benchmark,AWS IAM users can access AWS resources using different types of credentials (passwords or access keys). It is recommended that all credentials that have been unused in 90 or greater days be removed or deactivated.,Use the credential report to  ensure password_last_changed is less than 90 days ago.,https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_getting-report.html,IAM
```

**Comment by toniblyx** [comment]
Please, provide feedback if you still have this issue and feel free to reopen it. Helpful information here https://github.com/toniblyx/prowler/issues/905#issuecomment-958965727

**Comment by pgrabarczyk** [comment]
I had the same issue using the non-docker version (just clone it).

```bash
$ bash prowler -V
Prowler 2.7.0-24January2022
```

I solved it by installing **jq**.
```bash
sudo apt-get install jq
```
