### ISSUE TITLE
Prowler Report Not Able to Generate

### ISSUE THREAD

**Issue by amandalam2000** [prowler-cloud/prowler#810]
Hi,
When I try to run a remote a report using `./prowler -M csv -f us-east-1 > test.csv` after logging into my AWS account I get the following error: [Errno 2] No such file or directory. Then, it says 0.1 Generating AWS IAM Credential Report. It gets stuck here for a while before eventually finishing without any additional errors. When I go to the csv report, I just get a csv with one row for the first test that it checked. Any help on why it won't run through all the tests?

**Comment by w0rmr1d3r** [comment]
Hello @amandalam2000 ,
Where are you running Prowler from? inside an EC2 instance? inside a CodeBuild?

Where are you trying to save that report? I believe that it's not necessary to run the output into a file, because Prowler already outputs that into a folder.

Cheers!

**Comment by toniblyx** [comment]
First: Prowler comes with a builtin report generator, you don't have to redirect output to any file. Using `./prowler -M csv -f us-east-1` will generate a csv file inside `prowler/output` directory.

Make sure you have all dependencies available for Cygwin, in case of doubt use Docker in Windows. You can also run it as `bash -x /prowler -M csv -f us-east-1` to really see where it gets stuck and why.
