### ISSUE TITLE
[extra7132, extra7133, extra7113] Fails for DocumentDB instances

### ISSUE THREAD

**Issue by h1008** [prowler-cloud/prowler#811]
Hi,

the rds describe-db-instances command (as used by the checks extra7132, extra7133, and extra7113) also lists DocumentDB instances which do not support enhanced monitoring/multi-AZ/deletion protection [1]. So these checks fail if you have a DocumentDB cluster and it's not possible to fix the checks.

Proposed solution: 

- Filter output of describe-db-instances command to ignore DB Instances with Engine "docdb". 
- Add a specific check for deletion protection for docdb clusters (using the command docdb describe-db-clusters).

[1] DocumentDB does support deletion protection, but it's a configuration option for clusters, not individual instances. See result of docdb describe-db-clusters.

**Comment by toniblyx** [comment]
Thanks for let me know, in the meantime you can use the whitelist feature to prevent that fail.

**Comment by toniblyx** [comment]
Can you please try changing the checks with this query instead and see if that fixes the issue? `--query 'DBInstances[?Engine != `docdb`].DBInstanceIdentifier'`. If it does please, feel free to send a PR with a fix. Thanks

**Comment by h1008** [comment]
It almost worked - I just had to set the string in single quotes:  `--query "DBInstances[?Engine != 'docdb'].DBInstanceIdentifier"`.
I'll prepare a PR.
