### ISSUE TITLE
WAF CLASSIC(v1) Rules for Protected Resources

### ISSUE THREAD

**Issue by kamiryo** [prowler-cloud/prowler#814]
I checked the rules regarding the activation of WAF and found the following differences.
Shouldn't the ALB also be evaluated for WAF Classic attachments, like the other rules?

[extra7129] :ALB→WAFv2 only 
[extra744]:API Gateway→WAF CLASSIC and WAFv2
[extraextra773]:CloudFront→WAF CLASSIC and WAFv2

**Comment by toniblyx** [comment]
Your are right, just realized, thanks for the heads up! Can you fix it and send a PR? Otherwise I will add it to the backlog. Thanks again!

**Comment by toniblyx** [comment]
This was implemented already.
