### ISSUE TITLE
How does versioning work?

### ISSUE THREAD

**Issue by w0rmr1d3r** [prowler-cloud/prowler#818]
Hello @toniblyx !
Last Thursday I was using Prowler, when I came with the option `-V`, which shows Prowler version.
I'm using Prowler with the master branch (v2.4.1) but the command outputs:
```
$ ./prowler -V
Prowler 2.4.0-07042021
```

I can see that the line in the code was edited on the date it says, then, what about git tags?

Thanks!

**Comment by toniblyx** [comment]
This is a embarrassing (for me) question, I need to see how to improve that tagging process and automate it. Any help is appreciated.

**Comment by w0rmr1d3r** [comment]
Hello @toniblyx !
I've been investigating how Prowler could use versioning a little bit better, do you happen to be familiar with these concepts:
https://www.toptal.com/software/trunk-based-development-git-flow
Trunk based & Git Flow ?

I think that we should first adapt how do we work with git and its branches, before modifying the `-V` option of Prowler.
Because the development flow we are using it's a little bit different than, for instance, gitflow. If we first (after v2.5) adapt to gitflow, then, I think that adapting or modifying the `-V` option would be easier. It could be just a `git` command such as:
* `git describe --tags --abbrev=0`
or
*  `git describe --tags`

Any thoughts on it?

Cheers!

**Comment by toniblyx** [comment]
Since this is not a feature but more a versioning management issue, I'm closing it. We are going to improve this process for sure.
