### ISSUE TITLE
Fix: add condition to avoid run checks 11, 113, 114, 115, 117, 118, 33 in GovCloud since there is no root

### ISSUE THREAD

**Issue by justhereforthecroissants** [prowler-cloud/prowler#823]
Title --

Currently manually omitting these checks, would like it to automatically pick up the region.

For #758 adding $REGION seems to work fine (-r us-gov-west-1)

**Comment by toniblyx** [comment]
Thanks, can you provide the command you are using and exact error? And yes, for GovCloud or China regions, usage of `-r  <region>` (us-gov-west-1) is mandatory since will send API calls to that region, `-f <region>` will filter only that region.

**Comment by toniblyx** [comment]
This is documented here https://github.com/toniblyx/prowler#govcloud, please let me know if it fails even with that.

**Comment by justhereforthecroissants** [comment]
@toniblyx I apologize, I misspoke in my OP, I did use `-r` and not `-f`. Yes, it still looks for root.

This is also an issue on other scanners, like Aqua Wave. I'm currently just filtering out any check that requires `root` or `billing` since those are handled at the commercial layer.

**Comment by justhereforthecroissants** [comment]
@toniblyx 

`aws iam get-account-summary --region us-gov-east-1 --output json`

will output the following:

```
{
    "SummaryMap": {
        "AccountMFAEnabled": 0
    }
}
```

However, there is no `root` account for GovCloud. You should include a flag that checks for `region` in *any* GovCloud region and then drop these checks.

Honestly, all the following are failures and/or unavailable for GovCloud:

- check113
- check114
- check115
- check117
- check118

**Comment by toniblyx** [comment]
Thanks @cajual, do you mean that if it is `us-gov-west-1` and `us-gov-east-1` in following checks:

```
1.13 iam [check113] Ensure MFA is enabled for the root account [Critical] [group1, cislevel1, cislevel2, gdpr, hipaa, pci, iso27001, ffiec, soc2]
1.14 iam [check114] Ensure hardware MFA is enabled for the root account [Critical] [group1, cislevel2, gdpr, pci, iso27001]
1.15 support [check115] Ensure security questions are registered in the AWS account [Medium] [group1, cislevel1, cislevel2, iso27001]
1.17 support [check117] Maintain current contact details [Medium] [group1, cislevel1, cislevel2]
1.18 support [check118] Ensure security contact information is registered [Medium] [group1, cislevel1, cislevel2]
```
The output should be something like:
```
INFO: This is an AWS GovCloud account and there is no root account to perform checks. more info here https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-iam.html.
```

so it should be also for these checks:
```
1.1 iam [check11] Avoid the use of the root account [High] [group1, cislevel1, cislevel2, gdpr, pci, iso27001, ffiec]
3.3 iam [check33] Ensure a log metric filter and alarm exist for usage of root account [Medium] [group3, cislevel1, cislevel2, gdpr, hipaa, iso27001, ffiec, soc2, ens]
```
What do you think?

**Comment by justhereforthecroissants** [comment]
@toniblyx that looks great; I didn't realize, but we passed both check11 and check33 which is why it didn't stand out to me. I had copied our commercial metric filters and alarms to our GovCloud so we have a root account check :)

Thank you for the quick feedback.

**Comment by jfagoagas** [comment]
Hi @cajual, could you check this PR https://github.com/prowler-cloud/prowler/pull/1160 to test if the related fix addresses the issues you found?

Thanks!
