### ISSUE TITLE
HTML file not providing Scoring Information when using exclusions.

### ISSUE THREAD

**Issue by justhereforthecroissants** [prowler-cloud/prowler#827]
Report Information:

    Version: 2.4.0-07042021
    Parameters used: -r us-gov-west-1 -E check12,check113,check114,check115,check117,check118,extra7103 -M html
    Date: 2021-06-23T14:38:45Z 

Scoring Information:

    Prowler Score: PROWLER_SCORE%
    Total Resources: TOTAL_RESOURCES
    Passed: PASS_COUNTER
    Failed: FAIL_COUNTER
    Total Checks Executed: CHECKS_COUNTER

**Comment by toniblyx** [comment]
Thanks @cajual, Can you confirm same behavior for global regions? also if you try with a group (like `-g rds`) instead using -E, do you get values?

**Comment by toniblyx** [comment]
Here is an screenshot of the latest code in branch 2.5, scoring info is there so it can be an issue with -E.

![Screenshot 2021-06-24 at 10 46 01 AM](https://user-images.githubusercontent.com/3985464/123232540-8b993f00-d4d9-11eb-93fa-67bc565c542f.png)

**Comment by justhereforthecroissants** [comment]
@toniblyx sorry for the delay, was on vacation. Will check this and report back.

**Comment by toniblyx** [comment]
Ok, I could reproduce it in the latest version. Not it is fixed in branch 2.5.1
