### ISSUE TITLE
HTML Output - Ambiguous Redirects Error

### ISSUE THREAD

**Issue by Craw13r** [prowler-cloud/prowler#828]
When I am running "./prowler", I am getting results in the terminal.
But when I am running "./prowler -M html" I am getting the Ambiguous Redirect errors.

![image](https://user-images.githubusercontent.com/86422440/123289184-390e5180-d4de-11eb-822e-1477a1cba7f6.png)

**Comment by toniblyx** [comment]
can you provide the steps followed to make prowler run? Did you install all dependencies? As per the credentials info there I would say that `jq` is not installed. Probably the error handing there is not working properly.

**Comment by Craw13r** [comment]
I checked and I have jq and detect-secrets installed on the machines as per the instructions.
![image](https://user-images.githubusercontent.com/86422440/123304819-657d9a00-d4ed-11eb-86ff-01f2bab83baa.png)

**Comment by toniblyx** [comment]
ok, can you run prowler as `bash -x ./prowler` and see what is wrong? that will be really verbose but you will get the error. Let me know please.

**Comment by Craw13r** [comment]
These are few of the screenshots:
![image](https://user-images.githubusercontent.com/86422440/123306529-69122080-d4ef-11eb-9ed1-4fa7df0b473c.png)
![image](https://user-images.githubusercontent.com/86422440/123307103-1ab15180-d4f0-11eb-85a8-ffb7567b30df.png)
![image](https://user-images.githubusercontent.com/86422440/123307299-53e9c180-d4f0-11eb-9cd1-2cf0291fc4f6.png)

**Comment by Craw13r** [comment]
Hello,
The issue is resolved.
Thank You

**Comment by w0rmr1d3r** [comment]
How was it resolved @Craw13r ? A missing dependency? Something with your localhost?
Thank you!

**Comment by toniblyx** [comment]
I don't see it in those screenshots, can you let us know please @Craw13r? We can improve docs and the experience. Thanks.

**Comment by Craw13r** [comment]
It was the problem with the AWS CLI, the aws configure was setting the credentials for local user, and I was getting that ambiguous redirects error, but when I ran the AWS CONFIGURE with "sudo", it fixed the problem.

**Comment by w0rmr1d3r** [comment]
Thanks @Craw13r !
