### ISSUE TITLE
Cosmetic error related executing prowler on EC2 with permissions granted via EC2 attached IAM Role

### ISSUE THREAD

**Issue by mikevirgilio** [prowler-cloud/prowler#837]
Version: v2.4.0-07042021

Scenario 1:
When executing prowler from an EC2 instances where IAM permissions have been granted by attaching an IAM role to the EC2 instance and instructing it to Assume an IAM Role (-R ProwlerExecRole) , errors are generated during " This report is being generated using credentials below: " and with each check, but they appear to be cosmetic only.
These errors occur for auditing the local account and remote accounts.
The IAM Role grants access to assume IAM Roles in accounts for auditing.

"parse error: Invalid numeric literal at line 1, column 4"

./prowler -R ProwlerExecRole
                          _
  _ __  _ __ _____      _| | ___ _ __
 | '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
 | |_) | | | (_) \ V  V /| |  __/ |
 | .__/|_|  \___/ \_/\_/ |_|\___|_|v2.4.0-07042021
 |_| the handy cloud security tool

 Date: Sat Jul 31 13:59:59 UTC 2021

 Colors code for results:
 INFO (Information), PASS (Recommended value),  WARNING (Ignored by whitelist),  FAIL (Fix required),  Not Scored

 This report is being generated using credentials below:

 AWS-CLI Profile: [default] AWS API Region: [us-east-1] AWS Filter Region: [all]
 AWS Account: [XXXXXXXXXXXX] UserId: [parse error: Invalid numeric literal at line 1, column 4]
 Caller Identity ARN: [parse error: Invalid numeric literal at line 1, column 4]

parse error: Invalid numeric literal at line 2, column 4
parse error: Invalid numeric literal at line 2, column 4
parse error: Invalid numeric literal at line 2, column 4
parse error: Invalid numeric literal at line 2, column 4

 1.0 Identity and Access Management - CIS only - [group1] ***********
expr: syntax error
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6
parse error: Invalid numeric literal at line 1, column 6

Scenario 2:
When executing prowler from an EC2 instances where IAM permissions have been granted by attaching an IAM role to the EC2 instance and scanning the local account only, errors are generated during " This report is being generated using credentials below: ", but they appear to be cosmetic only.

./prowler
                          _
  _ __  _ __ _____      _| | ___ _ __
 | '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
 | |_) | | | (_) \ V  V /| |  __/ |
 | .__/|_|  \___/ \_/\_/ |_|\___|_|v2.4.0-07042021
 |_| the handy cloud security tool

 Date: Sat Jul 31 14:02:51 UTC 2021

 Colors code for results:
 INFO (Information), PASS (Recommended value),  WARNING (Ignored by whitelist),  FAIL (Fix required),  Not Scored

 This report is being generated using credentials below:

 AWS-CLI Profile: [default] AWS API Region: [us-east-1] AWS Filter Region: [all]
 AWS Account: [parse error: Invalid numeric literal at line 1, column 4] UserId: [parse error: Invalid numeric literal at line 1, column 4]
 Caller Identity ARN: [parse error: Invalid numeric literal at line 1, column 4]

 1.0 Identity and Access Management - CIS only - [group1] ***********

 0.1 Generating AWS IAM Credential Report...

=============
bash -x related output:

+ echo -e ' This report is being generated using credentials below:\n'
 This report is being generated using credentials below:

+ echo -e ' AWS-CLI Profile: [default] AWS API Region: [us-east-1] AWS Filter Region: [all]'
 AWS-CLI Profile: [default] AWS API Region: [us-east-1] AWS Filter Region: [all]
+ [[ 0 -eq 1 ]]
+ echo -e ' AWS Account: [XXXXXXXXXXXX] UserId: [parse error: Invalid numeric literal at line 1, column 4]'
 AWS Account: [XXXXXXXXXXXX] UserId: [parse error: Invalid numeric literal at line 1, column 4]
+ echo -e ' Caller Identity ARN: [parse error: Invalid numeric literal at line 1, column 4]'
 Caller Identity ARN: [parse error: Invalid numeric literal at line 1, column 4]
+ [[ 255 -eq 0 ]]
+ echo ''
...
+ [[ -z '' ]]
+ /usr/bin/aws --profile default sts assume-role --role-arn arn: Invalid numeric literal at line 1, column 4:iam::XXXXXXXXXXXX:role/ProwlerExecRole --role-session-name ProwlerAssessmentSession --region us-east-1 --duration-seconds 3600
++ grep AccessDenied /tmp/prowler.sts_assumed-MmR8Lv

**Comment by toniblyx** [comment]
I think this is fixed in branch 2.5. Can you please test it?
