### ISSUE TITLE
Check extra73 (GetAccountPublicAccessBlock) fails when an IAM Role is assumed by prowler and an AWS account (The local account or a remote account) is audited.

### ISSUE THREAD

**Issue by mikevirgilio** [prowler-cloud/prowler#838]
Version: v2.4.0-07042021

#Check extra73 (GetAccountPublicAccessBlock) fails when an IAM Role is assumed by prowler and an AWS account (The local account or a remote account) is audited.
#NOTE: IF the EC2 IAM Role (which is primarily used to assume ProwlerExecRole in all accounts) has the SecurityAudit managed IAM Policy attached, the local account will successfully audit while all remote fail

#When auditing audit accounts for extra73..  First check states INFO and second states FAIL (Due to Access Denied) "ACCESS DENIED GETTING PUBLICACCESSBLOCK CONFIGURATION FOR AWS ACCOUNT"
#Associated CloudTrail Log and bash -x attached (SANITIZED). Error: Caller id does not match the account id in the endpoints.
#The account where this command is being executed is XXXXXXXXXXXX
#The remote account being audited is YYYYYYYYYYYY
[CloudTrail-Sanitized.txt](https://github.com/toniblyx/prowler/files/6911341/CloudTrail-Sanitized.txt)
[bash_x-sanitized.txt](https://github.com/toniblyx/prowler/files/6911342/bash_x-sanitized.txt)

./prowler -R ProwlerExecRole -A YYYYYYYYYYYY -c extra73  -M csv -n
7.03 [extra73] Ensure there are no S3 buckets open to Everyone or Any AWS user (Not Scored) (Not part of CIS benchmark)
,YYYYYYYYYYYY,us-east-1,7.03,INFO,Not Scored,Extra,[extra73] Ensure there are no S3 buckets open to Everyone or Any AWS user (Not Scored) (Not part of CIS benchmark),Looking for open S3 Buckets (ACLs and Policies) in all regions...  ,Software and Configuration Checks,Critical,s3,AwsS3Bucket,Software and Configuration Checks,Even if you enable all possible bucket ACL options available in the Amazon S3 console the ACL alone does not allow everyone to download objects from your bucket. Depending on which option you select any user could perform some actions.,You can enable block public access settings only for access points; buckets; and AWS accounts. Amazon S3 does not support block public access settings on a per-object basis. When you apply block public access settings to an account; the settings apply to all AWS Regions globally. The settings might not take effect in all Regions immediately or simultaneously; but they eventually propagate to all Regions.,https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html,Data Protection
,YYYYYYYYYYYY,us-east-1,7.03,FAIL,Not Scored,Extra,[extra73] Ensure there are no S3 buckets open to Everyone or Any AWS user (Not Scored) (Not part of CIS benchmark),Access Denied getting PublicAccessBlock configuration for AWS account,Software and Configuration Checks,Critical,s3,AwsS3Bucket,Software and Configuration Checks,Even if you enable all possible bucket ACL options available in the Amazon S3 console the ACL alone does not allow everyone to download objects from your bucket. Depending on which option you select any user could perform some actions.,You can enable block public access settings only for access points; buckets; and AWS accounts. Amazon S3 does not support block public access settings on a per-object basis. When you apply block public access settings to an account; the settings apply to all AWS Regions globally. The settings might not take effect in all Regions immediately or simultaneously; but they eventually propagate to all Regions.,https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html,Data Protection

**Comment by toniblyx** [comment]
This check has been improved in 2.5 so this should have been fixed. Please meke sure you use the latest verion 2.5.1 (in a branch so far, not master).
