### ISSUE TITLE
Prowler 2.5 - HTML Output - Service Column Data corrupted / Formatting issue

### ISSUE THREAD

**Issue by a-vj** [prowler-cloud/prowler#847]
Prowler 2.5 adds **[1;35m**AWS Service Name**[0;39m** to the Service Column. Please refer to the screenshot below

![image](https://user-images.githubusercontent.com/4490696/129433189-4e737398-b8f8-4e78-a0d2-b30112518b76.png)

**Comment by toniblyx** [comment]
Thanks @a-vj, I will see what is going on.

**Comment by toniblyx** [comment]
Fixed here 623e62ad3f36cabf368a7d4d48a83f7ed7d6be76
