### ISSUE TITLE
ITEM_SCORED and ITEM_LEVEL in csv

### ISSUE THREAD

**Issue by CenturionGamer** [prowler-cloud/prowler#848]
ITEM_SCORED and ITEM_LEVEL are both blank in the results. This happened for multiple checks.

**Comment by w0rmr1d3r** [comment]
Hello @CenturionGamer !
Can you give us some images where that is failing?
How did you run Prowler?

Thanks!

**Comment by estemendoza** [comment]
Hi! I am having the same issue. I executed prowler like this: `./prowler -c check310 -M csv` and then the CSV file looked like this:

<img width="682" alt="Screenshot 2021-08-18 at 11 15 53" src="https://user-images.githubusercontent.com/545757/129872232-3f4bcd69-2f40-4773-8f15-ff59ac22f63d.png">

**Comment by estemendoza** [comment]
I am no good with Bash, but could this be the issue? These lines are commented out

https://github.com/toniblyx/prowler/blob/e0f60114f4465205cf782aea108c521d84a7f78d/include/outputs#L240-L258

**Comment by CenturionGamer** [comment]
@w0rmr1d3r - Good morning! Thanks for responding to this issue. See the comment above from @estemendoza and the code he posted. I ran Prowler the same way as @estemendoza did.

**Comment by w0rmr1d3r** [comment]
Can we try again uncommenting those lines that @estemendoza says?

**Comment by estemendoza** [comment]
Hi @w0rmr1d3r, I tried enabling those lines and now they show up on the report, but they always show as "Unspecified", no matter what check I execute, so I think that doesn't solve the issue

**Comment by w0rmr1d3r** [comment]
Let's try another thing, can you try running Prowler, but without specific checks? Just with a group.
For instance, execute Prowler so it runs the whole IAM group and the output is csv. With those lines enabled!

Can you try that and tell us what does appear?

Thank you @estemendoza !

**Comment by estemendoza** [comment]
@w0rmr1d3r No problem, executed the following command: `./prowler -g group1 -M csv` and same result

<img width="371" alt="Screenshot 2021-08-18 at 17 10 59" src="https://user-images.githubusercontent.com/545757/129923876-090f91d7-7d57-46df-a866-0c62979078f3.png">

**Comment by toniblyx** [comment]
hey guys! My bad, I should have included that information in the release notes, sorry about that. I removed those fields because are only used by CIS checks, and now Prowler is way more than just CIS checks. The plan is to have another way to identify checks that belong to a particular standard or framework. If you think Scored/Not Scored and Level is really important for you, please let me know.

**Comment by CenturionGamer** [comment]
@toniblyx - Hey man! Thanks for the reply. I'll connect with @estemendoza and see how relevant those columns are, and if we need them.

**Comment by snotrauk** [comment]
The level is important for the CIS checks IMO. Would rather that stayed.

**Comment by toniblyx** [comment]
@shaunography yes, I kind of agree for CIS checks only. The plan is to change the way checks are related to security frameworks and regulations so that will change but the implementation is not clear yet in terms of checks metadata.

**Comment by toniblyx** [comment]
Hey @shaunography @estemendoza @CenturionGamer @w0rmr1d3r,

This will come back in version 3 with the reachitecture of checks and implementation of compliance related information per check. Item scored won't be included but CIS Level will.

**Comment by eprothro** [comment]
I agree keeping the CIS level / scored fields -- at least until there is a replacement available. Our compliance review requires being able to report on (and thus filter by) CIS Scored checks by level. Since these fields were removed with any kind of replacement we can't use the current version.

**Comment by toniblyx** [comment]
Watch out! I have added back CIS Level to the 2.5.1 branch that will be merged to master soon.  It's added to CSV, HTML and JSON outputs.

**Comment by toniblyx** [comment]
Now this one can be closed :D

**Comment by toniblyx** [comment]
![Screenshot 2021-11-11 at 13 37 55](https://user-images.githubusercontent.com/3985464/141300543-dccb4a3c-7857-4929-ae16-47f67c3afe7f.png)

**Comment by eprothro** [comment]
Thank you for the quick consideration!

**Comment by toniblyx** [comment]
You are welcome, it is actually in branch 2.6, this has many changes and fixes that deserves a minor version instead.
