### ISSUE TITLE
Enhance secrets group: Find secrets in EC2 Auto Scaling Launch Template

### ISSUE THREAD

**Issue by kamiryo** [prowler-cloud/prowler#852]
I'm having issues with "[extra775] Find secrets in EC2 Auto Scaling Launch Configuration".
I checked the script of extra775, and I think it uses the secretsDetector to check the UserData inside the launch-configuration, but I also feel that there should be a rule to check the UserData inside the launch-template. However, I feel a rule to check UserData in launch-template is also necessary.
(I feel that creating a new one with different rules would be a good idea.)

Reference:
https://docs.aws.amazon.com/autoscaling/ec2/userguide/LaunchTemplates.html

> We recommend that you use launch templates to ensure that you're accessing the latest features and improvements. Not all Amazon EC2 Auto Scaling features are available when you use launch configurations. Not all Amazon EC2 Auto Scaling features are available when you use launch configurations.

**Comment by w0rmr1d3r** [comment]
Thank you @kamiryo , I believe this issue is somehow duplicated (or just adding more info) to this other one -> https://github.com/toniblyx/prowler/issues/422

Cheers!

**Comment by toniblyx** [comment]
@kamiryo can you confirm where could those credentials could be stored? extra775 search for them at `LaunchConfigurations[*].UserData`. What else UserData inside the launch-template? I don't see that in docs.

**Comment by jfagoagas** [comment]
Hi @kamiryo, can you provide us more information about this issue?

**Comment by jfagoagas** [comment]
Hi @kamiryo, we are closing this issue. Please, feel free to reopen it if you can provide more information.

Thanks!

**Comment by rieck-srlabs** [comment]
@jfagoagas Might make sense to reopen this while work on PR #4076 is ongoing.
