### ISSUE TITLE
Check extra7123 not showing recent changes (only cached ones?)

### ISSUE THREAD

**Issue by w0rmr1d3r** [prowler-cloud/prowler#854]
Hello @toniblyx !
I came accross the [check extra 7123](https://github.com/toniblyx/prowler/blob/master/checks/check_extra7123) regarding user with 2 active access keys and I wanted to do some tests.

I found a user with 2 active access keys, went to the IAM console and deactivated and then deleted the key.
I rerun the check and it keep saying that the user I deleted the key from, still had 2 active access keys, no way!
Reloaded IAM console, only 1 active access key.
Rerun the check, still saying the same, that user had 2 active access keys.

Went to the check and found out that it was working, not with the AWS CLI directly but with `$TEMP_REPORT_FILE`.

That's where I got lost, I don't know how that file works or what is it saving in it.
However, I managed to delete the temp file and rerun the check again, still the same result even though that user only has 1 active access key.

Can you provide any context about `$TEMP_REPORT_FILE` and why that check uses it instead of AWS CLI?

Thank you!

PS: I searched for closed issues regarding this, but found none

**Comment by toniblyx** [comment]
That information comes from the credentials report that is actually generated every 4 hours as you can see here https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_getting-report.html
> You can generate a credential report as often as once every four hours

**Comment by w0rmr1d3r** [comment]
Perfect! Thank you @toniblyx !
Closing the issue since it's resolved!
