### ISSUE TITLE
extra784 logic seems to be wrong

### ISSUE THREAD

**Issue by tayivan-sg** [prowler-cloud/prowler#855]
This check(extra 784) checks if there is internal users in elasticsearch and should fail if there is any. 
Currently the logic fails test when there is no internal user instead. 

https://github.com/toniblyx/prowler/blob/master/checks/check_extra784 line 32 should have a 'not' operator. 
line 33 and line 35 should be changed accordingly.

**Comment by tayivan-sg** [comment]
#856 Fix bug in extra 784

**Comment by w0rmr1d3r** [comment]
Hi @toniblyx & @tayivan-sg !

Since the PR https://github.com/toniblyx/prowler/pull/856 has been merged, I believe we can close this issue :)

Cheers!
