### ISSUE TITLE
R can take role arn as well

### ISSUE THREAD

**Issue by mmuller88** [prowler-cloud/prowler#859]
As I develop cdk-prowler https://github.com/mmuller88/cdk-prowler and currently work on multi accounts. For the prowler master role you would need to set it up in every account with like using stack set which is currently not supported by CDK. It would be massively conviently if we could instead just pass the cross account role per the R parameter as well eg: 

./prowler -A 111222333 -R arn:aws:iam::999999:role/ProwlerAudit . 

I will open a PR soon to show you the necessary small changes. 

Thanks :)

**Comment by mmuller88** [comment]
opened a PR #860

**Comment by toniblyx** [comment]
Added to branch 2.5.1 a827504
