### ISSUE TITLE
S3 check -  extra73

### ISSUE THREAD

**Issue by zorangagic** [prowler-cloud/prowler#87]
I got errors running extra73:
       INFO! Looking for open S3 Buckets (ACLs and Policies) in all regions...
       mktemp: too few X's in template ‘prowler-123456789012-mybucket.policy’
      ./prowler: line 1444: $TEMP_POLICY_FILE: ambiguous redirect

To resolve I changed prowler from:
    TEMP_POLICY_FILE=$(mktemp  -t prowler-${ACCOUNT_NUM}-${bucket}.policy)
to:
    TEMP_POLICY_FILE=prowler-${ACCOUNT_NUM}-${bucket}.policy

**Comment by toniblyx** [comment]
Thanks @zorangagic for reporting the issue, it is due to the difference between GNU and BSD mktemp. I have fixed it in PR #88
