### ISSUE TITLE
Check extra734 gives a false positive

### ISSUE THREAD

**Issue by rustic** [prowler-cloud/prowler#893]
Line 75 of checks/check_extra734 performs a check for the condition: .Condition.StringEquals."s3:x-amz-server-side-encryption" != null". The condition check should be for "StringNotEquals"

Given the code example at [https://docs.aws.amazon.com/codepipeline/latest/userguide/S3-artifact-encryption.html](https://docs.aws.amazon.com/codepipeline/latest/userguide/S3-artifact-encryption.html)
```
        {
            "Sid": "DenyUnEncryptedObjectUploads",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::codepipeline-us-west-2-89050EXAMPLE/*",
            "Condition": {
                "StringNotEquals": {
                    "s3:x-amz-server-side-encryption": "aws:kms"
                }
            }
        },
```

Using StringNotEquals would allow the CHECK_BUCKET_SSE_POLICY_PRESENT check to not be empty and the subsequent CHECK_BUCKET_SSE_POLICY_VALUE check would report "aws:kms" and PASS the finding.

it looks like StringNotEquals was previously set on this line in this diff: [https://github.com/toniblyx/prowler/commit/669469e618ab588839105e67187e36ce69a12182#diff-f1a4deca3e3a960af9d8beab029f4bd476a2ef451e303b7911d3671dc0f2940d ](https://github.com/toniblyx/prowler/commit/669469e618ab588839105e67187e36ce69a12182#diff-f1a4deca3e3a960af9d8beab029f4bd476a2ef451e303b7911d3671dc0f2940d )

Thanks!

**Comment by toniblyx** [comment]
Thanks for the heads up @rustic, going to look at it soon and fix it.

**Comment by toniblyx** [comment]
Feel free also to send a PR with the fix to the branch 2.5.1 if you like.

**Comment by rustic** [comment]
Pull request issued. Thanks!

**Comment by toniblyx** [comment]
Merged https://github.com/toniblyx/prowler/pull/896, thanks!
