### ISSUE TITLE
line 417: [: user/XXXX.XXXX: unary operator expected

### ISSUE THREAD

**Issue by virtualjj** [prowler-cloud/prowler#9]
I get the following error for check113.

line 417: [: user/XXXX.XXXX: unary operator expected

![image](https://cloud.githubusercontent.com/assets/10323889/18687845/dad5f094-7fbc-11e6-84ec-58be73cd74cf.png)

Resolved the error by replacing line 417 with:

`if [[ $COMMAND113 ]]; then`

![image](https://cloud.githubusercontent.com/assets/10323889/18687947/51608c2e-7fbd-11e6-9d6a-56f4b81282a8.png)

However I think this is a limitation of the AWS CLI because there doesn't appear to be a way to determine whether or not the MFA device is actually hardware or not using CIS's recommended Audit check of **aws iam get-account-summary | grep AccountMFAEnabled**. In my case my root account has a virtual MFA assigned, not hardware but the status is 1.

https://github.com/Alfresco/aws-cis-security-benchmark/blob/master/prowler#L415 is querying VirtualMFADevices but I don't see a way to query anything hardware related with the subcommand list-mfa-devices.

**Comment by toniblyx** [comment]
Thanks @virtualjj, as you say there I didn't find a query to figure out if hardware MFA is used so I queried for just MFA which is also good and pretty valid check. I'm fixing it now as you suggest and also adding a comment to clarify that, in case of OK, it is Virtual MFA.

**Comment by toniblyx** [comment]
as you say, running:
aws iam get-account-summary | grep MFA

I get:
        "MFADevicesInUse": 1,
        "MFADevices": 1,
        "AccountMFAEnabled": 1,

In my case is also use virtual MFA, so no way to see if it is hw or not.

**Comment by virtualjj** [comment]
Cool - I raised a support request with AWS to see if there is a workaround for this and will update as soon as I get an answer. 

Thanks again for this very helpful project!

**Comment by toniblyx** [comment]
Thanks @virtualjj I will also go ahead and change the check command with this one which seems to be more accurate despite we don't know if it is HW or SW: aws iam get-account-summary |grep AccountMFAEnabled | awk -F":\ " '{ print $2 }'|sed 's/,//'

**Comment by toniblyx** [comment]
@virtualjj just commited the change, I have tested it in two accounts and it works. You can test it now. Glad you find it helpful.

**Comment by virtualjj** [comment]
Tested and confirmed:

![image](https://cloud.githubusercontent.com/assets/10323889/18717631/7dd7ba9a-805b-11e6-80e2-9a19cbe143c0.png)

I think this is a reasonable message since the hardware MFAs listed as supported by AWS have synchronization issues which isn't worth the trouble in my opinion.

I did receive a reply from AWS support that root MFA API / CLI calls are limited for security reasons citing this resource: 

http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_enable_cliapi.html

The workaround proposed by AWS support requires having paid support for Trusted Advisor and these commands that I wasn't able to test since my dev AWS account doesn't have paid support:

`sudo yum install jq`

`check_id=$(aws support describe-trusted-advisor-checks --language en --region us-east-1 |  jq -r '.checks[] | select(.name == "MFA on Root Account") | .id')`

`aws support describe-trusted-advisor-check-result --check-id "$check_id" --region us-east-1 | jq -r '.result.status'`

**Comment by toniblyx** [comment]
I have checked those commands with one of our paid support accounts and I don't think it adds more value or information to what I currently have with the existing check. Another reason to write prowler was to not to depend on your support status to get good advises about security. Thanks for your time looking at it @virtualjj

**Comment by virtualjj** [comment]
Awesome and agreed - thanks again!
