### ISSUE TITLE
Removing the reference to: http://bit.ly/2g3PEf7

### ISSUE THREAD

**Issue by hemi-hga** [prowler-cloud/prowler#96]
This reference doesn't add much information and may encourage uninformed users to click on unverified links. Whoever is working with the tool should also have the benchmark at hand to understand/handle issues.

I'll be happy to create a pull request for this issue, I'm just not sure how is best to tackle this.
Maybe remove all references from the reports aside from a link at the top of the report.

**Comment by toniblyx** [comment]
Thanks @hemedga. Why do you think it may confuse users? The way to understand all these checks are looking at the CIS Benchmark guide. Did I miss something?

**Comment by hemi-hga** [comment]
From a security standpoint, url shorteners may  be used to spread malware and web attacks.
Users click on these links without checking their origin.

I prefer to publish urls which are verified for the source or fully controlled by my organization.

**Comment by toniblyx** [comment]
got it, you are talking about this: https://github.com/Alfresco/prowler/blob/0e0f3a334e60e57777a65f0eebe7e50900459b8e/prowler#L440

**Comment by toniblyx** [comment]
You are right. You can send a PR with the way you consider is better. I would be glad to accept it.
